"""
Django settings for xing-cloud project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import json
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _resolve_config_file():
    raw_path = os.getenv('XING_CLOUD_CONFIG_FILE', 'config.json')
    path = Path(raw_path).expanduser()
    if not path.is_absolute():
        path = BASE_DIR / path
    return path


def _load_app_config(path):
    if not path.exists():
        return {}
    try:
        with path.open('r', encoding='utf-8') as handle:
            config = json.load(handle)
    except json.JSONDecodeError as exc:
        raise RuntimeError(f'Invalid JSON in config file {path}: {exc}') from exc
    if not isinstance(config, dict):
        raise RuntimeError(f'Config file {path} must contain a JSON object.')
    return config


APP_CONFIG_FILE = _resolve_config_file()
APP_CONFIG = _load_app_config(APP_CONFIG_FILE)


def _app_config_section(*names):
    for name in names:
        section = APP_CONFIG.get(name, {})
        if isinstance(section, dict):
            return section
    return {}


def _setting_value(section, keys, env_names=(), default=None, allow_blank=False):
    if isinstance(keys, str):
        keys = (keys,)
    for key in keys:
        if key in section:
            value = section[key]
            if allow_blank or value not in (None, ''):
                return value
    for env_name in env_names:
        value = os.getenv(env_name)
        if value is not None and (allow_blank or value != ''):
            return value
    return default


def _bool_value(value, default=False):
    if value in (None, ''):
        return default
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {'1', 'true', 'yes', 'on', 'y'}


FEATURE_CONFIG = _app_config_section('features')
SYSTEM_POSTURE_ENABLED = _bool_value(
    _setting_value(
        FEATURE_CONFIG,
        ('system_posture_enabled', 'systemPostureEnabled', 'system_posture', 'systemPosture'),
        ('XING_CLOUD_SYSTEM_POSTURE_ENABLED', 'SYSTEM_POSTURE_ENABLED'),
        False,
    ),
    False,
)


def _int_value(value, name, default=None):
    if value in (None, ''):
        return default
    try:
        return int(value)
    except (TypeError, ValueError) as exc:
        raise RuntimeError(f'{name} must be an integer.') from exc


def _sqlite_database_config(section):
    db_name = _setting_value(
        section,
        ('path', 'sqlite_path', 'file', 'name'),
        ('SQLITE_NAME', 'SQLITE_PATH', 'DATABASE_NAME', 'DB_NAME'),
        BASE_DIR / 'db.sqlite3',
    )
    if isinstance(db_name, str) and db_name != ':memory:':
        db_path = Path(db_name).expanduser()
        if not db_path.is_absolute():
            db_path = BASE_DIR / db_path
        db_name = db_path
    return {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': db_name,
    }


def _mysql_database_config(section):
    try:
        import pymysql

        pymysql.install_as_MySQLdb()
    except ImportError as exc:
        raise RuntimeError('MySQL database support requires pymysql to be installed.') from exc

    db_name = _setting_value(
        section,
        ('database_name', 'database', 'name'),
        ('MYSQL_DATABASE_NAME', 'MYSQL_DATABASE', 'MYSQL_DB', 'DATABASE_NAME', 'DB_NAME'),
        '',
    )
    if not db_name:
        raise RuntimeError('MySQL database is enabled but database.database_name is empty.')

    options = section.get('options', {})
    if not isinstance(options, dict):
        raise RuntimeError('database.options must be a JSON object.')
    options = dict(options)
    charset = _setting_value(
        section,
        'charset',
        ('MYSQL_CHARSET', 'DATABASE_CHARSET', 'DB_CHARSET'),
        'utf8mb4',
    )
    options.setdefault('charset', charset)

    config = {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': db_name,
        'USER': _setting_value(
            section,
            'user',
            ('MYSQL_USER', 'DATABASE_USER', 'DB_USER'),
            'root',
        ),
        'PASSWORD': _setting_value(
            section,
            'password',
            ('MYSQL_PASSWORD', 'DATABASE_PASSWORD', 'DB_PASSWORD'),
            '',
            allow_blank=True,
        ),
        'HOST': _setting_value(
            section,
            'host',
            ('MYSQL_HOST', 'DATABASE_HOST', 'DB_HOST'),
            '127.0.0.1',
        ),
        'PORT': str(_setting_value(
            section,
            'port',
            ('MYSQL_PORT', 'DATABASE_PORT', 'DB_PORT'),
            '3306',
        )),
        'OPTIONS': options,
    }

    conn_max_age = _setting_value(
        section,
        ('conn_max_age', 'connMaxAge'),
        ('DATABASE_CONN_MAX_AGE', 'DB_CONN_MAX_AGE'),
        None,
    )
    if conn_max_age is not None:
        config['CONN_MAX_AGE'] = _int_value(conn_max_age, 'database.conn_max_age')

    test_config = section.get('test')
    if test_config is not None:
        if not isinstance(test_config, dict):
            raise RuntimeError('database.test must be a JSON object.')
        config['TEST'] = test_config

    return config


def _build_database_config():
    section = _app_config_section('database', 'db')
    engine = str(_setting_value(
        section,
        ('type', 'engine'),
        ('DATABASE_ENGINE', 'DB_ENGINE'),
        'sqlite',
    ) or 'sqlite').strip().lower()

    if engine in {'', 'sqlite', 'sqlite3', 'django.db.backends.sqlite3'}:
        return {'default': _sqlite_database_config(section)}
    if engine in {'mysql', 'mariadb', 'django.db.backends.mysql'}:
        return {'default': _mysql_database_config(section)}

    raise RuntimeError(f'Unsupported database engine: {engine}')


def _build_cache_config():
    section = _app_config_section('cache')
    backend = str(_setting_value(
        section,
        ('type', 'backend', 'engine'),
        ('CACHE_BACKEND',),
        '',
    ) or '').strip().lower()
    redis_location = _setting_value(
        section,
        ('redis_url', 'location', 'url'),
        ('REDIS_URL', 'CACHE_REDIS_URL'),
        '',
    )
    timeout = _int_value(_setting_value(
        section,
        ('default_timeout_seconds', 'timeout_seconds', 'timeout', 'default_timeout', 'defaultTimeout'),
        ('CACHE_DEFAULT_TIMEOUT',),
        300,
    ), 'cache.timeout', 300)
    key_prefix = _setting_value(
        section,
        ('key_prefix', 'keyPrefix'),
        ('CACHE_KEY_PREFIX',),
        'xing-cloud',
        allow_blank=True,
    )

    redis_requested = backend in {'redis', 'django-redis', 'django_redis'} or (not backend and bool(redis_location))
    if redis_requested:
        if not redis_location:
            raise RuntimeError('Redis cache is enabled but cache.redis_url is empty.')
        options = section.get('options', {})
        if not isinstance(options, dict):
            raise RuntimeError('cache.options must be a JSON object.')
        options = dict(options)
        options.setdefault('CLIENT_CLASS', 'django_redis.client.DefaultClient')
        ignore_exceptions = _setting_value(
            section,
            ('ignore_redis_errors', 'ignore_exceptions', 'ignoreExceptions'),
            ('CACHE_IGNORE_EXCEPTIONS',),
            True,
        )
        options.setdefault('IGNORE_EXCEPTIONS', _bool_value(ignore_exceptions, True))
        return {
            'default': {
                'BACKEND': 'django_redis.cache.RedisCache',
                'LOCATION': redis_location,
                'TIMEOUT': timeout,
                'KEY_PREFIX': key_prefix,
                'OPTIONS': options,
            },
        }

    if backend in {'', 'locmem', 'local-memory', 'local', 'memory', 'in-memory', 'django.core.cache.backends.locmem.locmemcache'}:
        return {
            'default': {
                'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
                'LOCATION': 'xing-cloud-local-cache',
                'TIMEOUT': timeout,
                'KEY_PREFIX': key_prefix,
            },
        }

    raise RuntimeError(f'Unsupported cache backend: {backend}')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-ag#xxnjm^46$=ye()w$yma8r8oy3&wfq!8_=bm!kwe0e((&y3-',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _bool_value(os.getenv('DEBUG'), True)

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', '*').split(',')
    if host.strip()
]
XING_CLOUD_PUBLIC_BASE_URL = os.getenv('XING_CLOUD_PUBLIC_BASE_URL', '').rstrip('/')

X_FRAME_OPTIONS = os.getenv('X_FRAME_OPTIONS', 'SAMEORIGIN')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'corsheaders',
    'channels',
    # Local
    'ops.apps.OpsConfig',
    'cmdb',
    'aiops.apps.AiopsConfig',
    'rbac',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'xing_cloud.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'xing_cloud.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = _build_database_config()


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS
CORS_ALLOW_ALL_ORIGINS = _bool_value(os.getenv('CORS_ALLOW_ALL_ORIGINS'), True)

# DRF
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],
}

# Loki
LOKI_URL = ''

LOG_PROVIDER_CONFIGS = {
    'loki': {
        'endpoint': os.getenv('LOKI_URL', LOKI_URL),
    },
    'elk': {
        'endpoint': os.getenv('ELK_URL', ''),
        'auth_type': os.getenv('ELK_AUTH_TYPE', 'none'),
        'username': os.getenv('ELK_USERNAME', ''),
        'password': os.getenv('ELK_PASSWORD', ''),
        'api_key': os.getenv('ELK_API_KEY', ''),
        'bearer_token': os.getenv('ELK_BEARER_TOKEN', ''),
        'index_pattern': os.getenv('ELK_INDEX_PATTERN', 'logs-*'),
        'time_field': os.getenv('ELK_TIME_FIELD', '@timestamp'),
        'message_fields': os.getenv('ELK_MESSAGE_FIELDS', 'message,log,msg'),
    },
    'clickhouse': {
        'endpoint': os.getenv('CLICKHOUSE_URL', ''),
        'username': os.getenv('CLICKHOUSE_USERNAME', ''),
        'password': os.getenv('CLICKHOUSE_PASSWORD', ''),
        'timezone': os.getenv('CLICKHOUSE_TIMEZONE', 'Asia/Shanghai'),
        'collections': [
            {
                'key': 'container-logs',
                'name': 'K8S Container Logs',
                'database': 'container_logs',
                'table': 'logs',
                'time_field': 'timestamp',
                'message_fields': 'message,log_message',
                'level_field': 'log_level',
                'source_fields': 'namespace,pod_name,container_name',
                'search_fields': 'namespace,pod_name,node_name,container_name,log_level,message,log_message,source,log_file_path',
            },
            {
                'key': 'k8s-events',
                'name': 'K8S Events',
                'database': 'container_logs',
                'table': 'events',
                'time_field': 'timestamp',
                'message_fields': 'message,reason',
                'level_field': 'event_type',
                'source_fields': 'namespace,pod_name,source_component',
                'search_fields': 'namespace,pod_name,event_type,reason,message,source_component,source_host,count',
            },
            {
                'key': 'ingress-access',
                'name': 'Ingress Access Logs',
                'database': 'nginxlogs',
                'table': 'nginx_access',
                'time_field': 'timestamp',
                'message_fields': '',
                'level_field': 'status',
                'source_fields': 'domain,server_ip,client_ip',
                'search_fields': 'domain,path,top_path,query,client_ip,remote_ip,xff,status,server_ip,http_user_agent',
            },
        ],
    },
}

OBSERVABILITY_CONFIG = {
    'prometheus': {
        'enabled': os.getenv('PROMETHEUS_ENABLED', '0') != '0',
        'query_url': os.getenv('PROMETHEUS_QUERY_URL', ''),
        'bearer_token': os.getenv('PROMETHEUS_BEARER_TOKEN', ''),
        'api_token': os.getenv('PROMETHEUS_API_TOKEN', ''),
        'timeout': os.getenv('PROMETHEUS_QUERY_TIMEOUT', '6'),
    },
}

CACHES = _build_cache_config()

def _build_channel_layers():
    redis_url = os.getenv('CHANNEL_REDIS_URL') or os.getenv('REDIS_URL', '')
    backend = os.getenv('CHANNEL_LAYER_BACKEND', 'redis' if redis_url else 'memory').strip().lower()

    if backend in {'redis', 'channels-redis', 'channels_redis'}:
        if not redis_url:
            raise RuntimeError('Redis channel layer is enabled but CHANNEL_REDIS_URL/REDIS_URL is empty.')
        return {
            'default': {
                'BACKEND': 'channels_redis.core.RedisChannelLayer',
                'CONFIG': {
                    'hosts': [redis_url],
                },
            },
        }

    return {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }


# ASGI / Channels
ASGI_APPLICATION = 'xing_cloud.asgi.application'
CHANNEL_LAYERS = _build_channel_layers()
