import request from '../request'

const AIOPS_CHAT_TIMEOUT = 120000
const AIOPS_MODEL_TEST_TIMEOUT = 45000

export const getAIOpsBootstrap = () => request.get('/aiops/bootstrap/')
export const getAIOpsKnowledgeGraph = (params) => request.get('/aiops/knowledge-graph/', { params })
export const getAIOpsKnowledgeEnvironments = (params) => request.get('/aiops/knowledge-environments/', { params })
export const getAIOpsBusinessContextOptions = () => request.get('/aiops/knowledge-environments/context-options/')
export const getAIOpsKnowledgeEnvironmentCatalog = () => request.get('/aiops/knowledge-environments/catalog/')
export const createAIOpsKnowledgeEnvironment = (data) => request.post('/aiops/knowledge-environments/', data)
export const updateAIOpsKnowledgeEnvironment = (id, data) => request.patch(`/aiops/knowledge-environments/${id}/`, data)
export const deleteAIOpsKnowledgeEnvironment = (id) => request.delete(`/aiops/knowledge-environments/${id}/`)
export const discoverAIOpsKnowledgeEnvironmentBindings = (code) => request.post('/aiops/knowledge-environments/discover-bindings/', { code })
export const validateAIOpsKnowledgeEnvironmentBindings = (id, live = false) => request.post(`/aiops/knowledge-environments/${id}/validate-bindings/`, { live })
export const inspectAIOpsKnowledgeEnvironment = (id, data, config = {}) => request.post(`/aiops/knowledge-environments/${id}/inspect/`, data, { timeout: AIOPS_CHAT_TIMEOUT, ...config })
export const getAIOpsUnassignedAlerts = () => request.get('/aiops/knowledge-environments/unassigned-alerts/')

export const getAIOpsSessions = (params) => request.get('/aiops/sessions/', { params })
export const createAIOpsSession = (data) => request.post('/aiops/sessions/', data)
export const deleteAIOpsSession = (id, config = {}) => request.post(`/aiops/sessions/${id}/delete_session/`, null, config)
export const getAIOpsMessages = (id, config = {}) => request.get(`/aiops/sessions/${id}/messages/`, config)
export const setAIOpsSessionEnvironment = (id, knowledge_environment_id) => request.post(`/aiops/sessions/${id}/set-environment/`, { knowledge_environment_id })
export const sendAIOpsMessage = (id, data, config = {}) => request.post(`/aiops/sessions/${id}/send_message/`, data, { timeout: AIOPS_CHAT_TIMEOUT, ...config })
export const sendAIOpsMessageAsync = (id, data, config = {}) => request.post(`/aiops/sessions/${id}/send_message_async/`, data, { timeout: 20000, ...config })
export const cancelAIOpsMessage = (sessionId, messageId) => request.post(`/aiops/sessions/${sessionId}/messages/${messageId}/cancel/`)

export const confirmAIOpsAction = (id) => request.post(`/aiops/actions/${id}/confirm/`)
export const cancelAIOpsAction = (id) => request.post(`/aiops/actions/${id}/cancel/`)

export const getAIOpsConfig = (config = {}) => request.get('/aiops/admin/config/', config)
export const updateAIOpsConfig = (data) => request.put('/aiops/admin/config/', data)
export const getAIOpsActions = (config = {}) => request.get('/aiops/admin/actions/', config)
export const preflightAIOpsAction = (data) => request.post('/aiops/admin/actions/preflight/', data)
export const getAIOpsAuditOverview = (params, config = {}) => request.get('/aiops/admin/audit/overview/', { params, ...config })
export const getAIOpsAuditCosts = (params, config = {}) => request.get('/aiops/admin/audit/costs/', { params, ...config })
export const getAIOpsAuditSessions = (params, config = {}) => request.get('/aiops/admin/audit/sessions/', { params, ...config })
export const deleteAIOpsAuditSession = (id) => request.delete(`/aiops/admin/audit/sessions/${id}/`)
export const bulkDeleteAIOpsAuditSessions = (session_ids) => request.post('/aiops/admin/audit/sessions/bulk-delete/', { session_ids })
export const getAIOpsAuditToolInvocations = (params, config = {}) => request.get('/aiops/admin/audit/tool-invocations/', { params, ...config })
export const deleteAIOpsAuditToolInvocation = (id) => request.delete(`/aiops/admin/audit/tool-invocations/${id}/`)
export const bulkDeleteAIOpsAuditToolInvocations = (invocation_ids) => request.post('/aiops/admin/audit/tool-invocations/bulk-delete/', { invocation_ids })
export const getAIOpsAuditSkillTraces = (params, config = {}) => request.get('/aiops/admin/audit/skill-traces/', { params, ...config })
export const bulkDeleteAIOpsAuditSkillTraces = (trace_ids) => request.post('/aiops/admin/audit/skill-traces/bulk-delete/', { trace_ids })
export const getAIOpsAuditActionTraces = (params, config = {}) => request.get('/aiops/admin/audit/action-traces/', { params, ...config })
export const bulkDeleteAIOpsAuditActionTraces = (trace_ids) => request.post('/aiops/admin/audit/action-traces/bulk-delete/', { trace_ids })
export const getAIOpsAuditModelInvocations = (params, config = {}) => request.get('/aiops/admin/audit/model-invocations/', { params, ...config })
export const deleteAIOpsAuditModelInvocation = (id) => request.delete(`/aiops/admin/audit/model-invocations/${id}/`)
export const getAIOpsAuditActions = (params, config = {}) => request.get('/aiops/admin/audit/actions/', { params, ...config })
export const deleteAIOpsAuditAction = (id) => request.delete(`/aiops/admin/audit/actions/${id}/`)
export const bulkDeleteAIOpsAuditActions = (action_ids) => request.post('/aiops/admin/audit/actions/bulk-delete/', { action_ids })

export const getAIOpsProviders = (config = {}) => request.get('/aiops/admin/providers/', config)
export const getAIOpsProviderPresets = (config = {}) => request.get('/aiops/admin/providers/presets/', config)
export const createAIOpsProvider = (data) => request.post('/aiops/admin/providers/', data)
export const updateAIOpsProvider = (id, data) => request.patch(`/aiops/admin/providers/${id}/`, data)
export const deleteAIOpsProvider = (id) => request.delete(`/aiops/admin/providers/${id}/`)
export const testAIOpsProvider = (id) => request.post(`/aiops/admin/providers/${id}/test_connection/`, null, { timeout: AIOPS_MODEL_TEST_TIMEOUT })
export const listAIOpsProviderModels = (id, params) => request.get(`/aiops/admin/providers/${id}/models/`, { params, timeout: AIOPS_MODEL_TEST_TIMEOUT })

export const getAIOpsMcpServers = (config = {}) => request.get('/aiops/admin/mcp-servers/', config)
export const createAIOpsMcpServer = (data) => request.post('/aiops/admin/mcp-servers/', data)
export const updateAIOpsMcpServer = (id, data) => request.patch(`/aiops/admin/mcp-servers/${id}/`, data)
export const deleteAIOpsMcpServer = (id) => request.delete(`/aiops/admin/mcp-servers/${id}/`)
export const testAIOpsMcpServer = (id) => request.post(`/aiops/admin/mcp-servers/${id}/test_connection/`)
export const listAIOpsMcpTools = (id) => request.get(`/aiops/admin/mcp-servers/${id}/list_tools/`)

export const getAIOpsSkills = (config = {}) => request.get('/aiops/admin/skills/', config)
export const getAIOpsSkillMarketplace = (config = {}) => request.get('/aiops/admin/skills/marketplace/', config)
export const cloneAIOpsSkill = (id, data) => request.post(`/aiops/admin/skills/${id}/clone/`, data)
export const createAIOpsSkill = (data) => request.post('/aiops/admin/skills/', data)
export const updateAIOpsSkill = (id, data) => request.patch(`/aiops/admin/skills/${id}/`, data)
export const deleteAIOpsSkill = (id) => request.delete(`/aiops/admin/skills/${id}/`)

export const getAIOpsA2ATasks = (params, config = {}) => request.get('/aiops/a2a/tasks/', { params, ...config })
export const createAIOpsA2ATask = (data) => request.post('/aiops/a2a/tasks/', data)
export const cancelAIOpsA2ATask = (publicId) => request.post(`/aiops/a2a/tasks/${publicId}/cancel/`)
export const runAIOpsA2ATask = (publicId) => request.post(`/aiops/a2a/tasks/${publicId}/run/`)
export const interruptAIOpsA2ATask = (publicId) => request.post(`/aiops/a2a/tasks/${publicId}/interrupt/`)

export const getAIOpsRunbooks = (params, config = {}) => request.get('/aiops/runbooks/', { params, ...config })
export const createAIOpsRunbookDraft = (data) => request.post('/aiops/runbooks/draft/', data)
export const createAIOpsRunbookFromSession = (data) => request.post('/aiops/runbooks/from-session/', data)
export const publishAIOpsRunbook = (id, data = {}) => request.post(`/aiops/runbooks/${id}/publish/`, data)
export const archiveAIOpsRunbook = (id, data = {}) => request.post(`/aiops/runbooks/${id}/archive/`, data)
export const getAIOpsRunbookVersions = (id) => request.get(`/aiops/runbooks/${id}/versions/`)
export const updateAIOpsRunbook = (id, data) => request.patch(`/aiops/runbooks/${id}/`, data)
export const deleteAIOpsRunbook = (id) => request.delete(`/aiops/runbooks/${id}/`)
export const getAIOpsReviewKnowledge = (params, config = {}) => request.get('/aiops/review-knowledge/', { params, ...config })
export const autoIngestAIOpsReviewKnowledge = (data) => request.post('/aiops/review-knowledge/auto-ingest/', data)
export const deleteAIOpsReviewKnowledge = (id) => request.delete(`/aiops/review-knowledge/${id}/`)
export const getAIOpsPlatformMcpManifest = (config = {}) => request.get('/aiops/mcp/manifest/', config)
