import request from '../request'

export const getEventWallAnalysis = (params) => request.get('/events/analysis_wall/', { params })
export const getOperationAuditEvents = (params) => request.get('/events/operation_audit/', { params })
export const pruneOperationAuditEvents = (data) => request.post('/events/prune_operation_audit/', data)
export const getEventWallEvents = (params) => request.get('/events/', { params })
export const getEventWallEvent = (id) => request.get(`/events/${id}/`)
export const getEventWallAssociations = (params) => request.get('/events/associations/', { params })
export const getEventWallFilterOptions = (params) => request.get('/events/filter_options/', { params })
export const getEventSources = (params) => request.get('/event-sources/', { params })
export const getEventSourceSummary = () => request.get('/event-sources/summary/')
export const getEventSourceIngestSpec = () => request.get('/event-sources/ingest_spec/')
export const createEventSource = (data) => request.post('/event-sources/', data)
export const updateEventSource = (type, data) => request.patch(`/event-sources/${type}/`, data)
export const deleteEventSource = (type) => request.delete(`/event-sources/${type}/`)
export const toggleEventSource = (type) => request.post(`/event-sources/${type}/toggle_enabled/`)
export const issueEventSourceToken = (type) => request.post(`/event-sources/${type}/issue_token/`)
export const getEventEnvironments = (params) => request.get('/event-environments/', { params })
export const createEventEnvironment = (data) => request.post('/event-environments/', data)
export const updateEventEnvironment = (code, data) => request.patch(`/event-environments/${code}/`, data)
export const deleteEventEnvironment = (code) => request.delete(`/event-environments/${code}/`)
export const getUnmatchedEventEnvironments = () => request.get('/event-environments/unmatched/')
