import request from '../request'

export const getDashboardStats = () => request.get('/dashboard/stats/')

export const getHosts = (params) => request.get('/hosts/', { params })
export const getHost = (id) => request.get(`/hosts/${id}/`)
export const createHost = (data) => request.post('/hosts/', data)
export const updateHost = (id, data) => request.put(`/hosts/${id}/`, data)
export const deleteHost = (id) => request.delete(`/hosts/${id}/`)
export const testHostConnection = (id) => request.post(`/hosts/${id}/test_connection/`)
export const refreshHostInfo = (id) => request.post(`/hosts/${id}/refresh_info/`)
export const getTaskResourceGroups = (params) => request.get('/task-resource-groups/', { params })
export const createTaskResourceGroup = (data) => request.post('/task-resource-groups/', data)
export const updateTaskResourceGroup = (id, data) => request.put(`/task-resource-groups/${id}/`, data)
export const deleteTaskResourceGroup = (id) => request.delete(`/task-resource-groups/${id}/`)
export const getTaskResourceTree = () => request.get('/task-resource-groups/tree/')
export const getTaskResources = (params) => request.get('/task-resources/', { params })
export const getTaskResourceStats = (params) => request.get('/task-resources/stats/', { params })
export const createTaskResource = (data) => request.post('/task-resources/', data)
export const updateTaskResource = (id, data) => request.put(`/task-resources/${id}/`, data)
export const deleteTaskResource = (id) => request.delete(`/task-resources/${id}/`)
export const getHostTasks = (params) => request.get('/host-tasks/', { params })
export const getHostTask = (id) => request.get(`/host-tasks/${id}/`)
export const createHostTask = (data) => request.post('/host-tasks/', data)
export const deleteHostTask = (id) => request.delete(`/host-tasks/${id}/`)
export const renameHostTask = (id, data) => request.post(`/host-tasks/${id}/rename/`, data)
export const executeHostTask = (id) => request.post(`/host-tasks/${id}/execute/`)
export const rerunHostTask = (id) => request.post(`/host-tasks/${id}/rerun/`)
export const cancelHostTask = (id) => request.post(`/host-tasks/${id}/cancel/`)
export const batchCancelHostTasks = (data) => request.post('/host-tasks/batch_cancel/', data)
export const getHostTaskStats = () => request.get('/host-tasks/stats/')
export const getHostTaskTargets = (params) => request.get('/host-tasks/host_options/', { params })
export const getTaskResourceOptions = (params) => request.get('/host-tasks/resource_options/', { params })
export const getHostTaskTemplates = (params) => request.get('/host-task-templates/', { params })
export const createHostTaskTemplate = (data) => request.post('/host-task-templates/', data)
export const updateHostTaskTemplate = (id, data) => request.put(`/host-task-templates/${id}/`, data)
export const deleteHostTaskTemplate = (id) => request.delete(`/host-task-templates/${id}/`)
export const getHostTaskSchedules = (params) => request.get('/host-task-schedules/', { params })
export const getHostTaskSchedule = (id) => request.get(`/host-task-schedules/${id}/`)
export const createHostTaskSchedule = (data) => request.post('/host-task-schedules/', data)
export const updateHostTaskSchedule = (id, data) => request.put(`/host-task-schedules/${id}/`, data)
export const deleteHostTaskSchedule = (id) => request.delete(`/host-task-schedules/${id}/`)
export const getHostTaskScheduleStats = () => request.get('/host-task-schedules/stats/')
export const previewHostTaskSchedule = (data) => request.get('/host-task-schedules/preview_next_runs/', {
  params: {
    ...data,
    payload: JSON.stringify(data?.payload || {}),
    selection_filters: JSON.stringify(data?.selection_filters || {}),
    target_host_ids: JSON.stringify(data?.target_host_ids || []),
  },
})
export const toggleHostTaskSchedule = (id) => request.post(`/host-task-schedules/${id}/toggle_enabled/`)
export const runHostTaskScheduleNow = (id) => request.post(`/host-task-schedules/${id}/run_now/`)
export const getHostTaskScheduleExecutions = (params) => request.get('/host-task-schedule-executions/', { params })
export const getHostTaskScheduleExecution = (id) => request.get(`/host-task-schedule-executions/${id}/`)

export const getDeployments = (params) => request.get('/deployments/', { params })
export const createDeployment = (data) => request.post('/deployments/', data)
export const updateDeployment = (id, data) => request.put(`/deployments/${id}/`, data)
export const deleteDeployment = (id) => request.delete(`/deployments/${id}/`)
export const approveDeployment = (id, data = {}) => request.post(`/deployments/${id}/approve/`, data)
export const rejectDeployment = (id, data = {}) => request.post(`/deployments/${id}/reject/`, data)
export const rerunDeployment = (id, data = {}) => request.post(`/deployments/${id}/rerun/`, data)
export const rollbackDeployment = (id, data = {}) => request.post(`/deployments/${id}/rollback/`, data)
export const advanceDeploymentBatch = (id, data = {}) => request.post(`/deployments/${id}/advance_batch/`, data)
export const stopDeployment = (id) => request.post(`/deployments/${id}/stop/`)
export const startDeployment = (id) => request.post(`/deployments/${id}/start/`)
export const removeDeployment = (id) => request.post(`/deployments/${id}/remove/`)
export const getDeploymentLogs = (id, tail = 100) => request.get(`/deployments/${id}/logs/`, { params: { tail } })
export const getDeploymentStatus = (id) => request.get(`/deployments/${id}/status_detail/`)
export const getDeploymentApprovalFlows = (params) => request.get('/deployment-approval-flows/', { params })
export const createDeploymentApprovalFlow = (data) => request.post('/deployment-approval-flows/', data)
export const updateDeploymentApprovalFlow = (id, data) => request.put(`/deployment-approval-flows/${id}/`, data)
export const deleteDeploymentApprovalFlow = (id) => request.delete(`/deployment-approval-flows/${id}/`)
export const getTransactionTickets = (params) => request.get('/transaction-tickets/', { params })
export const createTransactionTicket = (data) => request.post('/transaction-tickets/', data)
export const updateTransactionTicket = (id, data) => request.patch(`/transaction-tickets/${id}/`, data)
export const deleteTransactionTicket = (id) => request.delete(`/transaction-tickets/${id}/`)
export const approveTransactionTicket = (id) => request.post(`/transaction-tickets/${id}/approve/`)
export const rejectTransactionTicket = (id) => request.post(`/transaction-tickets/${id}/reject/`)
export const startProcessTransactionTicket = (id) => request.post(`/transaction-tickets/${id}/start_process/`)
export const completeTransactionTicket = (id) => request.post(`/transaction-tickets/${id}/complete/`)

export const getAlerts = (params) => request.get('/alerts/', { params })
export const getAlert = (id) => request.get(`/alerts/${id}/`)
export const getAlertSummary = (params) => request.get('/alerts/summary/', { params })
export const getAlertGroups = (params) => request.get('/alerts/groups/', { params })
export const getAlertLogEvidence = (id, params) => request.get(`/alerts/${id}/log-evidence/`, { params })
export const getAlertAnalysis = (id) => request.get(`/alerts/${id}/analysis/`)
export const analyzeAlert = (id, data = {}) => request.post(`/alerts/${id}/analyze/`, data)
export const updateAlert = (id, data) => request.patch(`/alerts/${id}/`, data)
export const deleteAlert = (id) => request.delete(`/alerts/${id}/`)
export const acknowledgeAlert = (id, data = {}) => request.post(`/alerts/${id}/acknowledge/`, data)
export const claimAlert = (id, data = {}) => request.post(`/alerts/${id}/claim/`, data)
export const unclaimAlert = (id, data = {}) => request.post(`/alerts/${id}/unclaim/`, data)
export const muteAlert = (id, data = {}) => request.post(`/alerts/${id}/mute/`, data)
export const escalateAlert = (id, data = {}) => request.post(`/alerts/${id}/escalate/`, data)
export const resolveAlert = (id, data = {}) => request.post(`/alerts/${id}/resolve/`, data)
export const closeAlert = (id, data = {}) => request.post(`/alerts/${id}/close/`, data)
export const reopenAlert = (id, data = {}) => request.post(`/alerts/${id}/reopen/`, data)
export const notifyAlert = (id, data = {}) => request.post(`/alerts/${id}/notify/`, data)
export const getAlertRules = (params) => request.get('/alert-rules/', { params })
export const createAlertRule = (data) => request.post('/alert-rules/', data)
export const updateAlertRule = (id, data) => request.put(`/alert-rules/${id}/`, data)
export const patchAlertRule = (id, data) => request.patch(`/alert-rules/${id}/`, data)
export const deleteAlertRule = (id) => request.delete(`/alert-rules/${id}/`)
export const getAlertRuleTemplates = (params) => request.get('/alert-rule-templates/', { params })
export const instantiateAlertRule = (data) => request.post('/alert-rules/instantiate/', data)
export const triggerAlertRule = (id, data = {}) => request.post(`/alert-rules/${id}/trigger/`, data)
export const evaluateAlertRule = (id, data = {}) => request.post(`/alert-rules/${id}/evaluate/`, data)
export const getAlertRuleEngineStatus = () => request.get('/alert-rules/engine-status/')
export const previewAlertRuleNotification = (data) => request.post('/alert-rules/preview-notification/', data)
export const getAlertRecipients = (params) => request.get('/alert-recipients/', { params })
export const createAlertRecipient = (data) => request.post('/alert-recipients/', data)
export const updateAlertRecipient = (id, data) => request.put(`/alert-recipients/${id}/`, data)
export const deleteAlertRecipient = (id) => request.delete(`/alert-recipients/${id}/`)
export const getAlertRecipientGroups = (params) => request.get('/alert-recipient-groups/', { params })
export const createAlertRecipientGroup = (data) => request.post('/alert-recipient-groups/', data)
export const updateAlertRecipientGroup = (id, data) => request.put(`/alert-recipient-groups/${id}/`, data)
export const deleteAlertRecipientGroup = (id) => request.delete(`/alert-recipient-groups/${id}/`)
export const getAlertNotificationChannels = (params) => request.get('/alert-notification-channels/', { params })
export const createAlertNotificationChannel = (data) => request.post('/alert-notification-channels/', data)
export const updateAlertNotificationChannel = (id, data) => request.put(`/alert-notification-channels/${id}/`, data)
export const deleteAlertNotificationChannel = (id) => request.delete(`/alert-notification-channels/${id}/`)
export const testAlertNotificationChannel = (id) => request.post(`/alert-notification-channels/${id}/test/`)
export const getAlertNotificationPolicies = (params) => request.get('/alert-notification-policies/', { params })
export const createAlertNotificationPolicy = (data) => request.post('/alert-notification-policies/', data)
export const updateAlertNotificationPolicy = (id, data) => request.put(`/alert-notification-policies/${id}/`, data)
export const deleteAlertNotificationPolicy = (id) => request.delete(`/alert-notification-policies/${id}/`)
export const previewAlertNotificationPolicy = (data) => request.post('/alert-notification-policies/preview/', data)
export const getAgent4NotificationPolicyPreset = () => request.get('/alert-notification-policies/agent4-preset/')
export const getInspectionReportSchedules = (params) => request.get('/inspection-report-schedules/', { params })
export const createInspectionReportSchedule = (data) => request.post('/inspection-report-schedules/', data)
export const updateInspectionReportSchedule = (id, data) => request.put(`/inspection-report-schedules/${id}/`, data)
export const deleteInspectionReportSchedule = (id) => request.delete(`/inspection-report-schedules/${id}/`)
export const runInspectionReportSchedule = (id) => request.post(`/inspection-report-schedules/${id}/run-now/`)
export const getInspectionReportExecutions = (params) => request.get('/inspection-report-executions/', { params })
export const getAlertNotificationRules = getAlertNotificationPolicies
export const createAlertNotificationRule = createAlertNotificationPolicy
export const updateAlertNotificationRule = updateAlertNotificationPolicy
export const deleteAlertNotificationRule = deleteAlertNotificationPolicy
export const getAlertAggregationRules = (params) => request.get('/alert-aggregation-rules/', { params })
export const createAlertAggregationRule = (data) => request.post('/alert-aggregation-rules/', data)
export const updateAlertAggregationRule = (id, data) => request.put(`/alert-aggregation-rules/${id}/`, data)
export const deleteAlertAggregationRule = (id) => request.delete(`/alert-aggregation-rules/${id}/`)
export const getAlertInhibitionRules = (params) => request.get('/alert-inhibition-rules/', { params })
export const createAlertInhibitionRule = (data) => request.post('/alert-inhibition-rules/', data)
export const updateAlertInhibitionRule = (id, data) => request.put(`/alert-inhibition-rules/${id}/`, data)
export const deleteAlertInhibitionRule = (id) => request.delete(`/alert-inhibition-rules/${id}/`)
export const getAlertMuteRules = (params) => request.get('/alert-mute-rules/', { params })
export const createAlertMuteRule = (data) => request.post('/alert-mute-rules/', data)
export const updateAlertMuteRule = (id, data) => request.put(`/alert-mute-rules/${id}/`, data)
export const deleteAlertMuteRule = (id) => request.delete(`/alert-mute-rules/${id}/`)
export const getAlertEscalationPolicies = (params) => request.get('/alert-escalation-policies/', { params })
export const createAlertEscalationPolicy = (data) => request.post('/alert-escalation-policies/', data)
export const updateAlertEscalationPolicy = (id, data) => request.put(`/alert-escalation-policies/${id}/`, data)
export const deleteAlertEscalationPolicy = (id) => request.delete(`/alert-escalation-policies/${id}/`)
export const getAlertNotificationLogs = (params) => request.get('/alert-notification-logs/', { params })
export const getAlertActions = (params) => request.get('/alert-actions/', { params })

export const getLogs = (params) => request.get('/logs/', { params })

export const getUsers = (params) => request.get('/users/', { params })

export const getLokiLabels = (params) => request.get('/loki/labels/', { params })
export const getLokiLabelValues = (name, params) => request.get(`/loki/label/${name}/values/`, { params })
export const queryLokiLogs = (params) => request.get('/loki/query_range/', { params })
export const getLokiSeries = (params) => request.get('/loki/series/', { params })

export const getLogProviders = () => request.get('/log/providers/')
export const getLogProviderCatalog = (provider, data) => request.post(`/log/providers/${provider}/catalog/`, data)
export const queryLogs = (data) => request.post('/log/query/', data)

export const getLogDataSources = (params, config = {}) => request.get('/log/datasources/', { params, ...config })
export const createLogDataSource = (data) => request.post('/log/datasources/', data)
export const updateLogDataSource = (id, data) => request.put(`/log/datasources/${id}/`, data)
export const deleteLogDataSource = (id) => request.delete(`/log/datasources/${id}/`)
export const testLogDataSource = (id) => request.post(`/log/datasources/${id}/test_connection/`)

export const getObservabilityOverview = (params) => request.get('/observability/overview/', { params })
export const getObservabilityIntegrations = () => request.get('/observability/integrations/')
export const installIntegrationRules = (key, data = {}) => request.post(`/observability/integrations/${key}/install-rules/`, data)
export const installIntegrationDashboards = (key, data = {}) => request.post(`/observability/integrations/${key}/install-dashboards/`, data)
export const getSlaSummary = () => request.get('/observability/sla/summary/')
export const getMiddlewareOverview = (params) => request.get('/middleware/overview/', { params })
export const runMiddlewareAction = (data) => request.post('/middleware/action/', data)
export const queryMetrics = (data) => request.post('/observability/metrics/query/', data)
export const getDashboardDefinitions = (params) => request.get('/observability/dashboard-definitions/', { params })
export const createDashboardDefinition = (data) => request.post('/observability/dashboard-definitions/', data)
export const updateDashboardDefinition = (id, data) => request.put(`/observability/dashboard-definitions/${id}/`, data)
export const deleteDashboardDefinition = (id) => request.delete(`/observability/dashboard-definitions/${id}/`)
export const queryDashboardDefinition = (id, data, config = {}) => request.post(`/observability/dashboard-definitions/${id}/query/`, data, config)
export const exportDashboardDefinition = (id) => request.get(`/observability/dashboard-definitions/${id}/export/`)
export const importDashboardDefinition = (data) => request.post('/observability/dashboard-definitions/import/', data)
export const dryRunDraftAlertRule = (data) => request.post('/alert-rules/dry-run-draft/', data)
export const getAlertCardAction = (token) => request.get(`/alerts/card-actions/${token}/`)
export const confirmAlertCardAction = (token) => request.post(`/alerts/card-actions/${token}/`)
export const getMetricSeriesNames = (params) => request.get('/observability/metrics/series-names/', { params })
export const getMetricDataSources = (params, config = {}) => request.get('/observability/metric/datasources/', { params, ...config })
export const createMetricDataSource = (data) => request.post('/observability/metric/datasources/', data)
export const updateMetricDataSource = (id, data) => request.put(`/observability/metric/datasources/${id}/`, data)
export const deleteMetricDataSource = (id) => request.delete(`/observability/metric/datasources/${id}/`)
export const testMetricDataSource = (id, data = {}) => request.post(`/observability/metric/datasources/${id}/test_connection/`, data)
