PERMISSION_DEFINITIONS = [
    ('aiops.knowledge.view', '查看 AIOps 知识图谱', 'aiops', '查看工单、日志、链路、看板、告警和事件源之间的业务关联'),
    ('aiops.knowledge.manage', '管理 AIOps 知识图谱配置', 'aiops', '维护知识图谱环境与事件中心、监控看板、日志、链路、告警来源的关联'),
    ('ops.dashboard.view', '查看运维仪表盘', 'ops', '访问首页运维统计与最近动态'),
    ('ops.host.view', '查看主机', 'ops', '查看主机列表与详情'),
    ('ops.host.manage', '管理主机', 'ops', '新增、编辑、删除、测试、刷新主机'),
    ('ops.host.terminal', '使用 WebShell', 'ops', '通过浏览器进入主机终端'),
    ('ops.host.execute', '执行主机任务', 'ops', '通过任务中心批量执行主机巡检与运维命令'),
    ('ops.task.execute', '执行任务中心任务', 'ops', '通过任务中心执行主机、K8s 与自动化调度任务'),
    ('ops.task.resource.view', '查看任务资源底座', 'ops', '查看任务中心独立执行资源、环境与系统树'),
    ('ops.task.resource.manage', '管理任务资源底座', 'ops', '维护任务中心独立执行资源、环境与系统树'),
    ('ops.host.schedule.view', '查看定时任务', 'ops', '查看主机定时编排、执行记录与下次执行时间'),
    ('ops.host.schedule.manage', '管理定时任务', 'ops', '创建、编辑、启停和删除主机定时编排'),
    ('ops.host.schedule.execute', '执行定时任务', 'ops', '手动触发主机定时编排并复用 SSH/Ansible 执行链路'),
    ('ops.deployment.view', '查看应用发布', 'ops', '查看公司应用发布记录、状态与日志'),
    ('ops.deployment.manage', '管理应用发布', 'ops', '创建发布申请、重试、回滚、启停和下线应用'),
    ('ops.deployment.approve', '审批应用发布', 'ops', '审批通过或驳回应用发布申请'),
    ('ops.ticket.view', '查看事务工单', 'ops', '查看事务工单列表、详情与处理状态'),
    ('ops.ticket.manage', '管理事务工单', 'ops', '创建、编辑、删除并推进事务工单执行'),
    ('ops.ticket.approve', '审批事务工单', 'ops', '审批通过或驳回事务工单'),
    ('ops.alert.view', '查看告警', 'ops', '查看告警列表'),
    ('ops.alert.manage', '管理告警', 'ops', '确认、编辑、删除告警'),
    ('ops.alert.notify', '发送告警通知', 'ops', '手动触发告警通知、测试通知渠道'),
    ('ops.alert.config.view', '查看告警配置', 'ops', '查看告警规则、规则模板、通知渠道、接收人、聚合抑制和升级策略'),
    ('ops.alert.config.manage', '管理告警配置', 'ops', '维护告警规则、规则模板、通知渠道、接收人、聚合抑制和升级策略'),
    ('ops.log.entry.view', '查看内置日志', 'ops', '查看平台内置日志表'),
    ('ops.log.entry.manage', '管理内置日志', 'ops', '新增、编辑、删除平台内置日志表数据'),
    ('ops.log.datasource.view', '查看日志数据源', 'ops', '查看日志数据源与供应商能力'),
    ('ops.log.datasource.manage', '管理日志数据源', 'ops', '新增、编辑、删除、测试日志数据源'),
    ('ops.log.query', '查询日志', 'ops', '执行 Loki、ELK、ClickHouse 日志检索'),
    ('ops.metric.query', '查询指标', 'ops', '执行 Prometheus 兼容 PromQL 指标查询'),
    ('ops.metric.datasource.view', '查看指标数据源', 'ops', '查看 Prometheus 兼容指标数据源配置'),
    ('ops.metric.datasource.manage', '管理指标数据源', 'ops', '新增、编辑、删除、测试 Prometheus 兼容指标数据源'),
    ('ops.monitor.dashboard.view', '查看监控看板', 'ops', '查看服务器、K8S 集群和日志三类平台原生监控看板'),
    ('ops.k8s.view', '查看 K8s 集群', 'ops', '查看集群、命名空间与资源列表'),
    ('ops.k8s.manage', '管理 K8s 集群', 'ops', '维护集群连接并执行集群管理动作'),
    ('ops.k8s.exec', '执行 K8s Pod 命令', 'ops', '通过浏览器对 Pod 执行命令并进入轻量控制台'),
    ('ops.docker.view', '查看 Docker 环境', 'ops', '查看 Docker 主机、容器、镜像与日志'),
    ('ops.docker.manage', '管理 Docker 环境', 'ops', '维护 Docker 主机并执行容器操作'),
    ('cmdb.dashboard.view', '查看 CMDB 总览', 'cmdb', '查看 CMDB 仪表盘指标'),
    ('cmdb.ci.view', '查看 CMDB 资源', 'cmdb', '查看 CI 类型、配置项、关系、资源树与申请单'),
    ('cmdb.ci.manage', '管理 CMDB 资源', 'cmdb', '维护 CI 类型、配置项、关系、资源树与成本记录'),
    ('cmdb.topology.view', '查看 CMDB 拓扑', 'cmdb', '查看资源拓扑与资源地图'),
    ('cmdb.cost.view', '查看 CMDB 成本', 'cmdb', '查看成本报表与优化建议'),
    ('cmdb.request.submit', '提交资源申请', 'cmdb', '提交新的资源申请'),
    ('cmdb.request.approve', '审批资源申请', 'cmdb', '审批或交付资源申请'),
    ('sqlaudit.datasource.view', '查看 SQL 数据源', 'sqlaudit', '查看数据库数据源与库列表'),
    ('sqlaudit.datasource.manage', '管理 SQL 数据源', 'sqlaudit', '维护数据库数据源与测试连通性'),
    ('sqlaudit.order.view', '查看 SQL 工单', 'sqlaudit', '查看 SQL 工单与检查结果'),
    ('sqlaudit.order.submit', '提交 SQL 工单', 'sqlaudit', '创建 SQL 变更工单并执行检查'),
    ('sqlaudit.order.review', '审核 SQL 工单', 'sqlaudit', '审核通过或驳回 SQL 工单'),
    ('sqlaudit.order.execute', '执行 SQL 工单', 'sqlaudit', '执行已审核通过的 SQL 工单'),
    ('sqlaudit.query.view', '查看 SQL 查询记录', 'sqlaudit', '查看 SQL 查询历史'),
    ('sqlaudit.query.execute', '执行 SQL 查询', 'sqlaudit', '提交只读 SQL 查询'),
    ('eventwall.view', '查看事件墙', 'eventwall', '查看平台事件流、关联链路与审计概览'),
    ('eventwall.source.view', '查看事件源', 'eventwall', '查看平台内置与外部接入事件源、接入规范和健康状态'),
    ('eventwall.source.manage', '管理事件源', 'eventwall', '维护外部事件源配置、启停状态和接入令牌'),
    ('eventwall.environment.view', '查看事件中心环境', 'eventwall', '查看事件中心环境字典、别名和未映射环境'),
    ('eventwall.environment.manage', '管理事件中心环境', 'eventwall', '维护事件中心环境编码、显示名称、别名和启用状态'),
    ('aiops.chat.view', '查看 AIOps 机器人', 'aiops', '在页面右下角打开 AIOps 智能助手并发起对话'),
    ('aiops.chat.analyze', '使用 AIOps 关联分析', 'aiops', '基于资源、告警、日志、事件和变更做关联分析'),
    ('aiops.task.generate', '生成 AIOps 任务草稿', 'aiops', '通过机器人生成主机巡检、命令和执行草稿'),
    ('aiops.task.execute', '执行 AIOps 任务', 'aiops', '通过机器人确认并触发任务中心执行'),
    ('aiops.config.view', '查看 AIOps 配置', 'aiops', '查看模型、MCP、Skill 和机器人安全配置'),
    ('aiops.config.manage', '管理 AIOps 配置', 'aiops', '维护模型 API、MCP、Skill、Prompt 与执行策略'),
    ('aiops.mcp.view', '查看 AIOps 对外 MCP', 'aiops', '查看 xing-cloud 对外暴露的只读 MCP 工具清单和接入信息'),
    ('aiops.mcp.invoke', '调用 AIOps 对外 MCP', 'aiops', '允许外部 Agent 通过统一鉴权调用只读平台 MCP 工具'),
    ('aiops.audit.view', '查看 AIOps 审计', 'aiops', '查看机器人会话、工具调用和动作执行审计'),
    ('aiops.audit.manage', '管理 AIOps 审计', 'aiops', '删除机器人历史会话等审计管理动作'),
    ('aiops.a2a.view', '查看 AIOps A2A 任务', 'aiops', '查看外部 Agent 创建的 AIOps 编排任务与状态'),
    ('aiops.a2a.invoke', '发起 AIOps A2A 任务', 'aiops', '允许外部 Agent 创建、取消受控 AIOps 编排任务'),
    ('aiops.runbook.view', '查看 AIOps Runbook', 'aiops', '查看 AIOps 自动沉淀的排障 Runbook 草案与发布内容'),
    ('aiops.runbook.manage', '管理 AIOps Runbook', 'aiops', '创建、编辑、发布和归档 AIOps Runbook'),
    ('aiops.review.view', '查看 AIOps 复盘知识', 'aiops', '查看由会话、协同任务和 Runbook 自动沉淀的复盘知识'),
    ('aiops.review.manage', '管理 AIOps 复盘知识', 'aiops', '自动沉淀、编辑和删除 AIOps 复盘知识'),
    ('rbac.user.view', '查看用户', 'rbac', '查看用户、角色、用户组信息'),
    ('rbac.user.manage', '管理用户', 'rbac', '新增、编辑、禁用、重置用户密码'),
    ('rbac.role.view', '查看角色', 'rbac', '查看角色与权限绑定'),
    ('rbac.role.manage', '管理角色', 'rbac', '新增、编辑、删除角色'),
    ('rbac.group.view', '查看用户组', 'rbac', '查看用户组与成员关系'),
    ('rbac.group.manage', '管理用户组', 'rbac', '新增、编辑、删除用户组'),
    ('rbac.permission.view', '查看权限字典', 'rbac', '查看系统权限清单'),
    ('rbac.module.manage', '管理模块显示', 'rbac', '配置左侧菜单模块的显示与隐藏'),
    ('rbac.audit.view', '查看操作审计', 'rbac', '查看平台关键操作、执行动作和配置变更审计记录'),
    ('rbac.audit.manage', '管理操作审计', 'rbac', '按保留策略批量清理操作审计记录'),
]


BUILTIN_ROLES = [
    {
        'code': 'platform-admin',
        'name': '平台管理员',
        'description': '拥有平台全部权限。',
        'permissions': ['*'],
    },
    {
        'code': 'ops-admin',
        'name': '运维管理员',
        'description': '负责主机、部署、容器、日志与 CMDB 维护。',
        'permissions': [
            'aiops.knowledge.view', 'aiops.knowledge.manage',
            'ops.dashboard.view', 'ops.host.view', 'ops.host.manage', 'ops.host.terminal', 'ops.host.execute', 'ops.task.execute', 'ops.task.resource.view', 'ops.task.resource.manage',
            'ops.host.schedule.view', 'ops.host.schedule.manage', 'ops.host.schedule.execute',
            'ops.deployment.view', 'ops.deployment.manage', 'ops.deployment.approve',
            'ops.ticket.view', 'ops.ticket.manage', 'ops.ticket.approve',
            'ops.alert.view', 'ops.alert.manage', 'ops.alert.notify', 'ops.alert.config.view', 'ops.alert.config.manage',
            'ops.log.entry.view', 'ops.log.datasource.view', 'ops.log.datasource.manage', 'ops.log.query',
            'ops.metric.query', 'ops.metric.datasource.view', 'ops.metric.datasource.manage',
            'ops.monitor.dashboard.view',
            'ops.k8s.view', 'ops.k8s.manage', 'ops.k8s.exec', 'ops.docker.view', 'ops.docker.manage',
            'eventwall.view', 'eventwall.source.view', 'eventwall.source.manage', 'eventwall.environment.view', 'eventwall.environment.manage',
            'rbac.audit.view',
            'aiops.chat.view', 'aiops.chat.analyze', 'aiops.task.generate', 'aiops.task.execute', 'aiops.config.view', 'aiops.audit.view', 'aiops.audit.manage',
            'aiops.mcp.view', 'aiops.mcp.invoke', 'aiops.a2a.view', 'aiops.a2a.invoke',
            'aiops.runbook.view', 'aiops.runbook.manage', 'aiops.review.view', 'aiops.review.manage',
            'cmdb.dashboard.view', 'cmdb.ci.view',
            'cmdb.ci.manage', 'cmdb.topology.view', 'cmdb.cost.view', 'cmdb.request.submit',
            'cmdb.request.approve',
        ],
    },
    {
        'code': 'developer',
        'name': '研发工程师',
        'description': '可查看环境信息、日志并提交 SQL 与资源申请。',
        'permissions': [
            'aiops.knowledge.view',
            'ops.dashboard.view', 'ops.host.view', 'ops.task.resource.view', 'ops.host.schedule.view', 'ops.deployment.view', 'ops.ticket.view', 'ops.alert.view', 'ops.alert.config.view',
            'ops.monitor.dashboard.view',
            'eventwall.view', 'eventwall.source.view', 'eventwall.environment.view',
            'aiops.chat.view', 'aiops.chat.analyze', 'aiops.task.generate', 'aiops.runbook.view', 'aiops.review.view',
            'cmdb.dashboard.view', 'cmdb.ci.view',
            'cmdb.topology.view', 'cmdb.cost.view', 'cmdb.request.submit', 'sqlaudit.datasource.view', 'sqlaudit.order.view',
            'sqlaudit.order.submit', 'sqlaudit.query.view', 'sqlaudit.query.execute',
        ],
    },
    {
        'code': 'security-auditor',
        'name': '审计员',
        'description': '查看日志、安全告警并审核 SQL 工单。',
        'permissions': [
            'aiops.knowledge.view',
            'eventwall.view', 'eventwall.source.view', 'eventwall.environment.view', 'rbac.audit.view', 'aiops.chat.view', 'aiops.chat.analyze', 'aiops.runbook.view', 'aiops.review.view',
            'ops.monitor.dashboard.view',
            'cmdb.dashboard.view', 'cmdb.topology.view', 'cmdb.cost.view', 'sqlaudit.datasource.view',
            'sqlaudit.order.view', 'sqlaudit.order.review', 'sqlaudit.query.view',
        ],
    },
    {
        'code': 'read-only',
        'name': '只读访客',
        'description': '只能浏览各模块的只读信息。',
        'permissions': [
            'ops.dashboard.view', 'ops.host.view', 'ops.task.resource.view', 'ops.host.schedule.view', 'ops.deployment.view', 'ops.ticket.view', 'ops.alert.view', 'ops.alert.config.view',
            'ops.monitor.dashboard.view',
            'cmdb.dashboard.view', 'cmdb.ci.view', 'cmdb.topology.view',
            'cmdb.cost.view',
            'sqlaudit.datasource.view', 'sqlaudit.order.view', 'sqlaudit.query.view',
            'eventwall.view', 'eventwall.source.view', 'eventwall.environment.view', 'aiops.chat.view', 'aiops.knowledge.view', 'aiops.config.view', 'aiops.mcp.view', 'aiops.runbook.view', 'aiops.review.view',
            'rbac.user.view', 'rbac.role.view', 'rbac.group.view', 'rbac.permission.view', 'rbac.audit.view',
        ],
    },
]
