# Generated by Django 5.2.16 on 2026-07-29 08:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ops', '0101_alter_logdatasource_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='资源 ID')),
                ('name', models.CharField(max_length=255, verbose_name='资源名称')),
                ('display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='显示名称')),
                ('environment', models.CharField(choices=[('prod', '生产'), ('test', '测试'), ('dev', '开发'), ('unknown', '未指定')], default='unknown', max_length=16, verbose_name='环境')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('active', '使用中'), ('warning', '异常'), ('missing', '疑似失联'), ('offline', '已失联'), ('retired', '已下线')], default='active', max_length=16, verbose_name='状态')),
                ('product', models.CharField(blank=True, default='', max_length=128, verbose_name='所属产品')),
                ('business_system', models.CharField(blank=True, default='', max_length=128, verbose_name='业务系统')),
                ('primary_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='主要 IP')),
                ('criticality', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '核心')], default='medium', max_length=16, verbose_name='重要级别')),
                ('source', models.CharField(default='manual', max_length=32, verbose_name='创建来源')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='扩展属性')),
                ('manual_fields', models.JSONField(blank=True, default=list, verbose_name='人工锁定字段')),
                ('consecutive_misses', models.PositiveIntegerField(default=0, verbose_name='连续未发现次数')),
                ('first_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='首次发现时间')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='最后发现时间')),
                ('created_by', models.CharField(blank=True, default='system', max_length=64, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, default='system', max_length=64, verbose_name='更新人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['resource_type__category', 'resource_type__name', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='类型编码')),
                ('name', models.CharField(max_length=64, verbose_name='类型名称')),
                ('category', models.CharField(choices=[('organization', '组织与业务'), ('compute', '计算资源'), ('platform', '平台组件')], max_length=32, verbose_name='分类')),
                ('icon', models.CharField(blank=True, default='Box', max_length=64, verbose_name='图标')),
                ('attribute_schema', models.JSONField(blank=True, default=dict, verbose_name='扩展字段规范')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='内置类型')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DiscoverySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='发现源名称')),
                ('source_type', models.CharField(choices=[('k8s', 'Kubernetes API'), ('zabbix', 'Zabbix'), ('prometheus', 'Prometheus'), ('ssh', 'SSH'), ('manual', '手工登记')], max_length=32, verbose_name='发现源类型')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='发现配置')),
                ('sync_interval_minutes', models.PositiveIntegerField(default=10, verbose_name='同步间隔分钟')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('status', models.CharField(choices=[('pending', '待发现'), ('healthy', '正常'), ('degraded', '部分成功'), ('failed', '失败')], default='pending', max_length=16, verbose_name='状态')),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='下次执行时间')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='最近执行时间')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='最近成功时间')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='最近错误')),
                ('created_by', models.CharField(blank=True, default='system', max_length=64, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('k8s_cluster', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_discovery_source', to='ops.k8scluster', verbose_name='K8S 集群连接')),
            ],
            options={
                'ordering': ['source_type', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('connecting', '连接中'), ('collecting', '采集中'), ('reconciling', '对账中'), ('completed', '完成'), ('partial', '部分完成'), ('failed', '失败')], default='pending', max_length=16, verbose_name='状态')),
                ('trigger', models.CharField(default='manual', max_length=16, verbose_name='触发方式')),
                ('discovered_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('unchanged_count', models.PositiveIntegerField(default=0)),
                ('missing_count', models.PositiveIntegerField(default=0)),
                ('conflict_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='resource_center.discoverysource')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResourceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('field', models.CharField(blank=True, default='', max_length=64)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('actor', models.CharField(default='system', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discovery_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource_center.discoveryrun')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='resource_center.resource')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResourceContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ops_owner', '运维负责人'), ('project_owner', '项目负责人'), ('product_owner', '产品负责人'), ('oncall', '值班人员')], max_length=32, verbose_name='职责')),
                ('contact_name', models.CharField(blank=True, default='', max_length=64, verbose_name='联系人')),
                ('inherit_to_children', models.BooleanField(default=True, verbose_name='向下继承')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主要负责人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ops.alertrecipient')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='resource_center.resource')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32, verbose_name='标识类型')),
                ('value', models.CharField(max_length=255, verbose_name='标识值')),
                ('scope', models.CharField(default='global', max_length=128, verbose_name='标识作用域')),
                ('source', models.CharField(blank=True, default='manual', max_length=32, verbose_name='标识来源')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主要标识')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='resource_center.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('belongs_to', '属于'), ('contains', '包含'), ('runs_on', '运行于'), ('deployed_on', '部署于'), ('depends_on', '依赖'), ('monitored_by', '监控于')], max_length=32, verbose_name='关系类型')),
                ('origin', models.CharField(default='manual', max_length=32, verbose_name='关系来源')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='关系属性')),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='resource_center.resource')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='resource_center.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceSourceBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_type', models.CharField(max_length=64)),
                ('external_id', models.CharField(max_length=255)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_bindings', to='resource_center.resource')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='resource_center.discoverysource')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='resource_center.resourcetype'),
        ),
        migrations.CreateModel(
            name='RuntimeResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=64)),
                ('uid', models.CharField(max_length=255)),
                ('namespace', models.CharField(blank=True, default='', max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('owner_kind', models.CharField(blank=True, default='', max_length=64)),
                ('owner_name', models.CharField(blank=True, default='', max_length=255)),
                ('node_name', models.CharField(blank=True, default='', max_length=255)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('cluster_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runtime_resources', to='resource_center.resource')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runtime_resources', to='resource_center.discoverysource')),
            ],
        ),
        migrations.AddConstraint(
            model_name='discoverysource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_type', 'k8s'), _negated=True), ('k8s_cluster__isnull', False), _connector='OR'), name='rc_k8s_source_has_cluster'),
        ),
        migrations.AddConstraint(
            model_name='resourcecontact',
            constraint=models.UniqueConstraint(fields=('resource', 'role', 'user', 'recipient'), name='rc_contact_unique'),
        ),
        migrations.AddIndex(
            model_name='resourceidentifier',
            index=models.Index(fields=['kind', 'value'], name='rc_identifier_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='resourceidentifier',
            constraint=models.UniqueConstraint(fields=('kind', 'scope', 'value'), name='rc_identifier_unique'),
        ),
        migrations.AddConstraint(
            model_name='resourcerelation',
            constraint=models.UniqueConstraint(fields=('source', 'target', 'relation_type'), name='rc_relation_unique'),
        ),
        migrations.AddConstraint(
            model_name='resourcerelation',
            constraint=models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='rc_relation_no_self'),
        ),
        migrations.AddConstraint(
            model_name='resourcesourcebinding',
            constraint=models.UniqueConstraint(fields=('source', 'external_type', 'external_id'), name='rc_binding_unique'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['resource_type', 'status'], name='rc_res_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['primary_ip'], name='rc_res_primary_ip_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['product', 'environment'], name='rc_res_product_env_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['last_seen_at'], name='rc_res_last_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='runtimeresource',
            index=models.Index(fields=['cluster_resource', 'kind', 'namespace'], name='rc_runtime_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='runtimeresource',
            constraint=models.UniqueConstraint(fields=('source', 'kind', 'uid'), name='rc_runtime_unique'),
        ),
    ]
