# Generated by Django 5.2.16 on 2026-07-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0027_alter_aiopsknowledgeenvironment_k8s_cluster_and_more'),
        ('resource_center', '0002_seed_resource_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='business_contexts',
            field=models.ManyToManyField(blank=True, related_name='resources', to='aiops.aiopsknowledgeenvironment', verbose_name='业务上下文'),
        ),
    ]
