# Generated by Django 5.2.16 on 2026-08-03 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0105_k8scluster_tls_skip_verify'),
        ('resource_center', '0003_resource_business_contexts'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='discoverysource',
            name='rc_k8s_source_has_cluster',
        ),
        migrations.AlterField(
            model_name='discoverysource',
            name='k8s_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_discovery_source', to='ops.k8scluster', verbose_name='K8S 集群连接'),
        ),
    ]
