apiVersion: v1
kind: Secret
metadata:
  name: xing-cloud-secret
  namespace: xing-cloud
type: Opaque
stringData:
  MYSQL_USER: xinghai
  MYSQL_PASSWORD: xinghaik8s
  MYSQL_ROOT_PASSWORD: xinghaik8s
  SECRET_KEY: xinghai-xing-cloud-production-secret-key
