apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xing-cloud-ingress
  namespace: xing-cloud
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
spec:
  ingressClassName: nginx
  rules:
    - host: xingcloud.vip.cpolar.cn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: xing-cloud-app
                port:
                  number: 8000
