# Generated by Django 6.0 on 2026-03-27 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('aliyun', '阿里云'), ('tencent', '腾讯云'), ('huawei', '华为云'), ('baidu', '百度智能云'), ('aws', 'AWS')], max_length=32, verbose_name='云厂商')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='账号名称')),
                ('account_id', models.CharField(blank=True, default='', max_length=128, verbose_name='账号 ID')),
                ('account_name', models.CharField(blank=True, default='', max_length=128, verbose_name='账号别名')),
                ('auth_mode', models.CharField(choices=[('aksk', 'AK/SK'), ('sts', 'STS / AssumeRole'), ('secret', '密钥对'), ('demo', 'Demo')], default='aksk', max_length=16, verbose_name='认证方式')),
                ('access_key_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Access Key ID')),
                ('access_key_secret', models.CharField(blank=True, default='', max_length=255, verbose_name='Access Key Secret')),
                ('project_id', models.CharField(blank=True, default='', max_length=128, verbose_name='项目 / 租户')),
                ('role_arn', models.CharField(blank=True, default='', max_length=255, verbose_name='角色 ARN')),
                ('external_id', models.CharField(blank=True, default='', max_length=255, verbose_name='External ID')),
                ('default_region', models.CharField(blank=True, default='', max_length=64, verbose_name='默认区域')),
                ('owner', models.CharField(blank=True, default='', max_length=64, verbose_name='负责人')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('tags', models.JSONField(blank=True, default=dict, verbose_name='标签')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('demo_mode', models.BooleanField(default=False, verbose_name='Demo 模式')),
                ('last_test_status', models.CharField(choices=[('unknown', '未检测'), ('healthy', '健康'), ('warning', '告警'), ('error', '异常')], default='unknown', max_length=16, verbose_name='最近检测状态')),
                ('last_test_message', models.CharField(blank=True, default='', max_length=255, verbose_name='最近检测信息')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最近同步时间')),
                ('created_by', models.CharField(blank=True, default='', max_length=64, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, default='', max_length=64, verbose_name='更新人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '云账号',
                'verbose_name_plural': '云账号',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CloudEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='环境名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='环境编码')),
                ('business_line', models.CharField(blank=True, default='', max_length=64, verbose_name='业务线')),
                ('environment_type', models.CharField(choices=[('prod', '生产'), ('test', '测试'), ('dev', '开发'), ('shared', '共享')], default='prod', max_length=16, verbose_name='环境类型')),
                ('region', models.CharField(max_length=64, verbose_name='区域')),
                ('zone', models.CharField(blank=True, default='', max_length=64, verbose_name='可用区')),
                ('vpc_name', models.CharField(blank=True, default='', max_length=128, verbose_name='VPC')),
                ('network_cidr', models.CharField(blank=True, default='', max_length=64, verbose_name='网段')),
                ('owner', models.CharField(blank=True, default='', max_length=64, verbose_name='环境负责人')),
                ('status', models.CharField(choices=[('active', '运行中'), ('warning', '待治理'), ('offline', '已下线')], default='active', max_length=16, verbose_name='环境状态')),
                ('sync_status', models.CharField(choices=[('never', '未同步'), ('running', '同步中'), ('success', '成功'), ('failed', '失败')], default='never', max_length=16, verbose_name='同步状态')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('tags', models.JSONField(blank=True, default=dict, verbose_name='标签')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='汇总')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最近同步时间')),
                ('last_cmdb_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最近同步到 CMDB 时间')),
                ('created_by', models.CharField(blank=True, default='', max_length=64, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, default='', max_length=64, verbose_name='更新人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='multicloud.cloudcredential', verbose_name='云账号')),
            ],
            options={
                'verbose_name': '云环境',
                'verbose_name_plural': '云环境',
                'ordering': ['credential__provider', 'environment_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CloudAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('aliyun', '阿里云'), ('tencent', '腾讯云'), ('huawei', '华为云'), ('baidu', '百度智能云'), ('aws', 'AWS')], max_length=32, verbose_name='云厂商')),
                ('resource_type', models.CharField(choices=[('ecs', '云主机'), ('rds', '数据库'), ('slb', '负载均衡'), ('k8s', 'Kubernetes'), ('redis', 'Redis'), ('oss', '对象存储'), ('nat', 'NAT 网关'), ('eip', '弹性 IP'), ('security_group', '安全组')], max_length=32, verbose_name='资源类型')),
                ('resource_id', models.CharField(max_length=128, verbose_name='资源 ID')),
                ('name', models.CharField(max_length=128, verbose_name='资源名称')),
                ('region', models.CharField(blank=True, default='', max_length=64, verbose_name='区域')),
                ('zone', models.CharField(blank=True, default='', max_length=64, verbose_name='可用区')),
                ('status', models.CharField(choices=[('running', '运行中'), ('stopped', '已停止'), ('degraded', '性能退化'), ('error', '异常')], default='running', max_length=16, verbose_name='资源状态')),
                ('charge_type', models.CharField(blank=True, default='', max_length=32, verbose_name='计费方式')),
                ('private_ip', models.CharField(blank=True, default='', max_length=128, verbose_name='私网 IP')),
                ('public_ip', models.CharField(blank=True, default='', max_length=128, verbose_name='公网 IP')),
                ('vpc_name', models.CharField(blank=True, default='', max_length=128, verbose_name='VPC')),
                ('spec', models.CharField(blank=True, default='', max_length=128, verbose_name='规格')),
                ('cpu', models.PositiveIntegerField(default=0, verbose_name='CPU')),
                ('memory_gb', models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='内存(GB)')),
                ('disk_gb', models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='磁盘(GB)')),
                ('monthly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='月成本')),
                ('cost_currency', models.CharField(default='CNY', max_length=8, verbose_name='币种')),
                ('risk_level', models.CharField(choices=[('normal', '正常'), ('warning', '风险'), ('critical', '高危')], default='normal', max_length=16, verbose_name='风险等级')),
                ('sync_state', models.CharField(choices=[('synced', '已同步'), ('drift', '配置漂移'), ('idle', '低利用率')], default='synced', max_length=16, verbose_name='同步态')),
                ('tags', models.JSONField(blank=True, default=dict, verbose_name='标签')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='multicloud.cloudenvironment', verbose_name='环境')),
            ],
            options={
                'verbose_name': '云资源',
                'verbose_name_plural': '云资源',
                'ordering': ['provider', 'resource_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CloudSyncTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('full', '全量同步'), ('warehouse', '资源同步'), ('cost', '成本同步'), ('security', '安全巡检'), ('cmdb', '同步 CMDB')], default='full', max_length=16, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=16, verbose_name='任务状态')),
                ('operator', models.CharField(blank=True, default='', max_length=64, verbose_name='执行人')),
                ('summary', models.CharField(blank=True, default='', max_length=255, verbose_name='任务摘要')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='任务结果')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_tasks', to='multicloud.cloudcredential', verbose_name='云账号')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_tasks', to='multicloud.cloudenvironment', verbose_name='环境')),
            ],
            options={
                'verbose_name': '同步任务',
                'verbose_name_plural': '同步任务',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cloudenvironment',
            constraint=models.UniqueConstraint(fields=('credential', 'name'), name='multicloud_env_credential_name_unique'),
        ),
        migrations.AddIndex(
            model_name='cloudasset',
            index=models.Index(fields=['provider', 'resource_type', 'status'], name='multicloud__provide_353e81_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudasset',
            index=models.Index(fields=['environment', 'risk_level', 'sync_state'], name='multicloud__environ_190112_idx'),
        ),
        migrations.AddConstraint(
            model_name='cloudasset',
            constraint=models.UniqueConstraint(fields=('environment', 'resource_type', 'resource_id'), name='multicloud_asset_env_type_resid_unique'),
        ),
    ]
