# Generated by Django 6.0 on 2026-04-05 13:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIOpsMCPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('server_type', models.CharField(choices=[('http', 'HTTP'), ('stdio', 'STDIO'), ('demo', 'Demo')], default='http', max_length=16, verbose_name='类型')),
                ('endpoint_or_command', models.CharField(blank=True, default='', max_length=255, verbose_name='地址或命令')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('auth_config', models.JSONField(blank=True, default=dict, verbose_name='鉴权配置')),
                ('tool_whitelist', models.JSONField(blank=True, default=list, verbose_name='工具白名单')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AIOps MCP 服务',
                'verbose_name_plural': 'AIOps MCP 服务',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIOpsModelProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='提供商名称')),
                ('provider_type', models.CharField(choices=[('openai_compatible', 'OpenAI Compatible')], default='openai_compatible', max_length=32, verbose_name='提供商类型')),
                ('base_url', models.CharField(blank=True, default='', max_length=255, verbose_name='Base URL')),
                ('api_key_encrypted', models.TextField(blank=True, default='', verbose_name='API Key 密文')),
                ('default_model', models.CharField(blank=True, default='', max_length=128, verbose_name='默认模型')),
                ('backup_model', models.CharField(blank=True, default='', max_length=128, verbose_name='备用模型')),
                ('temperature', models.FloatField(default=0.2, verbose_name='温度')),
                ('max_tokens', models.PositiveIntegerField(default=1200, verbose_name='最大 Tokens')),
                ('timeout_seconds', models.PositiveIntegerField(default=30, verbose_name='超时(秒)')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('last_test_status', models.CharField(choices=[('unknown', '未知'), ('success', '成功'), ('failed', '失败')], default='unknown', max_length=16, verbose_name='最近测试状态')),
                ('last_test_message', models.CharField(blank=True, default='', max_length=255, verbose_name='最近测试信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AIOps 模型提供商',
                'verbose_name_plural': 'AIOps 模型提供商',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIOpsSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='标识')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('source_type', models.CharField(choices=[('inline', '内置内容'), ('local', '本地文件')], default='inline', max_length=16, verbose_name='来源类型')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('allowed_role_codes', models.JSONField(blank=True, default=list, verbose_name='允许角色')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AIOps Skill',
                'verbose_name_plural': 'AIOps Skill',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIOpsChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='新会话', max_length=128, verbose_name='标题')),
                ('status', models.CharField(choices=[('active', '进行中'), ('archived', '已归档')], default='active', max_length=16, verbose_name='状态')),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后消息时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aiops_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AIOps 会话',
                'verbose_name_plural': 'AIOps 会话',
                'ordering': ['-last_message_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AIOpsChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', '系统'), ('user', '用户'), ('assistant', '助手')], max_length=16, verbose_name='角色')),
                ('message_type', models.CharField(choices=[('text', '文本'), ('analysis', '分析'), ('action', '动作'), ('error', '错误')], default='text', max_length=16, verbose_name='消息类型')),
                ('content', models.TextField(verbose_name='内容')),
                ('citations', models.JSONField(blank=True, default=list, verbose_name='引用')),
                ('tool_calls', models.JSONField(blank=True, default=list, verbose_name='工具调用')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='aiops.aiopschatsession', verbose_name='会话')),
            ],
            options={
                'verbose_name': 'AIOps 消息',
                'verbose_name_plural': 'AIOps 消息',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AIOpsAgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=64, unique=True, verbose_name='配置名称')),
                ('system_prompt', models.TextField(blank=True, default='', verbose_name='系统提示词')),
                ('welcome_message', models.CharField(blank=True, default='你好，我可以帮你结合平台上下文查询资源、分析告警、成本分析、生成待执行任务等。', max_length=255, verbose_name='欢迎语')),
                ('suggested_questions', models.JSONField(blank=True, default=list, verbose_name='建议问题')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用机器人')),
                ('allow_action_execution', models.BooleanField(default=True, verbose_name='允许执行动作')),
                ('require_confirmation', models.BooleanField(default=True, verbose_name='执行前确认')),
                ('show_evidence', models.BooleanField(default=True, verbose_name='展示证据来源')),
                ('allow_analysis', models.BooleanField(default=True, verbose_name='允许关联分析')),
                ('max_history_messages', models.PositiveIntegerField(default=12, verbose_name='最大历史消息数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('default_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_configs', to='aiops.aiopsmodelprovider', verbose_name='默认模型提供商')),
            ],
            options={
                'verbose_name': 'AIOps 机器人配置',
                'verbose_name_plural': 'AIOps 机器人配置',
            },
        ),
        migrations.CreateModel(
            name='AIOpsPendingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('execute_host_task', '执行主机任务')], max_length=32, verbose_name='动作类型')),
                ('title', models.CharField(default='', max_length=128, verbose_name='动作标题')),
                ('risk_level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '极高')], default='low', max_length=16, verbose_name='风险等级')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('canceled', '已取消'), ('executed', '已执行'), ('failed', '执行失败')], default='pending', max_length=16, verbose_name='状态')),
                ('action_payload', models.JSONField(blank=True, default=dict, verbose_name='动作参数')),
                ('result_payload', models.JSONField(blank=True, default=dict, verbose_name='执行结果')),
                ('confirmed_by', models.CharField(blank=True, default='', max_length=64, verbose_name='确认人')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_actions', to='aiops.aiopschatmessage', verbose_name='消息')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_actions', to='aiops.aiopschatsession', verbose_name='会话')),
            ],
            options={
                'verbose_name': 'AIOps 待确认动作',
                'verbose_name_plural': 'AIOps 待确认动作',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AIOpsToolInvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=64, verbose_name='工具名称')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=16, verbose_name='状态')),
                ('latency_ms', models.PositiveIntegerField(default=0, verbose_name='耗时')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='请求参数')),
                ('response_summary', models.JSONField(blank=True, default=dict, verbose_name='响应摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_invocations', to='aiops.aiopschatmessage', verbose_name='消息')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_invocations', to='aiops.aiopschatsession', verbose_name='会话')),
            ],
            options={
                'verbose_name': 'AIOps 工具调用',
                'verbose_name_plural': 'AIOps 工具调用',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
