# Generated by Django 6.0 on 2026-04-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiopsagentconfig',
            name='enabled_mcp_server_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='启用的 MCP'),
        ),
        migrations.AddField(
            model_name='aiopsagentconfig',
            name='enabled_skill_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='启用的 Skill'),
        ),
        migrations.AddField(
            model_name='aiopsmcpserver',
            name='is_builtin',
            field=models.BooleanField(default=False, verbose_name='内置'),
        ),
        migrations.AddField(
            model_name='aiopsskill',
            name='is_builtin',
            field=models.BooleanField(default=False, verbose_name='内置'),
        ),
    ]
