# Generated by Django 6.0 on 2026-06-07 09:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0014_aiopsskill_package_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiopsmodelprovider',
            name='input_token_price_per_1m',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='输入 Token 单价/百万'),
        ),
        migrations.AddField(
            model_name='aiopsmodelprovider',
            name='output_token_price_per_1m',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='输出 Token 单价/百万'),
        ),
        migrations.CreateModel(
            name='AIOpsExternalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='外部任务 ID')),
                ('source_agent', models.CharField(blank=True, default='', max_length=128, verbose_name='来源 Agent')),
                ('title', models.CharField(default='AIOps 外部任务', max_length=128, verbose_name='任务标题')),
                ('action_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Action')),
                ('agent_mode', models.CharField(blank=True, default='', max_length=32, verbose_name='Agent 模式')),
                ('status', models.CharField(choices=[('queued', '排队中'), ('running', '执行中'), ('completed', '已完成'), ('canceled', '已取消'), ('failed', '失败')], default='queued', max_length=16, verbose_name='状态')),
                ('input_payload', models.JSONField(blank=True, default=dict, verbose_name='输入参数')),
                ('plan_steps', models.JSONField(blank=True, default=list, verbose_name='计划步骤')),
                ('result_payload', models.JSONField(blank=True, default=dict, verbose_name='结果')),
                ('error_message', models.CharField(blank=True, default='', max_length=255, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aiops_external_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'AIOps A2A 外部任务',
                'verbose_name_plural': 'AIOps A2A 外部任务',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AIOpsModelInvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=64, verbose_name='用户')),
                ('purpose', models.CharField(choices=[('chat_planning', '聊天规划'), ('answer_formatting', '回答整形'), ('parameter_extraction', '参数抽取'), ('model_probe', '模型探测'), ('connection_test', '连接测试')], default='chat_planning', max_length=32, verbose_name='调用目的')),
                ('requested_model', models.CharField(blank=True, default='', max_length=128, verbose_name='请求模型')),
                ('resolved_model', models.CharField(blank=True, default='', max_length=128, verbose_name='实际模型')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], default='success', max_length=16, verbose_name='状态')),
                ('latency_ms', models.PositiveIntegerField(default=0, verbose_name='耗时')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='输入 Token')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='输出 Token')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='总 Token')),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='预估费用 USD')),
                ('request_summary', models.JSONField(blank=True, default=dict, verbose_name='请求摘要')),
                ('response_summary', models.JSONField(blank=True, default=dict, verbose_name='响应摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_invocations', to='aiops.aiopschatmessage', verbose_name='消息')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_invocations', to='aiops.aiopsmodelprovider', verbose_name='模型提供商')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_invocations', to='aiops.aiopschatsession', verbose_name='会话')),
            ],
            options={
                'verbose_name': 'AIOps 模型调用',
                'verbose_name_plural': 'AIOps 模型调用',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AIOpsRunbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='标题')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='标识')),
                ('environment', models.CharField(blank=True, default='', max_length=128, verbose_name='环境')),
                ('service', models.CharField(blank=True, default='', max_length=128, verbose_name='服务')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=16, verbose_name='状态')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('evidence', models.JSONField(blank=True, default=list, verbose_name='证据')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('created_by', models.CharField(blank=True, default='', max_length=64, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, default='', max_length=64, verbose_name='更新人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runbooks', to='aiops.aiopschatsession', verbose_name='来源会话')),
                ('source_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runbooks', to='aiops.aiopsexternaltask', verbose_name='来源任务')),
            ],
            options={
                'verbose_name': 'AIOps Runbook',
                'verbose_name_plural': 'AIOps Runbook',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
