# Generated by Django 6.0 on 2026-06-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0018_aiopsmodelprovider_provider_preset_and_max_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiopsknowledgeenvironment',
            name='metric_datasource_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='指标数据源'),
        ),
    ]
