# Generated by Django 6.0 on 2026-06-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0020_aiopsknowledgeenvironment_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiopsknowledgeenvironment',
            name='posture_environments',
        ),
    ]
