# Generated by Django 5.2.16 on 2026-07-17 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0026_sync_context_metric_environment'),
        ('ops', '0084_middlewareasset_business_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiopsknowledgeenvironment',
            name='k8s_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aiops_knowledge_environments', to='ops.k8scluster', verbose_name='K8s 集群'),
        ),
        migrations.AlterField(
            model_name='aiopsknowledgeenvironment',
            name='log_datasource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aiops_knowledge_environments', to='ops.logdatasource', verbose_name='日志数据源'),
        ),
        migrations.AlterField(
            model_name='aiopsknowledgeenvironment',
            name='metric_datasource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aiops_knowledge_environments', to='ops.metricdatasource', verbose_name='指标数据源'),
        ),
        migrations.AlterField(
            model_name='aiopsknowledgeenvironment',
            name='task_resource_environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aiops_knowledge_environments', to='ops.taskresourcegroup', verbose_name='资产环境分组'),
        ),
    ]
