# Generated by Django 6.0 on 2026-03-16 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='权限编码')),
                ('name', models.CharField(max_length=100, verbose_name='权限名称')),
                ('category', models.CharField(max_length=50, verbose_name='模块分类')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='内置权限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'ordering': ['sort_order', 'category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='角色编码')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='角色名称')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='内置角色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='rbac.permissiondefinition', verbose_name='权限')),
                ('users', models.ManyToManyField(blank=True, related_name='rbac_roles', to=settings.AUTH_USER_MODEL, verbose_name='绑定用户')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='用户组编码')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='用户组名称')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='内置用户组')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('roles', models.ManyToManyField(blank=True, related_name='user_groups', to='rbac.role', verbose_name='关联角色')),
                ('users', models.ManyToManyField(blank=True, related_name='rbac_groups', to=settings.AUTH_USER_MODEL, verbose_name='组内用户')),
            ],
            options={
                'verbose_name': '用户组',
                'verbose_name_plural': '用户组',
                'ordering': ['name'],
            },
        ),
    ]
