# Generated by Django 6.0 on 2026-03-06 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ops', '0002_host_ssh_password_host_ssh_port_host_ssh_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='服务名称')),
                ('icon', models.CharField(help_text='前端图标名或 emoji', max_length=64, verbose_name='图标标识')),
                ('category', models.CharField(choices=[('database', '数据库'), ('cache', '缓存'), ('cicd', 'CI/CD'), ('monitoring', '监控与日志'), ('security', '安全运维'), ('devenv', '开发环境'), ('middleware', '中间件')], max_length=32, verbose_name='分类')),
                ('description', models.CharField(default='', max_length=256, verbose_name='简介')),
                ('versions', models.JSONField(default=list, help_text='如 ["8.0","5.7"]', verbose_name='可用版本列表')),
                ('docker_compose_template', models.TextField(help_text='Jinja2 变量: {{version}}, {{port}}, {{password}} 等', verbose_name='docker-compose 模板')),
                ('env_schema', models.JSONField(default=list, help_text='[{"key":"port","label":"端口","default":"3306","required":true}, ...]', verbose_name='配置项定义')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '服务模板',
                'verbose_name_plural': '服务模板',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32, verbose_name='部署版本')),
                ('status', models.CharField(choices=[('pending', '待部署'), ('deploying', '部署中'), ('running', '运行中'), ('stopped', '已停止'), ('failed', '部署失败'), ('removing', '卸载中')], default='pending', max_length=16, verbose_name='状态')),
                ('env_config', models.JSONField(default=dict, help_text='用户填写的参数键值对', verbose_name='部署配置')),
                ('deploy_log', models.TextField(blank=True, default='', verbose_name='部署日志')),
                ('deployer', models.CharField(default='admin', max_length=64, verbose_name='部署人')),
                ('deploy_dir', models.CharField(blank=True, default='', max_length=256, verbose_name='部署目录')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.host', verbose_name='目标主机')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.servicetemplate', verbose_name='服务模板')),
            ],
            options={
                'verbose_name': '服务部署',
                'verbose_name_plural': '服务部署',
                'ordering': ['-created_at'],
                'unique_together': {('template', 'host')},
            },
        ),
    ]
