# Generated by Django 6.0 on 2026-03-23 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('ops', '0013_k8sconfigrevision'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicedeployment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='servicedeployment',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ops.k8scluster', verbose_name='目标集群'),
        ),
        migrations.AddField(
            model_name='servicedeployment',
            name='deploy_mode',
            field=models.CharField(choices=[('docker_compose', 'Docker Compose 单机'), ('k8s', 'Kubernetes')], default='docker_compose', max_length=32, verbose_name='部署模式'),
        ),
        migrations.AddField(
            model_name='servicedeployment',
            name='namespace',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='命名空间'),
        ),
        migrations.AddField(
            model_name='servicedeployment',
            name='release_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='发布名称'),
        ),
        migrations.AddField(
            model_name='servicedeployment',
            name='replicas',
            field=models.PositiveIntegerField(default=1, verbose_name='副本数'),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='k8s_manifest_template',
            field=models.TextField(blank=True, default='', help_text='Jinja2 变量: {{version}}, {{namespace}}, {{release_name}}, {{replicas}} 等', verbose_name='K8s YAML 模板'),
        ),
        migrations.AlterField(
            model_name='servicedeployment',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ops.host', verbose_name='目标主机'),
        ),
        migrations.AlterField(
            model_name='servicedeployment',
            name='status',
            field=models.CharField(choices=[('pending', '待部署'), ('deploying', '部署中'), ('running', '已部署'), ('stopped', '已停止'), ('failed', '部署失败'), ('removing', '卸载中')], default='pending', max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='docker_compose_template',
            field=models.TextField(blank=True, default='', help_text='Jinja2 变量: {{version}}, {{port}}, {{password}} 等', verbose_name='docker-compose 模板'),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='versions',
            field=models.JSONField(default=list, help_text='如 ["8.0", "5.7"]', verbose_name='可用版本列表'),
        ),
        migrations.AddConstraint(
            model_name='servicedeployment',
            constraint=models.UniqueConstraint(condition=models.Q(('deploy_mode', 'docker_compose')), fields=('template', 'host'), name='uniq_marketplace_template_host_compose'),
        ),
        migrations.AddConstraint(
            model_name='servicedeployment',
            constraint=models.UniqueConstraint(condition=models.Q(('deploy_mode', 'k8s')), fields=('template', 'cluster', 'namespace'), name='uniq_marketplace_template_cluster_ns_k8s'),
        ),
    ]
