# Generated by Django 6.0 on 2026-03-18 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_cirelation_cmdb_cirelation_unique_relation'),
        ('iac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terraformstack',
            name='last_cmdb_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近同步 CMDB 时间'),
        ),
        migrations.AddField(
            model_name='terraformstack',
            name='last_executed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近执行时间'),
        ),
        migrations.AddField(
            model_name='terraformstack',
            name='last_execution_action',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='最近执行动作'),
        ),
        migrations.AddField(
            model_name='terraformstack',
            name='last_execution_status',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='最近执行状态'),
        ),
        migrations.AddField(
            model_name='terraformstack',
            name='workspace_dir',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='执行工作目录'),
        ),
        migrations.CreateModel(
            name='TerraformExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('init', '初始化'), ('plan', '计划'), ('apply', '执行'), ('destroy', '销毁')], max_length=16, verbose_name='执行动作')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=16, verbose_name='执行状态')),
                ('command', models.CharField(blank=True, default='', max_length=255, verbose_name='执行命令')),
                ('return_code', models.IntegerField(blank=True, null=True, verbose_name='返回码')),
                ('stdout', models.TextField(blank=True, default='', verbose_name='标准输出')),
                ('stderr', models.TextField(blank=True, default='', verbose_name='标准错误')),
                ('outputs', models.JSONField(blank=True, default=dict, verbose_name='执行结果')),
                ('cmdb_summary', models.JSONField(blank=True, default=dict, verbose_name='CMDB 同步摘要')),
                ('created_by', models.CharField(default='', max_length=64, verbose_name='执行人')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='iac.terraformstack')),
            ],
            options={
                'verbose_name': 'Terraform 执行记录',
                'verbose_name_plural': 'Terraform 执行记录',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TerraformResourceBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_key', models.CharField(max_length=64, verbose_name='资源键')),
                ('resource_name', models.CharField(max_length=128, verbose_name='资源名称')),
                ('resource_kind', models.CharField(max_length=64, verbose_name='资源类型')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='绑定元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cmdb_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terraform_bindings', to='cmdb.configitem')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_bindings', to='iac.terraformstack')),
            ],
            options={
                'verbose_name': 'Terraform 资源绑定',
                'verbose_name_plural': 'Terraform 资源绑定',
                'ordering': ['resource_key'],
                'constraints': [models.UniqueConstraint(fields=('stack', 'resource_key'), name='iac_resourcebinding_stack_key_unique')],
            },
        ),
    ]
