# Generated by Django 6.0 on 2026-02-28 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('host', models.CharField(max_length=256, verbose_name='主机地址')),
                ('port', models.PositiveIntegerField(default=3306, verbose_name='端口')),
                ('user', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=512, verbose_name='密码')),
                ('charset', models.CharField(default='utf8mb4', max_length=32, verbose_name='字符集')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '数据源',
                'verbose_name_plural': '数据源',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.CharField(max_length=128, verbose_name='目标数据库')),
                ('sql_content', models.TextField(verbose_name='SQL 内容')),
                ('submitter', models.CharField(default='admin', max_length=64, verbose_name='提交人')),
                ('result_count', models.IntegerField(blank=True, null=True, verbose_name='结果行数')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='耗时(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='查询时间')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sqlaudit.datasource', verbose_name='数据源')),
            ],
            options={
                'verbose_name': '查询记录',
                'verbose_name_plural': '查询记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SqlOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='工单标题')),
                ('database', models.CharField(max_length=128, verbose_name='目标数据库')),
                ('sql_type', models.CharField(choices=[('DDL', 'DDL'), ('DML', 'DML')], default='DML', max_length=8, verbose_name='SQL 类型')),
                ('sql_content', models.TextField(verbose_name='SQL 内容')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回'), ('executing', '执行中'), ('executed', '已执行'), ('failed', '执行失败')], default='pending', max_length=16, verbose_name='状态')),
                ('submitter', models.CharField(default='admin', max_length=64, verbose_name='提交人')),
                ('reviewer', models.CharField(blank=True, default='', max_length=64, verbose_name='审核人')),
                ('review_comment', models.TextField(blank=True, default='', verbose_name='审核备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('execute_log', models.TextField(blank=True, default='', verbose_name='执行日志')),
                ('affected_rows', models.IntegerField(blank=True, null=True, verbose_name='影响行数')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='耗时(ms)')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sqlaudit.datasource', verbose_name='数据源')),
            ],
            options={
                'verbose_name': 'SQL 工单',
                'verbose_name_plural': 'SQL 工单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SqlCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('error', '错误'), ('warning', '警告'), ('info', '建议')], max_length=16, verbose_name='级别')),
                ('rule_name', models.CharField(max_length=128, verbose_name='规则名')),
                ('message', models.TextField(verbose_name='检查信息')),
                ('line_no', models.IntegerField(blank=True, null=True, verbose_name='行号')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='sqlaudit.sqlorder', verbose_name='关联工单')),
            ],
            options={
                'verbose_name': 'SQL 检查结果',
                'verbose_name_plural': 'SQL 检查结果',
            },
        ),
    ]
