from .models import AlertRule, AlertRuleTemplate


BUILTIN_ALERT_RULE_TEMPLATES = [
    {
        'code': 'redis-down',
        'name': 'Redis Down',
        'source_type': AlertRuleTemplate.SOURCE_PROMETHEUS,
        'level': 'critical',
        'query_config': {'query': 'redis_up == 0', 'value_path': 'value'},
        'condition': {'operator': '>', 'threshold': 0},
        'default_labels': {'integration': 'redis', 'service': 'redis'},
        'annotations': {'summary': 'Redis exporter reports the instance is down'},
        'interval_seconds': 60,
        'duration_seconds': 60,
        'notify_enabled': True,
        'auto_analyze': True,
        'description': 'Redis availability rule based on redis_up.',
        'sort_order': 100,
    },
    {
        'code': 'redis-high-clients',
        'name': 'Redis High Client Usage',
        'source_type': AlertRuleTemplate.SOURCE_PROMETHEUS,
        'level': 'warning',
        'query_config': {'query': 'redis_connected_clients / redis_config_maxclients * 100', 'value_path': 'value'},
        'condition': {'operator': '>', 'threshold': 85},
        'default_labels': {'integration': 'redis', 'service': 'redis'},
        'annotations': {'summary': 'Redis client usage is higher than 85%'},
        'interval_seconds': 60,
        'duration_seconds': 60,
        'notify_enabled': True,
        'auto_analyze': False,
        'description': 'Redis connected clients pressure rule.',
        'sort_order': 110,
    },
    {
        'code': 'redis-high-memory',
        'name': 'Redis High Memory Usage',
        'source_type': AlertRuleTemplate.SOURCE_PROMETHEUS,
        'level': 'warning',
        'query_config': {'query': 'redis_memory_used_bytes / redis_memory_max_bytes * 100', 'value_path': 'value'},
        'condition': {'operator': '>', 'threshold': 85},
        'default_labels': {'integration': 'redis', 'service': 'redis'},
        'annotations': {'summary': 'Redis memory usage is higher than 85%'},
        'interval_seconds': 60,
        'duration_seconds': 120,
        'notify_enabled': True,
        'auto_analyze': False,
        'description': 'Redis memory pressure rule.',
        'sort_order': 120,
    },
    {
        'code': 'redis-evicted-keys',
        'name': 'Redis Evicted Keys Increasing',
        'source_type': AlertRuleTemplate.SOURCE_PROMETHEUS,
        'level': 'warning',
        'query_config': {'query': 'increase(redis_evicted_keys_total[5m])', 'value_path': 'value'},
        'condition': {'operator': '>', 'threshold': 0},
        'default_labels': {'integration': 'redis', 'service': 'redis'},
        'annotations': {'summary': 'Redis evicted keys increased in the last 5 minutes'},
        'interval_seconds': 60,
        'duration_seconds': 0,
        'notify_enabled': True,
        'auto_analyze': False,
        'description': 'Redis eviction signal rule.',
        'sort_order': 130,
    },
    {
        'code': 'mysql-down',
        'name': 'MySQL Down',
        'source_type': AlertRuleTemplate.SOURCE_PROMETHEUS,
        'level': 'critical',
        'query_config': {'query': 'mysql_up == 0', 'value_path': 'value'},
        'condition': {'operator': '>', 'threshold': 0},
        'default_labels': {'integration': 'mysql', 'service': 'mysql'},
        'annotations': {'summary': 'MySQL exporter reports the instance is down'},
        'interval_seconds': 60,
        'duration_seconds': 60,
        'notify_enabled': True,
        'auto_analyze': True,
        'description': 'MySQL availability rule based on mysql_up.',
        'sort_order': 200,
    },
    {
        'code': 'mysql-high-connections',
        'name': 'MySQL High Connections',
        'source_type': AlertRuleTemplate.SOURCE_PROMETHEUS,
        'level': 'warning',
        'query_config': {'query': 'mysql_global_status_threads_connected / mysql_global_variables_max_connections * 100', 'value_path': 'value'},
        'condition': {'operator': '>', 'threshold': 80},
        'default_labels': {'integration': 'mysql', 'service': 'mysql'},
        'annotations': {'summary': 'MySQL connections are higher than 80%'},
        'interval_seconds': 60,
        'duration_seconds': 120,
        'notify_enabled': True,
        'auto_analyze': False,
        'description': 'MySQL connection usage rule.',
        'sort_order': 210,
    },
    {
        'code': 'mysql-high-running-threads',
        'name': 'MySQL High Running Threads',
        'source_type': AlertRuleTemplate.SOURCE_PROMETHEUS,
        'level': 'warning',
        'query_config': {'query': 'mysql_global_status_threads_running / mysql_global_variables_max_connections * 100', 'value_path': 'value'},
        'condition': {'operator': '>', 'threshold': 60},
        'default_labels': {'integration': 'mysql', 'service': 'mysql'},
        'annotations': {'summary': 'MySQL running threads are higher than 60% of max connections'},
        'interval_seconds': 60,
        'duration_seconds': 120,
        'notify_enabled': True,
        'auto_analyze': False,
        'description': 'MySQL running thread pressure rule.',
        'sort_order': 220,
    },
    {
        'code': 'mysql-slow-queries',
        'name': 'MySQL Slow Queries Increasing',
        'source_type': AlertRuleTemplate.SOURCE_PROMETHEUS,
        'level': 'warning',
        'query_config': {'query': 'increase(mysql_global_status_slow_queries[5m])', 'value_path': 'value'},
        'condition': {'operator': '>', 'threshold': 20},
        'default_labels': {'integration': 'mysql', 'service': 'mysql'},
        'annotations': {'summary': 'MySQL slow queries increased in the last 5 minutes'},
        'interval_seconds': 60,
        'duration_seconds': 0,
        'notify_enabled': True,
        'auto_analyze': False,
        'description': 'MySQL slow query growth rule.',
        'sort_order': 230,
    },
    {
        'code': 'postgresql-down',
        'name': 'PostgreSQL Down',
        'source_type': AlertRuleTemplate.SOURCE_PROMETHEUS,
        'level': 'critical',
        'query_config': {'query': 'pg_up == 0', 'value_path': 'value'},
        'condition': {'operator': '>', 'threshold': 0},
        'default_labels': {'integration': 'postgresql', 'service': 'postgresql'},
        'annotations': {'summary': 'PostgreSQL exporter reports the instance is down'},
        'interval_seconds': 60,
        'duration_seconds': 60,
        'notify_enabled': True,
        'auto_analyze': True,
        'description': 'PostgreSQL availability rule.',
        'sort_order': 300,
    },
    {
        'code': 'postgresql-high-connections',
        'name': 'PostgreSQL High Connections',
        'source_type': AlertRuleTemplate.SOURCE_PROMETHEUS,
        'level': 'warning',
        'query_config': {'query': 'sum(pg_stat_activity_count) by (instance) / max(pg_settings_max_connections) by (instance) * 100', 'value_path': 'value'},
        'condition': {'operator': '>', 'threshold': 80},
        'default_labels': {'integration': 'postgresql', 'service': 'postgresql'},
        'annotations': {'summary': 'PostgreSQL connections are higher than 80%'},
        'interval_seconds': 60,
        'duration_seconds': 120,
        'notify_enabled': True,
        'auto_analyze': False,
        'description': 'PostgreSQL connection pressure rule.',
        'sort_order': 310,
    },
    {
        'code': 'kafka-broker-down',
        'name': 'Kafka Broker Down',
        'source_type': AlertRuleTemplate.SOURCE_PROMETHEUS,
        'level': 'critical',
        'query_config': {'query': 'kafka_brokers < 1', 'value_path': 'value'},
        'condition': {'operator': '>', 'threshold': 0},
        'default_labels': {'integration': 'kafka', 'service': 'kafka'},
        'annotations': {'summary': 'Kafka broker count is below expected value'},
        'interval_seconds': 60,
        'duration_seconds': 60,
        'notify_enabled': True,
        'auto_analyze': True,
        'description': 'Kafka broker availability rule.',
        'sort_order': 400,
    },
    {
        'code': 'kafka-consumer-lag',
        'name': 'Kafka Consumer Lag High',
        'source_type': AlertRuleTemplate.SOURCE_PROMETHEUS,
        'level': 'warning',
        'query_config': {'query': 'kafka_consumergroup_lag', 'value_path': 'value'},
        'condition': {'operator': '>', 'threshold': 1000},
        'default_labels': {'integration': 'kafka', 'service': 'kafka'},
        'annotations': {'summary': 'Kafka consumer lag is high'},
        'interval_seconds': 60,
        'duration_seconds': 120,
        'notify_enabled': True,
        'auto_analyze': False,
        'description': 'Kafka consumer lag rule.',
        'sort_order': 410,
    },
    {
        'code': 'kafka-offline-partitions',
        'name': 'Kafka Offline Partitions',
        'source_type': AlertRuleTemplate.SOURCE_PROMETHEUS,
        'level': 'critical',
        'query_config': {'query': 'kafka_controller_kafkacontroller_offlinepartitionscount', 'value_path': 'value'},
        'condition': {'operator': '>', 'threshold': 0},
        'default_labels': {'integration': 'kafka', 'service': 'kafka'},
        'annotations': {'summary': 'Kafka has offline partitions'},
        'interval_seconds': 60,
        'duration_seconds': 60,
        'notify_enabled': True,
        'auto_analyze': True,
        'description': 'Kafka offline partitions rule.',
        'sort_order': 420,
    },
    {
        'code': 'k8s-node-not-ready',
        'name': 'K8S Node Not Ready',
        'source_type': AlertRuleTemplate.SOURCE_K8S,
        'level': 'critical',
        'query_config': {'query': 'sum(kube_node_status_condition{condition="Ready",status!="true"})', 'value_path': 'value'},
        'condition': {'operator': '>', 'threshold': 0},
        'default_labels': {'integration': 'kubernetes', 'service': 'kubernetes'},
        'annotations': {'summary': 'Kubernetes has nodes that are not ready'},
        'interval_seconds': 60,
        'duration_seconds': 120,
        'notify_enabled': True,
        'auto_analyze': True,
        'description': 'K8S node ready condition rule.',
        'sort_order': 500,
    },
    {
        'code': 'k8s-abnormal-pods',
        'name': 'K8S Abnormal Pods',
        'source_type': AlertRuleTemplate.SOURCE_K8S,
        'level': 'warning',
        'query_config': {'query': 'count(kube_pod_status_phase{phase=~"Pending|Failed|Unknown"} == 1)', 'value_path': 'value'},
        'condition': {'operator': '>', 'threshold': 0},
        'default_labels': {'integration': 'kubernetes', 'service': 'kubernetes'},
        'annotations': {'summary': 'Kubernetes has abnormal pods'},
        'interval_seconds': 60,
        'duration_seconds': 120,
        'notify_enabled': True,
        'auto_analyze': True,
        'description': 'K8S abnormal pod count rule.',
        'sort_order': 510,
    },
    {
        'code': 'k8s-pod-restarts',
        'name': 'K8S Pod Restarts High',
        'source_type': AlertRuleTemplate.SOURCE_K8S,
        'level': 'warning',
        'query_config': {'query': 'sum by(pod, namespace) (increase(kube_pod_container_status_restarts_total[15m]))', 'value_path': 'value'},
        'condition': {'operator': '>', 'threshold': 5},
        'default_labels': {'integration': 'kubernetes', 'service': 'kubernetes'},
        'annotations': {'summary': 'Kubernetes pod restarts increased'},
        'interval_seconds': 60,
        'duration_seconds': 0,
        'notify_enabled': True,
        'auto_analyze': True,
        'description': 'K8S pod restart rule.',
        'sort_order': 520,
    },
    {
        'code': 'k8s-events-warning',
        'name': 'K8S Events Warning Spike',
        'source_type': AlertRuleTemplate.SOURCE_CLICKHOUSE,
        'level': 'warning',
        'query_config': {'collection': 'k8s-events', 'window_minutes': 5, 'levels': ['Warning']},
        'condition': {'operator': '>', 'threshold': 10},
        'default_labels': {'integration': 'kubernetes', 'service': 'kubernetes-events'},
        'annotations': {'summary': 'Kubernetes Warning events increased in the last 5 minutes'},
        'interval_seconds': 60,
        'duration_seconds': 0,
        'notify_enabled': True,
        'auto_analyze': True,
        'description': 'ClickHouse K8S Events warning spike rule.',
        'sort_order': 530,
    },
    {
        'code': 'linux-node-down',
        'name': 'Linux Node Down',
        'source_type': AlertRuleTemplate.SOURCE_PROMETHEUS,
        'level': 'critical',
        'query_config': {'query': 'up{job=~".*node.*"} == 0', 'value_path': 'value'},
        'condition': {'operator': '>', 'threshold': 0},
        'default_labels': {'integration': 'linux', 'service': 'linux'},
        'annotations': {'summary': 'Linux node exporter target is down'},
        'interval_seconds': 60,
        'duration_seconds': 60,
        'notify_enabled': True,
        'auto_analyze': True,
        'description': 'Linux node availability rule.',
        'sort_order': 600,
    },
    {
        'code': 'linux-high-cpu',
        'name': 'Linux High CPU Usage',
        'source_type': AlertRuleTemplate.SOURCE_PROMETHEUS,
        'level': 'warning',
        'query_config': {'query': '(1 - avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) by (instance)) * 100', 'value_path': 'value'},
        'condition': {'operator': '>', 'threshold': 85},
        'default_labels': {'integration': 'linux', 'service': 'linux'},
        'annotations': {'summary': 'Linux CPU usage is higher than 85%'},
        'interval_seconds': 60,
        'duration_seconds': 180,
        'notify_enabled': True,
        'auto_analyze': False,
        'description': 'Linux CPU usage rule.',
        'sort_order': 610,
    },
    {
        'code': 'linux-high-memory',
        'name': 'Linux High Memory Usage',
        'source_type': AlertRuleTemplate.SOURCE_PROMETHEUS,
        'level': 'warning',
        'query_config': {'query': '(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100', 'value_path': 'value'},
        'condition': {'operator': '>', 'threshold': 85},
        'default_labels': {'integration': 'linux', 'service': 'linux'},
        'annotations': {'summary': 'Linux memory usage is higher than 85%'},
        'interval_seconds': 60,
        'duration_seconds': 180,
        'notify_enabled': True,
        'auto_analyze': False,
        'description': 'Linux memory usage rule.',
        'sort_order': 620,
    },
    {
        'code': 'linux-high-disk',
        'name': 'Linux High Disk Usage',
        'source_type': AlertRuleTemplate.SOURCE_PROMETHEUS,
        'level': 'warning',
        'query_config': {'query': '(1 - node_filesystem_avail_bytes{fstype!~"tmpfs|overlay"} / node_filesystem_size_bytes{fstype!~"tmpfs|overlay"}) * 100', 'value_path': 'value'},
        'condition': {'operator': '>', 'threshold': 85},
        'default_labels': {'integration': 'linux', 'service': 'linux'},
        'annotations': {'summary': 'Linux disk usage is higher than 85%'},
        'interval_seconds': 60,
        'duration_seconds': 300,
        'notify_enabled': True,
        'auto_analyze': False,
        'description': 'Linux disk usage rule.',
        'sort_order': 630,
    },
    {
        'code': 'container-error-spike',
        'name': 'Container ERROR Log Spike',
        'source_type': AlertRuleTemplate.SOURCE_CLICKHOUSE,
        'level': 'warning',
        'query_config': {'collection': 'container-logs', 'window_minutes': 5, 'level': ['ERROR', 'FATAL', 'CRITICAL']},
        'condition': {'operator': '>', 'threshold': 50},
        'default_labels': {'integration': 'clickhouse-logs', 'service': 'container-logs'},
        'annotations': {'summary': 'Container ERROR logs spiked in the last 5 minutes'},
        'interval_seconds': 60,
        'duration_seconds': 0,
        'notify_enabled': True,
        'auto_analyze': False,
        'description': 'ClickHouse container log spike rule.',
        'sort_order': 700,
    },
    {
        'code': 'ingress-5xx-spike',
        'name': 'Ingress 5XX Spike',
        'source_type': AlertRuleTemplate.SOURCE_CLICKHOUSE,
        'level': 'warning',
        'query_config': {'collection': 'ingress-access', 'window_minutes': 5, 'status_min': 500},
        'condition': {'operator': '>', 'threshold': 50},
        'default_labels': {'integration': 'ingress-access', 'service': 'ingress'},
        'annotations': {'summary': 'Ingress 5XX responses spiked in the last 5 minutes'},
        'interval_seconds': 60,
        'duration_seconds': 0,
        'notify_enabled': True,
        'auto_analyze': False,
        'description': 'Ingress 5XX spike rule.',
        'sort_order': 710,
    },
    {
        'code': 'ingress-latency-high',
        'name': 'Ingress Latency High',
        'source_type': AlertRuleTemplate.SOURCE_CLICKHOUSE,
        'level': 'warning',
        'query_config': {'collection': 'ingress-access', 'window_minutes': 5, 'metric': 'avg_latency_ms'},
        'condition': {'operator': '>', 'threshold': 1000},
        'default_labels': {'integration': 'ingress-access', 'service': 'ingress'},
        'annotations': {'summary': 'Ingress average latency is high'},
        'interval_seconds': 60,
        'duration_seconds': 0,
        'notify_enabled': True,
        'auto_analyze': False,
        'description': 'Ingress latency rule.',
        'sort_order': 720,
    },
    {
        'code': 'sla-monthly-risk',
        'name': 'Monthly SLA At Risk',
        'source_type': AlertRuleTemplate.SOURCE_SLA,
        'level': 'critical',
        'query_config': {'metric': 'month_sla'},
        'condition': {'operator': '<', 'threshold': 99.96},
        'default_labels': {'integration': 'sla-risk', 'service': 'sla'},
        'annotations': {'summary': 'Monthly SLA is below target'},
        'interval_seconds': 300,
        'duration_seconds': 0,
        'notify_enabled': True,
        'auto_analyze': True,
        'description': 'SLA risk rule based on monthly SLA target.',
        'sort_order': 800,
    },
]


def ensure_builtin_alert_rule_templates():
    templates = []
    for item in BUILTIN_ALERT_RULE_TEMPLATES:
        payload = {**item, 'is_builtin': True, 'is_enabled': True}
        template, _ = AlertRuleTemplate.objects.update_or_create(code=item['code'], defaults=payload)
        templates.append(template)
    return templates


def install_rules_from_templates(template_codes):
    ensure_builtin_alert_rule_templates()
    created = []
    skipped = []
    for template in AlertRuleTemplate.objects.filter(code__in=template_codes, is_enabled=True).order_by('sort_order', 'name'):
        if AlertRule.objects.filter(template=template).exists():
            skipped.append(template.code)
            continue
        rule = AlertRule.objects.create(
            template=template,
            name=template.name,
            source_type=template.source_type,
            level=template.level,
            query_config=template.query_config,
            condition=template.condition,
            labels=template.default_labels,
            annotations=template.annotations,
            interval_seconds=template.interval_seconds,
            duration_seconds=template.duration_seconds,
            notify_enabled=template.notify_enabled,
            auto_analyze=template.auto_analyze,
            is_enabled=True,
            description=template.description,
        )
        created.append(rule)
    return created, skipped
