from datetime import timedelta

from django.utils import timezone

from .models import Alert, LogDataSource
from .log_views import _merge_config, _run_query


KNOWN_CLICKHOUSE_COLLECTIONS = {'container-logs', 'k8s-events', 'ingress-access'}


def _dict(value):
    return value if isinstance(value, dict) else {}


def _raw_rule(alert):
    return _dict(_dict(alert.raw_payload).get('rule'))


def _rule_query_config(alert):
    return _dict(_raw_rule(alert).get('query_config'))


def _rule_condition(alert):
    return _dict(_raw_rule(alert).get('condition'))


def _window_minutes(value, default=5):
    text = str(value or '').strip().lower()
    if not text:
        return default
    try:
        if text.endswith('m'):
            return int(float(text[:-1]))
        if text.endswith('h'):
            return int(float(text[:-1]) * 60)
        return int(float(text))
    except (TypeError, ValueError):
        return default


def _collection_for_alert(alert, query_config):
    labels = _dict(alert.labels)
    candidates = [
        query_config.get('collection'),
        labels.get('collection'),
        labels.get('log_collection'),
        alert.service,
        alert.resource,
    ]
    for candidate in candidates:
        text = str(candidate or '').strip()
        if text:
            return text
    return 'container-logs'


def is_clickhouse_log_alert(alert):
    if not alert:
        return False
    labels = _dict(alert.labels)
    rule = _raw_rule(alert)
    if str(rule.get('source_type') or labels.get('alert_rule_source_type') or '').lower() == 'clickhouse':
        return True
    collection = _collection_for_alert(alert, _rule_query_config(alert))
    return collection in KNOWN_CLICKHOUSE_COLLECTIONS


def _timestamp_ms(value):
    if not value:
        value = timezone.now()
    if timezone.is_naive(value):
        value = timezone.make_aware(value, timezone.get_current_timezone())
    return int(value.timestamp() * 1000)


def _time_window(alert, query_config, condition):
    window_minutes = _window_minutes(
        query_config.get('window_minutes') or query_config.get('window') or condition.get('window_minutes') or 5,
        default=5,
    )
    end_at = alert.last_received_at or alert.starts_at or timezone.now()
    if alert.status == Alert.STATUS_RESOLVED and alert.ends_at:
        end_at = alert.ends_at
    start_at = end_at - timedelta(minutes=max(window_minutes, 1))
    return window_minutes, _timestamp_ms(start_at), _timestamp_ms(end_at)


def _first_present(*values):
    for value in values:
        if value is not None and value != '':
            return value
    return None


def _sample_text(log):
    timestamp = log.get('timestamp') or '-'
    level = str(log.get('level') or '-').upper()
    source = log.get('source') or '-'
    message = str(log.get('message') or '').replace('\n', ' ').strip()
    if len(message) > 240:
        message = f'{message[:237]}...'
    return f'{timestamp} / {level} / {source} / {message or "-"}'


def _resolve_datasource(query_config):
    datasource_id = query_config.get('log_datasource_id') or query_config.get('datasource_id')
    if datasource_id:
        return LogDataSource.objects.get(pk=datasource_id)
    return LogDataSource.objects.filter(provider='clickhouse', is_enabled=True).order_by('-is_default', 'name').first()


def build_alert_log_evidence(alert, limit=10):
    query_config = _rule_query_config(alert)
    condition = _rule_condition(alert)
    collection = _collection_for_alert(alert, query_config)
    window_minutes, start_ms, end_ms = _time_window(alert, query_config, condition)
    limit = max(1, min(int(limit or 10), 50))

    if not is_clickhouse_log_alert(alert):
        return {
            'summary': {'count': 0, 'skipped': True, 'reason': 'not_clickhouse_log_alert'},
            'sections': [{'title': 'Log evidence skipped', 'items': ['Alert is not generated by a ClickHouse log rule.']}],
            'citations': [],
            'logs': [],
        }

    datasource = _resolve_datasource(query_config)
    if not datasource:
        return {
            'summary': {'count': 0, 'skipped': True, 'reason': 'missing_clickhouse_datasource', 'collection': collection},
            'sections': [{'title': 'Log evidence unavailable', 'items': ['No enabled ClickHouse log datasource is configured.']}],
            'citations': [{'title': 'Log Center', 'path': '/logs/query'}],
            'logs': [],
        }

    payload = {
        'collection': collection,
        'query': _first_present(query_config.get('keyword'), condition.get('keyword'), '*'),
        'start_ms': start_ms,
        'end_ms': end_ms,
        'limit': limit,
    }
    levels = _first_present(query_config.get('levels'), query_config.get('level'), query_config.get('log_level'), condition.get('levels'), condition.get('level'), condition.get('log_level'))
    if levels is not None:
        payload['levels'] = levels
    for key in ['status_min', 'status_max', 'time_field', 'level_field', 'search_fields', 'message_fields']:
        value = _first_present(query_config.get(key), condition.get(key))
        if value is not None:
            payload[key] = value

    config = _merge_config('clickhouse', datasource.config)
    result = _run_query('clickhouse', config, payload)
    logs = (result.get('logs') or [])[:limit]
    items = [_sample_text(item) for item in logs] or ['No matching log samples were found in the alert window.']
    return {
        'summary': {
            'count': len(logs),
            'total': result.get('total', len(logs)),
            'collection': result.get('collection') or collection,
            'collection_name': result.get('collection_name') or collection,
            'window_minutes': window_minutes,
            'datasource': datasource.name,
            'provider': 'clickhouse',
        },
        'sections': [{'title': 'Log evidence', 'items': items}],
        'citations': [{'title': 'Log Center', 'path': '/logs/query'}],
        'logs': logs,
        'datasources': [{'id': datasource.id, 'name': datasource.name, 'provider': datasource.provider}],
        'query': payload,
    }
