# Generated by Django 6.0 on 2026-03-13 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CIType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='模型名称')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='内置图标')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=50, verbose_name='申请人')),
                ('resource_type', models.CharField(max_length=50, verbose_name='资源类型')),
                ('specs', models.JSONField(default=dict, verbose_name='规格要求')),
                ('reason', models.TextField(verbose_name='申请理由')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('provisioned', '已交付')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置项名称')),
                ('business_line', models.CharField(blank=True, max_length=50, verbose_name='业务线')),
                ('environment', models.CharField(choices=[('prod', '生产'), ('test', '测试'), ('dev', '开发')], default='prod', max_length=20, verbose_name='环境')),
                ('admin_user', models.CharField(blank=True, max_length=50, verbose_name='负责人')),
                ('status', models.CharField(choices=[('active', '使用中'), ('idle', '闲置'), ('offline', '已下线')], default='active', max_length=20, verbose_name='状态')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='扩展属性')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ci_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='cmdb.citype')),
            ],
        ),
        migrations.CreateModel(
            name='CIRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('depends_on', '依赖'), ('runs_on', '运行在'), ('connects_to', '连接')], max_length=50, verbose_name='关系类型')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='cmdb.configitem')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='cmdb.configitem')),
            ],
        ),
        migrations.CreateModel(
            name='CostRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, verbose_name='归属月份')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额(元)')),
                ('provider', models.CharField(blank=True, max_length=50, verbose_name='云厂商')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('ci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='cmdb.configitem')),
            ],
        ),
    ]
