# Generated by Django 6.0 on 2026-03-13 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citype',
            name='color',
            field=models.CharField(default='#9c27b0', max_length=20, verbose_name='主题色'),
        ),
        migrations.CreateModel(
            name='ResourceNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='节点名称')),
                ('node_type', models.CharField(choices=[('biz', '业务线'), ('env', '环境')], max_length=20, verbose_name='节点类型')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cmdb.resourcenode')),
            ],
        ),
    ]
