# Generated by Django 6.0 on 2026-03-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_citype_color_resourcenode'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cirelation',
            constraint=models.UniqueConstraint(fields=('source', 'target', 'relation_type'), name='cmdb_cirelation_unique_relation'),
        ),
    ]
