# Generated by Django 6.0 on 2026-03-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_cirelation_cmdb_cirelation_unique_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcerequest',
            name='approval_comment',
            field=models.TextField(blank=True, default='', verbose_name='审批说明'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批时间'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='approver',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='business_line',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='业务线'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='environment',
            field=models.CharField(blank=True, choices=[('prod', '生产'), ('test', '测试'), ('dev', '开发')], default='', max_length=20, verbose_name='环境'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='fulfillment_note',
            field=models.TextField(blank=True, default='', verbose_name='交付说明'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='priority',
            field=models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=16, verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='specification',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='规格说明'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='申请标题'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cirelation',
            name='relation_type',
            field=models.CharField(choices=[('depends_on', '业务依赖'), ('runs_on', '部署在'), ('connects_to', '连接到')], max_length=50, verbose_name='关系类型'),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='specs',
            field=models.JSONField(blank=True, default=dict, verbose_name='规格要求'),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
