from .common import rule


FS_FILTER = 'job="node-exporter",fstype!~"tmpfs|overlay|squashfs|nsfs|ramfs",mountpoint!~"/run.*|/var/lib/(docker|containerd).*"'

RULES = [
    rule('system', 'k8s-node-filesystem-full-24h', '节点文件系统预计24小时内用尽',
         f'(node_filesystem_avail_bytes{{{FS_FILTER}}} / node_filesystem_size_bytes{{{FS_FILTER}}} * 100 < 40) and predict_linear(node_filesystem_avail_bytes{{{FS_FILTER}}}[6h], 24*60*60) < 0 and node_filesystem_readonly{{{FS_FILTER}}} == 0',
         {'operator': '>', 'threshold': 0}, duration=3600, unit='percent',
         message='{{ $labels.cluster }} 集群 {{ $labels.instance }} 节点的 {{ $labels.device }} 文件系统预计24小时内用尽。',
         description='根据近6小时趋势预测可写文件系统24小时内耗尽。', source_names=('节点文件系统24小时内用完',), sort_order=1200),
    rule('system', 'k8s-node-filesystem-full-4h', '节点文件系统预计4小时内用尽',
         f'(node_filesystem_avail_bytes{{{FS_FILTER}}} / node_filesystem_size_bytes{{{FS_FILTER}}} * 100 < 20) and predict_linear(node_filesystem_avail_bytes{{{FS_FILTER}}}[6h], 4*60*60) < 0 and node_filesystem_readonly{{{FS_FILTER}}} == 0',
         {'operator': '>', 'threshold': 0}, level='critical', duration=3600, unit='percent', profile='full',
         message='{{ $labels.cluster }} 集群 {{ $labels.instance }} 节点的 {{ $labels.device }} 文件系统预计4小时内用尽。',
         description='根据近6小时趋势预测可写文件系统4小时内耗尽。', source_names=('节点文件系统4小时内用完',), sort_order=1210),
    rule('system', 'k8s-node-filesystem-available-low', '节点文件系统可用空间过低',
         f'node_filesystem_avail_bytes{{{FS_FILTER}}} / node_filesystem_size_bytes{{{FS_FILTER}}} * 100',
         {'levels': [
             {'level': 'warning', 'operator': '<', 'threshold': 20, 'duration_seconds': 300},
             {'level': 'critical', 'operator': '<', 'threshold': 10, 'duration_seconds': 300},
         ]}, duration=300, unit='percent', profile='full',
         message='{{ $labels.cluster }} 集群 {{ $labels.instance }} 节点的 {{ $labels.device }} 文件系统只剩 {{ printf "%.2f" $value }}% 可用空间。',
         description='采用Agent-1磁盘使用率80%/90%对应的可用率阈值。',
         source_names=('节点文件系统只剩下不到5%', '节点文件系统只剩下不到3%'), sort_order=1220),
    rule('system', 'k8s-node-inodes-full-24h', '节点 inode 预计24小时内用尽',
         f'(node_filesystem_files_free{{{FS_FILTER}}} / node_filesystem_files{{{FS_FILTER}}} * 100 < 40) and predict_linear(node_filesystem_files_free{{{FS_FILTER}}}[6h], 24*60*60) < 0 and node_filesystem_readonly{{{FS_FILTER}}} == 0',
         {'operator': '>', 'threshold': 0}, duration=3600, unit='percent',
         message='{{ $labels.cluster }} 集群 {{ $labels.instance }} 节点的 {{ $labels.device }} 文件系统 inode 预计24小时内用尽。',
         description='根据近6小时趋势预测inode 24小时内耗尽。', source_names=('节点挂载的文件系统空闲的文件节点个数24小时内用完',), sort_order=1230),
    rule('system', 'k8s-node-inodes-full-4h', '节点 inode 预计4小时内用尽',
         f'(node_filesystem_files_free{{{FS_FILTER}}} / node_filesystem_files{{{FS_FILTER}}} * 100 < 20) and predict_linear(node_filesystem_files_free{{{FS_FILTER}}}[6h], 4*60*60) < 0 and node_filesystem_readonly{{{FS_FILTER}}} == 0',
         {'operator': '>', 'threshold': 0}, level='critical', duration=3600, unit='percent', profile='full',
         message='{{ $labels.cluster }} 集群 {{ $labels.instance }} 节点的 {{ $labels.device }} 文件系统 inode 预计4小时内用尽。',
         description='根据近6小时趋势预测inode 4小时内耗尽。', source_names=('节点挂载的文件系统空闲的文件节点个数4小时内用完',), sort_order=1240),
    rule('system', 'k8s-node-inodes-available-low', '节点 inode 可用率过低',
         f'node_filesystem_files_free{{{FS_FILTER}}} / node_filesystem_files{{{FS_FILTER}}} * 100',
         {'levels': [
             {'level': 'warning', 'operator': '<', 'threshold': 20, 'duration_seconds': 300},
             {'level': 'critical', 'operator': '<', 'threshold': 10, 'duration_seconds': 300},
         ]}, duration=300, unit='percent', profile='full',
         message='{{ $labels.cluster }} 集群 {{ $labels.instance }} 节点的 {{ $labels.device }} 文件系统只剩 {{ printf "%.2f" $value }}% 可用 inode。',
         description='采用Agent-1 inode使用率80%/90%对应的可用率阈值。',
         source_names=('节点挂载的文件系统空闲的文件节点个数不到5%', '节点挂载的文件系统空闲的文件节点个数不到3%'), sort_order=1250),
    rule('system', 'k8s-node-high-cpu', '节点 CPU 使用率过高',
         '100 - (avg by(cluster,instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)',
         {'levels': [
             {'level': 'warning', 'operator': '>', 'threshold': 80, 'duration_seconds': 300},
             {'level': 'critical', 'operator': '>', 'threshold': 95, 'duration_seconds': 120},
         ]}, duration=300, unit='percent', profile='full',
         message='{{ $labels.cluster }} 集群 {{ $labels.instance }} 节点 CPU 使用率达到 {{ printf "%.0f" $value }}%。',
         description='Agent-1规范CPU Warning 80%、Critical 95%。', source_names=('节点CPU使用大于85%',), sort_order=1260),
    rule('system', 'k8s-node-high-memory', '节点内存使用率过高',
         '100 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100)',
         {'levels': [
             {'level': 'warning', 'operator': '>', 'threshold': 85, 'duration_seconds': 300},
             {'level': 'critical', 'operator': '>', 'threshold': 95, 'duration_seconds': 120},
         ]}, duration=300, unit='percent', profile='full',
         message='{{ $labels.cluster }} 集群 {{ $labels.instance }} 节点内存使用率达到 {{ printf "%.0f" $value }}%。',
         description='Agent-1规范内存Warning 85%、Critical 95%。', source_names=('节点内存空闲低',), sort_order=1270),
    rule('system', 'k8s-node-oom-kill', '节点发生 OOM Kill',
         'increase(node_vmstat_oom_kill[5m])', {'operator': '>', 'threshold': 0},
         level='critical', duration=0, profile='full',
         message='{{ $labels.cluster }} 集群 {{ $labels.instance }} 节点近5分钟发生 {{ printf "%.0f" $value }} 次 OOM Kill。',
         description='节点内核在5分钟窗口内发生OOM Kill。', source_names=('侦测到OOM触发行为',), sort_order=1280),
]
