from .common import rule


RULES = [
    rule('workload', 'k8s-pod-restarts', 'K8S 容器组短时间内多次重启',
         'sum by (cluster,namespace,pod,container) (increase(kube_pod_container_status_restarts_total{job="kube-state-metrics"}[10m]))',
         {'levels': [
             {'level': 'warning', 'operator': '>', 'threshold': 1, 'duration_seconds': 0},
             {'level': 'critical', 'operator': '>', 'threshold': 5, 'duration_seconds': 0},
         ]}, duration=0, profile='full',
         message='{{ $labels.cluster }} 集群容器组 {{ $labels.namespace }}/{{ $labels.pod }}（{{ $labels.container }}）在10分钟内重启了 {{ printf "%.0f" $value }} 次。',
         description='窗口内重启增量，不使用生命周期累计重启次数。',
         source_names=('K8S容器组短时间内多次重启',), sort_order=700),
    rule('workload', 'k8s-pod-waiting', 'K8S 容器组 Waiting',
         'max_over_time(kube_pod_container_status_waiting_reason{job="kube-state-metrics",reason!="ContainerCreating"}[5m])',
         {'operator': '>', 'threshold': 0}, level='critical', duration=180, profile='full',
         message='{{ $labels.cluster }} 集群容器组 {{ $labels.namespace }}/{{ $labels.pod }}（{{ $labels.container }}）处于 Waiting，原因为 {{ $labels.reason }}。',
         description='容器因非ContainerCreating原因持续等待。',
         source_names=('K8S容器组Waiting',), sort_order=710),
    rule('workload', 'k8s-pod-unschedulable', 'K8S 容器组调度失败',
         'sum by (cluster,namespace,pod) (kube_pod_status_unschedulable{job="kube-state-metrics"})',
         {'operator': '>', 'threshold': 0}, level='critical', duration=300, profile='full',
         message='{{ $labels.cluster }} 集群容器组 {{ $labels.namespace }}/{{ $labels.pod }} 无符合条件的节点，无法完成调度。',
         description='Pod持续处于Unschedulable状态。',
         source_names=('K8S容器组调度失败',), sort_order=720),
    rule('workload', 'k8s-pod-not-ready-long', 'K8S 容器组长时间 NotReady',
         'sum by (cluster,namespace,pod) (max by(cluster,namespace,pod) (kube_pod_status_phase{job="kube-state-metrics",phase=~"Pending|Unknown"}) * on(cluster,namespace,pod) group_left(owner_kind) max by(cluster,namespace,pod,owner_kind) (kube_pod_owner{job="kube-state-metrics",owner_kind!="Job"}))',
         {'operator': '>', 'threshold': 0}, level='critical', duration=900, profile='full',
         message='{{ $labels.cluster }} 集群 {{ $labels.namespace }}/{{ $labels.pod }} 已处于 NotReady 状态超过15分钟。',
         description='非Job Pod持续处于Pending或Unknown状态。',
         source_names=('K8S容器组NotReady',), sort_order=730),
    rule('workload', 'k8s-deployment-unavailable', 'K8S Deployment 状态异常',
         'kube_deployment_status_replicas_unavailable{job="kube-state-metrics"}',
         {'operator': '>', 'threshold': 0}, duration=900, profile='targeted',
         message='{{ $labels.cluster }} 集群 Deployment {{ $labels.namespace }}/{{ $labels.deployment }} 有 {{ printf "%.0f" $value }} 个实例不可用，已持续15分钟。',
         description='Deployment存在持续不可用副本。',
         source_names=('K8S部署状态异常',), sort_order=740),
    rule('workload', 'k8s-deployment-generation-mismatch', 'K8S Deployment 版本未完成观测',
         'kube_deployment_status_observed_generation{job="kube-state-metrics"} != on(cluster,namespace,deployment) kube_deployment_metadata_generation{job="kube-state-metrics"}',
         {'operator': '>', 'threshold': 0}, level='critical', duration=900, profile='full',
         message='{{ $labels.cluster }} 集群 Deployment {{ $labels.namespace }}/{{ $labels.deployment }} 的 observed generation 与 metadata generation 不一致。',
         description='Deployment控制器在15分钟内未完成新版本观测。',
         source_names=('K8S部署版本号不匹配',), sort_order=750),
    rule('workload', 'k8s-deployment-replicas-mismatch', 'K8S Deployment 实际副本与预期不一致',
         'kube_deployment_spec_replicas{job="kube-state-metrics"} != on(cluster,namespace,deployment) kube_deployment_status_replicas_available{job="kube-state-metrics"}',
         {'operator': '>', 'threshold': 0}, level='critical', duration=900, profile='full',
         message='{{ $labels.cluster }} 集群 Deployment {{ $labels.namespace }}/{{ $labels.deployment }} 的可用副本数与预期不一致超过15分钟。',
         description='Deployment可用副本未达到期望副本。',
         source_names=('K8S部署实际副本数与预期数不匹配',), sort_order=760),
    rule('workload', 'k8s-statefulset-replicas-mismatch', 'K8S StatefulSet 实际副本与预期不一致',
         'kube_statefulset_status_replicas_ready{job="kube-state-metrics"} != on(cluster,namespace,statefulset) kube_statefulset_replicas{job="kube-state-metrics"}',
         {'operator': '>', 'threshold': 0}, level='critical', duration=900, profile='full',
         message='{{ $labels.cluster }} 集群 StatefulSet {{ $labels.namespace }}/{{ $labels.statefulset }} 的就绪副本数与预期不一致超过15分钟。',
         description='StatefulSet就绪副本未达到期望副本。',
         source_names=('K8S有状态部署实际副本数与预期数不匹配',), sort_order=770),
    rule('workload', 'k8s-statefulset-generation-mismatch', 'K8S StatefulSet 版本未完成观测',
         'kube_statefulset_status_observed_generation{job="kube-state-metrics"} != on(cluster,namespace,statefulset) kube_statefulset_metadata_generation{job="kube-state-metrics"}',
         {'operator': '>', 'threshold': 0}, level='critical', duration=900, profile='full',
         message='{{ $labels.cluster }} 集群 StatefulSet {{ $labels.namespace }}/{{ $labels.statefulset }} 的 observed generation 与 metadata generation 不一致。',
         description='StatefulSet控制器未完成新版本观测。',
         source_names=('K8S有状态部署版本号不匹配',), sort_order=780),
    rule('workload', 'k8s-statefulset-update-stalled', 'K8S StatefulSet 更新未展开',
         'max without (revision) (kube_statefulset_status_current_revision{job="kube-state-metrics"} unless kube_statefulset_status_update_revision{job="kube-state-metrics"}) * on(cluster,namespace,statefulset) (kube_statefulset_replicas{job="kube-state-metrics"} != kube_statefulset_status_replicas_updated{job="kube-state-metrics"})',
         {'operator': '>', 'threshold': 0}, level='critical', duration=900, profile='full',
         message='{{ $labels.cluster }} 集群 StatefulSet {{ $labels.namespace }}/{{ $labels.statefulset }} 的更新未展开，当前版本仍非更新版本。',
         description='StatefulSet当前修订与更新修订不一致且副本未完成更新。',
         source_names=('K8S有状态部署更新未展开',), sort_order=790),
    rule('workload', 'k8s-daemonset-rollout-failed', 'K8S DaemonSet 展开失败',
         'kube_daemonset_status_number_ready{job="kube-state-metrics"} / clamp_min(kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics"}, 1)',
         {'operator': '<', 'threshold': 1}, level='critical', duration=900, unit='ratio', profile='full',
         message='{{ $labels.cluster }} 集群 DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} 只有 {{ $value | humanizePercentage }} 的预期Pod完成调度并就绪。',
         description='DaemonSet就绪比例持续低于100%。',
         source_names=('K8S守护进程集展开失败',), sort_order=800),
    rule('workload', 'k8s-daemonset-unscheduled', 'K8S DaemonSet 存在未调度 Pod',
         'kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics"} - kube_daemonset_status_current_number_scheduled{job="kube-state-metrics"}',
         {'operator': '>', 'threshold': 0}, duration=600, profile='targeted',
         message='{{ $labels.cluster }} 集群 DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} 有 {{ printf "%.0f" $value }} 个Pod未被调度。',
         description='DaemonSet当前调度数低于期望调度数。',
         source_names=('K8S守护进程集未被调度',), sort_order=810),
    rule('workload', 'k8s-daemonset-misscheduled', 'K8S DaemonSet 调度错误',
         'kube_daemonset_status_number_misscheduled{job="kube-state-metrics"}',
         {'operator': '>', 'threshold': 0}, duration=600, profile='targeted',
         message='{{ $labels.cluster }} 集群 DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} 有 {{ printf "%.0f" $value }} 个非预期Pod正在运行。',
         description='DaemonSet Pod被调度到非预期节点。',
         source_names=('K8S守护进程集调度错误',), sort_order=820),
    rule('workload', 'k8s-cronjob-overdue', 'K8S CronJob 调度超时',
         'time() - kube_cronjob_next_schedule_time{job="kube-state-metrics"}',
         {'operator': '>', 'threshold': 3600}, duration=3600, profile='targeted',
         message='{{ $labels.cluster }} 集群 CronJob {{ $labels.namespace }}/{{ $labels.cronjob }} 已超过1小时未按计划完成调度。',
         description='CronJob下一计划时间已逾期超过1小时。',
         source_names=('K8S定时任务运行中',), sort_order=830),
    rule('workload', 'k8s-job-incomplete-long', 'K8S Job 长时间未完成',
         'kube_job_spec_completions{job="kube-state-metrics"} - on(cluster,namespace,job_name) kube_job_status_succeeded{job="kube-state-metrics"}',
         {'operator': '>', 'threshold': 0}, duration=3600, profile='targeted',
         message='{{ $labels.cluster }} 集群 Job {{ $labels.namespace }}/{{ $labels.job_name }} 已运行超过1小时仍未完成。',
         description='Job成功完成数持续低于预期完成数。',
         source_names=('K8S任务完成',), sort_order=840),
    rule('workload', 'k8s-job-failed', 'K8S Job 执行失败',
         'kube_job_failed{job="kube-state-metrics"}', {'operator': '>', 'threshold': 0},
         duration=900, profile='targeted',
         message='{{ $labels.cluster }} 集群 Job {{ $labels.namespace }}/{{ $labels.job_name }} 执行失败。',
         description='Job出现失败状态。', source_names=('K8S任务失败',), sort_order=850),
    rule('workload', 'k8s-hpa-replicas-mismatch', 'K8S HPA 副本数未收敛',
         '(kube_hpa_status_desired_replicas{job="kube-state-metrics"} != on(cluster,namespace,hpa) kube_hpa_status_current_replicas{job="kube-state-metrics"}) and on(cluster,namespace,hpa) changes(kube_hpa_status_current_replicas{job="kube-state-metrics"}[15m]) == 0',
         {'operator': '>', 'threshold': 0}, duration=900, profile='targeted',
         message='{{ $labels.cluster }} 集群 HPA {{ $labels.namespace }}/{{ $labels.hpa }} 的当前副本与期望副本不一致且15分钟内未收敛。',
         description='HPA副本数不一致并持续无变化。',
         source_names=('K8S的HPA副本数不匹配',), sort_order=860),
    rule('workload', 'k8s-hpa-scale-down-event', 'K8S HPA 缩容事件',
         '(kube_hpa_status_desired_replicas{job="kube-state-metrics"} == on(cluster,namespace,hpa) kube_hpa_status_current_replicas{job="kube-state-metrics"}) and on(cluster,namespace,hpa) delta(kube_hpa_status_current_replicas{job="kube-state-metrics"}[5m]) < 0',
         {'operator': '<', 'threshold': 0}, level='info', duration=60, notify=False, analyze=False,
         message='{{ $labels.cluster }} 集群 HPA {{ $labels.namespace }}/{{ $labels.hpa }} 已完成缩容，当前副本数为 {{ printf "%.0f" $value }}。',
         description='HPA正常缩容信息事件。', source_names=('侦测到K8S的HPA缩容',), sort_order=870),
    rule('workload', 'k8s-hpa-scale-up-event', 'K8S HPA 扩容事件',
         '(kube_hpa_status_desired_replicas{job="kube-state-metrics"} == on(cluster,namespace,hpa) kube_hpa_status_current_replicas{job="kube-state-metrics"}) and on(cluster,namespace,hpa) delta(kube_hpa_status_current_replicas{job="kube-state-metrics"}[5m]) > 0',
         {'operator': '>', 'threshold': 0}, level='info', duration=60, notify=False, analyze=False,
         message='{{ $labels.cluster }} 集群 HPA {{ $labels.namespace }}/{{ $labels.hpa }} 已完成扩容，当前副本数为 {{ printf "%.0f" $value }}。',
         description='HPA正常扩容信息事件。', source_names=('侦测到K8S的HPA扩容',), sort_order=880),
    rule('workload', 'k8s-hpa-at-max', 'K8S HPA 持续满载',
         'kube_hpa_status_current_replicas{job="kube-state-metrics"} == on(cluster,namespace,hpa) kube_hpa_spec_max_replicas{job="kube-state-metrics"}',
         {'operator': '>', 'threshold': 0}, duration=900, profile='targeted',
         message='{{ $labels.cluster }} 集群 HPA {{ $labels.namespace }}/{{ $labels.hpa }} 已在最大副本数持续运行15分钟。',
         description='HPA达到最大副本数，需检查容量与目标指标。',
         source_names=('K8S工作负载的HPA保持满载',), sort_order=890),
    rule('workload', 'k8s-deployment-rollout-event', 'K8S Deployment 版本变更完成',
         '(kube_deployment_status_observed_generation{job="kube-state-metrics"} == on(cluster,namespace,deployment) kube_deployment_metadata_generation{job="kube-state-metrics"}) and on(cluster,namespace,deployment) (kube_deployment_spec_replicas{job="kube-state-metrics"} == kube_deployment_status_replicas_available{job="kube-state-metrics"}) and on(cluster,namespace,deployment) changes(kube_deployment_status_observed_generation{job="kube-state-metrics"}[5m]) > 0',
         {'operator': '>', 'threshold': 0}, level='info', duration=60, notify=False, analyze=False,
         message='{{ $labels.cluster }} 集群 Deployment {{ $labels.namespace }}/{{ $labels.deployment }} 已完成版本变更，实例数达到预期。',
         description='Deployment发布成功信息事件。',
         source_names=('K8S部署服务版本变更通告',), sort_order=900),
    rule('workload', 'k8s-deployment-rollout-failed', 'K8S Deployment 版本变更异常',
         '((kube_deployment_status_observed_generation{job="kube-state-metrics"} != on(cluster,namespace,deployment) kube_deployment_metadata_generation{job="kube-state-metrics"}) or on(cluster,namespace,deployment) (kube_deployment_spec_replicas{job="kube-state-metrics"} != kube_deployment_status_replicas_available{job="kube-state-metrics"})) and on(cluster,namespace,deployment) changes(kube_deployment_metadata_generation{job="kube-state-metrics"}[5m]) > 0',
         {'operator': '>', 'threshold': 0}, level='critical', duration=60, profile='full',
         message='{{ $labels.cluster }} 集群 Deployment {{ $labels.namespace }}/{{ $labels.deployment }} 发生版本变更后，新版本未完成观测或可用实例未达到预期。',
         description='仅针对Deployment版本变更后的发布异常，不混入正常HPA扩缩容。',
         source_names=('K8S部署服务版本变更异常',), sort_order=910),
]
