# Generated by Django 6.0 on 2026-02-11 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128, unique=True, verbose_name='主机名')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 地址')),
                ('os_type', models.CharField(default='Linux', max_length=64, verbose_name='操作系统')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('warning', '告警')], default='online', max_length=16, verbose_name='状态')),
                ('cpu_usage', models.FloatField(default=0, verbose_name='CPU 使用率 (%)')),
                ('memory_usage', models.FloatField(default=0, verbose_name='内存使用率 (%)')),
                ('disk_usage', models.FloatField(default=0, verbose_name='磁盘使用率 (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=128, verbose_name='应用名称')),
                ('version', models.CharField(max_length=64, verbose_name='版本号')),
                ('environment', models.CharField(choices=[('production', '生产'), ('staging', '预发布'), ('testing', '测试'), ('development', '开发')], default='testing', max_length=32, verbose_name='环境')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('running', '部署中'), ('pending', '待部署'), ('rollback', '已回滚')], default='pending', max_length=16, verbose_name='状态')),
                ('deployer', models.CharField(default='admin', max_length=64, verbose_name='部署人')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('deployed_at', models.DateTimeField(auto_now_add=True, verbose_name='部署时间')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ops.host', verbose_name='部署主机')),
            ],
            options={
                'verbose_name': '部署记录',
                'verbose_name_plural': '部署记录',
                'ordering': ['-deployed_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='告警标题')),
                ('level', models.CharField(choices=[('critical', '严重'), ('warning', '警告'), ('info', '信息')], default='info', max_length=16, verbose_name='级别')),
                ('source', models.CharField(max_length=128, verbose_name='来源')),
                ('message', models.TextField(verbose_name='详情')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='已确认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ops.host', verbose_name='关联主机')),
            ],
            options={
                'verbose_name': '告警',
                'verbose_name_plural': '告警',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('error', 'ERROR'), ('warning', 'WARNING'), ('info', 'INFO'), ('debug', 'DEBUG')], default='info', max_length=16, verbose_name='级别')),
                ('service', models.CharField(max_length=128, verbose_name='服务名')),
                ('message', models.TextField(verbose_name='日志内容')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ops.host', verbose_name='来源主机')),
            ],
            options={
                'verbose_name': '日志',
                'verbose_name_plural': '日志',
                'ordering': ['-timestamp'],
            },
        ),
    ]
