# Generated by Django 6.0 on 2026-03-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ssh_password',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='SSH 密码'),
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_port',
            field=models.IntegerField(default=22, verbose_name='SSH 端口'),
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_user',
            field=models.CharField(default='root', max_length=64, verbose_name='SSH 用户'),
        ),
    ]
