# Generated by Django 6.0 on 2026-03-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_host_ssh_password_host_ssh_port_host_ssh_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='K8sCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='集群名称')),
                ('api_server', models.CharField(blank=True, default='', max_length=256, verbose_name='API Server')),
                ('kubeconfig', models.TextField(help_text='YAML 格式的 kubeconfig 内容', verbose_name='KubeConfig')),
                ('status', models.CharField(choices=[('connected', '已连接'), ('disconnected', '未连接'), ('error', '异常')], default='disconnected', max_length=16, verbose_name='状态')),
                ('description', models.CharField(blank=True, default='', max_length=256, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'K8s 集群',
                'verbose_name_plural': 'K8s 集群',
                'ordering': ['-created_at'],
            },
        ),
    ]
