# Generated by Django 6.0 on 2026-03-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_k8scluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='环境名称')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 地址')),
                ('ssh_port', models.IntegerField(default=22, verbose_name='SSH 端口')),
                ('ssh_user', models.CharField(default='root', max_length=64, verbose_name='SSH 用户')),
                ('ssh_password', models.CharField(blank=True, default='', max_length=256, verbose_name='SSH 密码')),
                ('docker_api_version', models.CharField(blank=True, default='', max_length=16, verbose_name='Docker API 版本')),
                ('status', models.CharField(choices=[('connected', '已连接'), ('disconnected', '未连接'), ('error', '异常')], default='disconnected', max_length=16, verbose_name='状态')),
                ('description', models.CharField(blank=True, default='', max_length=256, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Docker 环境',
                'verbose_name_plural': 'Docker 环境',
                'ordering': ['-created_at'],
            },
        ),
    ]
