# Generated by Django 6.0 on 2026-03-12 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_dockerhost'),
    ]

    operations = [
        migrations.CreateModel(
            name='NginxCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='证书对应的域名', max_length=256, verbose_name='证书域名')),
                ('cert_content', models.TextField(blank=True, default='', verbose_name='证书内容 (PEM)')),
                ('key_content', models.TextField(blank=True, default='', verbose_name='私钥内容 (KEY)')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('description', models.CharField(blank=True, default='', max_length=256, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Nginx 证书',
                'verbose_name_plural': 'Nginx 证书',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NginxEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='环境名称')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 地址')),
                ('ssh_port', models.IntegerField(default=22, verbose_name='SSH 端口')),
                ('ssh_user', models.CharField(default='root', max_length=64, verbose_name='SSH 用户')),
                ('ssh_password', models.CharField(blank=True, default='', max_length=256, verbose_name='SSH 密码')),
                ('nginx_path', models.CharField(default='/etc/nginx', max_length=256, verbose_name='Nginx 路径')),
                ('status', models.CharField(choices=[('connected', '已连接'), ('disconnected', '未连接'), ('error', '异常')], default='disconnected', max_length=16, verbose_name='状态')),
                ('description', models.CharField(blank=True, default='', max_length=256, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Nginx 环境',
                'verbose_name_plural': 'Nginx 环境',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NginxDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='填写域名或 IP 地址', max_length=256, verbose_name='域名/IP')),
                ('listen_port', models.IntegerField(default=80, verbose_name='监听端口')),
                ('ssl_port', models.IntegerField(default=443, verbose_name='SSL 端口')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_domains', to='ops.nginxcertificate', verbose_name='关联证书')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='ops.nginxenvironment', verbose_name='所属环境')),
            ],
            options={
                'verbose_name': 'Nginx 域名',
                'verbose_name_plural': 'Nginx 域名',
                'ordering': ['-created_at'],
                'unique_together': {('environment', 'domain', 'listen_port')},
            },
        ),
        migrations.AddField(
            model_name='nginxcertificate',
            name='environments',
            field=models.ManyToManyField(blank=True, related_name='certificates', to='ops.nginxenvironment', verbose_name='关联环境'),
        ),
        migrations.CreateModel(
            name='NginxRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='/', max_length=256, verbose_name='Location 路径')),
                ('upstream_servers', models.TextField(default='', help_text='每行一个后端地址，如 http://127.0.0.1:8080', verbose_name='后端地址')),
                ('redirect_url', models.CharField(blank=True, default='', max_length=512, verbose_name='重定向地址')),
                ('redirect_code', models.IntegerField(default=301, verbose_name='重定向状态码')),
                ('custom_headers', models.TextField(blank=True, default='', help_text='[{"name":"X-Custom","value":"val"}]', verbose_name='自定义 Header (JSON)')),
                ('proxy_set_headers', models.TextField(blank=True, default='', help_text='[{"name":"Host","value":"$host"}]', verbose_name='proxy_set_header (JSON)')),
                ('client_max_body_size', models.CharField(blank=True, default='10m', max_length=32, verbose_name='上传大小限制')),
                ('extra_directives', models.TextField(blank=True, default='', help_text='原始 Nginx 指令，每行一条', verbose_name='额外指令')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('nginx_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='ops.nginxdomain', verbose_name='所属域名')),
            ],
            options={
                'verbose_name': 'Nginx 路由',
                'verbose_name_plural': 'Nginx 路由',
                'ordering': ['-created_at'],
                'unique_together': {('nginx_domain', 'location')},
            },
        ),
    ]
