# Generated by Django 6.0 on 2026-03-13 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0005_nginxcertificate_nginxenvironment_nginxdomain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='类型名称')),
                ('icon', models.CharField(default='Box', max_length=64, verbose_name='图标')),
                ('color', models.CharField(default='#8b5cf6', max_length=32, verbose_name='颜色')),
                ('description', models.CharField(blank=True, default='', max_length=256, verbose_name='描述')),
                ('built_in', models.BooleanField(default=False, verbose_name='内置类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'CI 类型',
                'verbose_name_plural': 'CI 类型',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='申请标题')),
                ('requester', models.CharField(default='admin', max_length=64, verbose_name='申请人')),
                ('resource_type', models.CharField(help_text='如 ECS, RDS, Redis', max_length=64, verbose_name='资源类型')),
                ('specification', models.TextField(blank=True, default='', help_text='如 4C8G, 2C4G SSD100G', verbose_name='规格说明')),
                ('business_line', models.CharField(blank=True, default='', max_length=128, verbose_name='业务线')),
                ('environment', models.CharField(choices=[('production', '生产'), ('staging', '预发布'), ('testing', '测试'), ('development', '开发')], default='testing', max_length=32, verbose_name='环境')),
                ('reason', models.TextField(blank=True, default='', verbose_name='申请原因')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('completed', '已完成')], default='pending', max_length=16, verbose_name='状态')),
                ('reviewer', models.CharField(blank=True, default='', max_length=64, verbose_name='审批人')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资源申请',
                'verbose_name_plural': '资源申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='nginxroute',
            name='upstream_servers',
            field=models.TextField(blank=True, default='', help_text='每行一个后端地址，如 http://127.0.0.1:8080', verbose_name='后端地址'),
        ),
        migrations.CreateModel(
            name='ConfigItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('business_line', models.CharField(blank=True, default='', max_length=128, verbose_name='业务线')),
                ('environment', models.CharField(choices=[('production', '生产'), ('staging', '预发布'), ('testing', '测试'), ('development', '开发')], default='production', max_length=32, verbose_name='环境')),
                ('status', models.CharField(choices=[('active', '运行中'), ('inactive', '已停用'), ('maintenance', '维护中'), ('decommissioned', '已下线')], default='active', max_length=32, verbose_name='状态')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('cloud_provider', models.CharField(blank=True, default='', help_text='如 阿里云, AWS, 腾讯云, 华为云', max_length=64, verbose_name='云厂商')),
                ('region', models.CharField(blank=True, default='', max_length=64, verbose_name='区域')),
                ('instance_type', models.CharField(blank=True, default='', max_length=64, verbose_name='实例规格')),
                ('cpu', models.IntegerField(default=0, verbose_name='CPU (核)')),
                ('memory_gb', models.FloatField(default=0, verbose_name='内存 (GB)')),
                ('disk_gb', models.FloatField(default=0, verbose_name='磁盘 (GB)')),
                ('monthly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='月成本 (元)')),
                ('tags', models.JSONField(blank=True, default=dict, help_text='自定义标签, 如 {"team":"backend"}', verbose_name='标签')),
                ('owner', models.CharField(blank=True, default='', max_length=64, verbose_name='负责人')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ci_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='config_items', to='ops.citype', verbose_name='CI 类型')),
            ],
            options={
                'verbose_name': '配置项',
                'verbose_name_plural': '配置项',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CIRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('depends_on', '依赖'), ('deployed_on', '部署在'), ('connects_to', '连接'), ('contains', '包含'), ('backup_of', '备份')], default='depends_on', max_length=32, verbose_name='关系类型')),
                ('description', models.CharField(blank=True, default='', max_length=256, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('source_ci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='ops.configitem', verbose_name='源 CI')),
                ('target_ci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='ops.configitem', verbose_name='目标 CI')),
            ],
            options={
                'verbose_name': 'CI 关系',
                'verbose_name_plural': 'CI 关系',
                'unique_together': {('source_ci', 'target_ci', 'relation_type')},
            },
        ),
        migrations.CreateModel(
            name='CostRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='格式: YYYY-MM', max_length=7, verbose_name='账期')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='费用 (元)')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='费用明细')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('config_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_records', to='ops.configitem', verbose_name='配置项')),
            ],
            options={
                'verbose_name': '成本记录',
                'verbose_name_plural': '成本记录',
                'ordering': ['-period'],
                'unique_together': {('config_item', 'period')},
            },
        ),
    ]
