# Generated by Django 6.0 on 2026-03-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0006_citype_resourcerequest_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cirelation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cirelation',
            name='source_ci',
        ),
        migrations.RemoveField(
            model_name='cirelation',
            name='target_ci',
        ),
        migrations.RemoveField(
            model_name='configitem',
            name='ci_type',
        ),
        migrations.AlterUniqueTogether(
            name='costrecord',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='costrecord',
            name='config_item',
        ),

        migrations.DeleteModel(
            name='ResourceRequest',
        ),
        migrations.DeleteModel(
            name='CIRelation',
        ),
        migrations.DeleteModel(
            name='CIType',
        ),
        migrations.DeleteModel(
            name='ConfigItem',
        ),
        migrations.DeleteModel(
            name='CostRecord',
        ),
    ]
