# Generated by Django 6.0 on 2026-03-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0007_alter_cirelation_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('provider', models.CharField(choices=[('loki', 'Loki'), ('elk', 'ELK / Elasticsearch'), ('sls', '阿里云 SLS')], max_length=16, verbose_name='日志类型')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='连接配置')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认数据源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '日志数据源',
                'verbose_name_plural': '日志数据源',
                'ordering': ['provider', 'name'],
            },
        ),
    ]
