# Generated by Django 6.0 on 2026-03-19 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0012_seed_loki_demo_datasource'),
    ]

    operations = [
        migrations.CreateModel(
            name='K8sConfigRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=32)),
                ('namespace', models.CharField(max_length=128)),
                ('resource_name', models.CharField(max_length=255)),
                ('secret_type', models.CharField(blank=True, default='', max_length=128)),
                ('content', models.TextField()),
                ('operator', models.CharField(blank=True, default='', max_length=64)),
                ('action', models.CharField(choices=[('update', 'Update Snapshot'), ('rollback', 'Rollback Snapshot')], default='update', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_revisions', to='ops.k8scluster')),
            ],
            options={
                'verbose_name': 'K8s config revision',
                'verbose_name_plural': 'K8s config revisions',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['cluster', 'resource_type', 'namespace', 'resource_name'], name='ops_k8sconf_cluster_d94a16_idx')],
            },
        ),
    ]
