# Generated by Django 6.0 on 2026-03-24 03:10

import django.db.models.deletion
from django.db import migrations, models


def backfill_deployment_release_workflow(apps, schema_editor):
    Deployment = apps.get_model('ops', 'Deployment')

    latest_current = {}
    for deployment in Deployment.objects.all().order_by('deployed_at', 'id'):
        update_fields = []
        old_status = deployment.status

        if old_status == 'success':
            deployment.status = 'running'
            deployment.approval_status = 'approved'
            deployment.executed_at = deployment.deployed_at
            deployment.finished_at = deployment.deployed_at
            deployment.execution_count = 1
            update_fields.extend(['status', 'approval_status', 'executed_at', 'finished_at', 'execution_count'])
        elif old_status == 'failed':
            deployment.status = 'failed'
            deployment.approval_status = 'approved'
            deployment.executed_at = deployment.deployed_at
            deployment.finished_at = deployment.deployed_at
            deployment.execution_count = 1
            update_fields.extend(['status', 'approval_status', 'executed_at', 'finished_at', 'execution_count'])
        elif old_status == 'running':
            deployment.status = 'deploying'
            deployment.approval_status = 'approved'
            deployment.executed_at = deployment.deployed_at
            deployment.execution_count = 1
            update_fields.extend(['status', 'approval_status', 'executed_at', 'execution_count'])
        elif old_status == 'rollback':
            deployment.status = 'removed'
            deployment.approval_status = 'approved'
            deployment.action_type = 'rollback'
            deployment.executed_at = deployment.deployed_at
            deployment.finished_at = deployment.deployed_at
            deployment.execution_count = 1
            update_fields.extend(['status', 'approval_status', 'action_type', 'executed_at', 'finished_at', 'execution_count'])
        else:
            deployment.status = 'pending'
            deployment.approval_status = 'pending'
            update_fields.extend(['status', 'approval_status'])

        if not deployment.submitter:
            deployment.submitter = deployment.deployer or 'admin'
            update_fields.append('submitter')
        if deployment.approval_status == 'approved':
            if not deployment.approver:
                deployment.approver = deployment.deployer or deployment.submitter or 'admin'
                update_fields.append('approver')
            if not deployment.approved_at:
                deployment.approved_at = deployment.deployed_at
                update_fields.append('approved_at')
        if not deployment.deploy_mode:
            deployment.deploy_mode = 'docker_compose'
            update_fields.append('deploy_mode')
        if not deployment.image:
            deployment.image = f'{deployment.app_name}:{deployment.version}'
            update_fields.append('image')
        if not deployment.release_name:
            deployment.release_name = f'{deployment.app_name}-{deployment.environment}'.replace(' ', '-').lower()
            update_fields.append('release_name')
        if update_fields:
            deployment.save(update_fields=list(dict.fromkeys(update_fields)))

        target_key = (
            deployment.app_name,
            deployment.environment,
            deployment.deploy_mode,
            deployment.host_id or 0,
            deployment.cluster_id or 0,
            deployment.namespace or '',
        )
        if deployment.status in {'running', 'stopped'}:
            latest_current[target_key] = deployment.id

    Deployment.objects.filter(is_current=True).update(is_current=False)
    if latest_current:
        Deployment.objects.filter(id__in=list(latest_current.values())).update(is_current=True)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0013_k8sconfigrevision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deployment',
            options={'ordering': ['-deployed_at'], 'verbose_name': '应用发布', 'verbose_name_plural': '应用发布'},
        ),
        migrations.AddField(
            model_name='deployment',
            name='action_type',
            field=models.CharField(
                choices=[('deploy', '应用发布'), ('rollback', '版本回滚'), ('rerun', '重新执行')],
                default='deploy',
                max_length=16,
                verbose_name='发布类型',
            ),
        ),
        migrations.AddField(
            model_name='deployment',
            name='approval_comment',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='审批意见'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='approval_status',
            field=models.CharField(
                choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝')],
                default='pending',
                max_length=16,
                verbose_name='审批状态',
            ),
        ),
        migrations.AddField(
            model_name='deployment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批时间'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='approver',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='change_summary',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='变更说明'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ops.k8scluster', verbose_name='目标集群'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='container_port',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='容器端口'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='deploy_dir',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='发布目录'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='deploy_log',
            field=models.TextField(blank=True, default='', verbose_name='发布日志'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='deploy_mode',
            field=models.CharField(
                choices=[('docker_compose', 'Docker 环境'), ('k8s', 'K8s 集群')],
                default='docker_compose',
                max_length=32,
                verbose_name='发布模式',
            ),
        ),
        migrations.AddField(
            model_name='deployment',
            name='env_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='环境变量'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='执行时间'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='execution_count',
            field=models.PositiveIntegerField(default=0, verbose_name='执行次数'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='镜像地址'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='当前生效版本'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='namespace',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='命名空间'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='previous_success',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_releases', to='ops.deployment', verbose_name='上一成功版本'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='release_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='发布名称'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='replicas',
            field=models.PositiveIntegerField(default=1, verbose_name='副本数'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='rerun_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rerun_requests', to='ops.deployment', verbose_name='重试来源'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='rollback_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollback_requests', to='ops.deployment', verbose_name='回滚来源'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='service_port',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='服务端口'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='submitter',
            field=models.CharField(default='admin', max_length=64, verbose_name='申请人'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='deployed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='deployer',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='执行人'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ops.host', verbose_name='目标主机'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', '待执行'),
                    ('rejected', '已驳回'),
                    ('deploying', '发布中'),
                    ('running', '运行中'),
                    ('stopped', '已停止'),
                    ('failed', '发布失败'),
                    ('removed', '已下线'),
                ],
                default='pending',
                max_length=16,
                verbose_name='执行状态',
            ),
        ),
        migrations.AlterField(
            model_name='host',
            name='cpu_usage',
            field=models.FloatField(default=0, verbose_name='CPU 使用率(%)'),
        ),
        migrations.AlterField(
            model_name='host',
            name='disk_usage',
            field=models.FloatField(default=0, verbose_name='磁盘使用率(%)'),
        ),
        migrations.AlterField(
            model_name='host',
            name='memory_usage',
            field=models.FloatField(default=0, verbose_name='内存使用率(%)'),
        ),
        migrations.RunPython(backfill_deployment_release_workflow, noop_reverse),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['approval_status', 'status'], name='ops_deploym_approva_18f98e_idx'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['app_name', 'environment', 'deployed_at'], name='ops_deploym_app_nam_b34cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['is_current', 'deploy_mode'], name='ops_deploym_is_curr_5bf44d_idx'),
        ),
        migrations.AddConstraint(
            model_name='deployment',
            constraint=models.UniqueConstraint(
                condition=models.Q(('deploy_mode', 'docker_compose'), ('is_current', True)),
                fields=('app_name', 'environment', 'host'),
                name='uniq_ops_current_app_env_host_compose',
            ),
        ),
        migrations.AddConstraint(
            model_name='deployment',
            constraint=models.UniqueConstraint(
                condition=models.Q(('deploy_mode', 'k8s'), ('is_current', True)),
                fields=('app_name', 'environment', 'cluster', 'namespace'),
                name='uniq_ops_current_app_env_cluster_ns_k8s',
            ),
        ),
    ]
