# Generated by Django 6.0 on 2026-03-24 04:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0014_alter_deployment_options_deployment_action_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentApprovalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='流程名称')),
                ('environment', models.CharField(blank=True, choices=[('', '全部环境'), ('production', '生产'), ('staging', '预发布'), ('testing', '测试'), ('development', '开发')], default='', max_length=32, verbose_name='适用环境')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_by', models.CharField(blank=True, default='', max_length=64, verbose_name='维护人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '发布审批流程',
                'verbose_name_plural': '发布审批流程',
                'ordering': ['environment', 'name', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='deployment',
            name='batch_current',
            field=models.PositiveIntegerField(default=0, verbose_name='当前批次'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='batch_size',
            field=models.PositiveIntegerField(default=1, verbose_name='单批规模'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='batch_total',
            field=models.PositiveIntegerField(default=1, verbose_name='批次总数'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='canary_percent',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='灰度比例'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='release_strategy',
            field=models.CharField(choices=[('standard', '标准发布'), ('canary', '灰度发布'), ('batch', '批次发布')], default='standard', max_length=16, verbose_name='发布策略'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='strategy_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='策略配置'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='approval_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='ops.deploymentapprovalflow', verbose_name='审批流程'),
        ),
        migrations.CreateModel(
            name='DeploymentApprovalNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='节点名称')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='排序')),
                ('approver_type', models.CharField(choices=[('user', '指定用户'), ('role', '指定角色'), ('group', '指定用户组')], default='user', max_length=16, verbose_name='审批人类型')),
                ('approver_value', models.CharField(blank=True, default='', max_length=128, verbose_name='审批人值')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='节点说明')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='ops.deploymentapprovalflow', verbose_name='所属流程')),
            ],
            options={
                'verbose_name': '审批流程节点',
                'verbose_name_plural': '审批流程节点',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('flow', 'order'), name='uniq_ops_deploy_approval_flow_node_order')],
            },
        ),
        migrations.CreateModel(
            name='DeploymentApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=128, verbose_name='节点名称')),
                ('node_order', models.PositiveIntegerField(default=1, verbose_name='节点排序')),
                ('approver_type', models.CharField(choices=[('user', '指定用户'), ('role', '指定角色'), ('group', '指定用户组')], default='user', max_length=16, verbose_name='审批人类型')),
                ('approver_value', models.CharField(blank=True, default='', max_length=128, verbose_name='审批人值')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=16, verbose_name='节点状态')),
                ('is_current', models.BooleanField(default=False, verbose_name='当前节点')),
                ('approver', models.CharField(blank=True, default='', max_length=64, verbose_name='审批人')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='审批意见')),
                ('acted_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='ops.deployment', verbose_name='发布单')),
                ('flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='ops.deploymentapprovalflow', verbose_name='审批流程')),
            ],
            options={
                'verbose_name': '发布审批步骤',
                'verbose_name_plural': '发布审批步骤',
                'ordering': ['node_order', 'id'],
                'indexes': [models.Index(fields=['deployment', 'status', 'is_current'], name='ops_deploym_deploym_937ec3_idx')],
                'constraints': [models.UniqueConstraint(fields=('deployment', 'node_order'), name='uniq_ops_deploy_approval_step_order')],
            },
        ),
    ]
