# Generated by Django 6.0 on 2026-03-24 06:29

from django.db import migrations, models


def normalize_deployment_environments(apps, schema_editor):
    deployment_model = apps.get_model('ops', 'Deployment')
    flow_model = apps.get_model('ops', 'DeploymentApprovalFlow')
    env_map = {
        'production': 'prod',
        'staging': 'test',
        'testing': 'test',
        'development': 'dev',
    }
    for old_value, new_value in env_map.items():
        deployment_model.objects.filter(environment=old_value).update(environment=new_value)
        flow_model.objects.filter(environment=old_value).update(environment=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0015_deploymentapprovalflow_deployment_batch_current_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deployment',
            name='uniq_ops_current_app_env_host_compose',
        ),
        migrations.RemoveConstraint(
            model_name='deployment',
            name='uniq_ops_current_app_env_cluster_ns_k8s',
        ),
        migrations.RemoveIndex(
            model_name='deployment',
            name='ops_deploym_app_nam_b34cd8_idx',
        ),
        migrations.AddField(
            model_name='deployment',
            name='business_line',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='业务线'),
        ),
        migrations.RunPython(normalize_deployment_environments, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='deployment',
            name='environment',
            field=models.CharField(choices=[('prod', '生产'), ('test', '测试'), ('dev', '开发')], default='test', max_length=32, verbose_name='环境'),
        ),
        migrations.AlterField(
            model_name='deploymentapprovalflow',
            name='environment',
            field=models.CharField(blank=True, choices=[('', '全部环境'), ('prod', '生产'), ('test', '测试'), ('dev', '开发')], default='', max_length=32, verbose_name='适用环境'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['business_line', 'app_name', 'environment', 'deployed_at'], name='ops_deploym_busines_da4863_idx'),
        ),
        migrations.AddConstraint(
            model_name='deployment',
            constraint=models.UniqueConstraint(condition=models.Q(('deploy_mode', 'docker_compose'), ('is_current', True)), fields=('business_line', 'app_name', 'environment', 'host'), name='uniq_ops_curr_biz_app_host'),
        ),
        migrations.AddConstraint(
            model_name='deployment',
            constraint=models.UniqueConstraint(condition=models.Q(('deploy_mode', 'k8s'), ('is_current', True)), fields=('business_line', 'app_name', 'environment', 'cluster', 'namespace'), name='uniq_ops_curr_biz_app_k8s'),
        ),
    ]
