# Generated by Django 6.0 on 2026-03-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0017_deployment_docker_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='admin_user',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='host',
            name='business_line',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='业务线'),
        ),
        migrations.AddField(
            model_name='host',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='host',
            name='environment',
            field=models.CharField(blank=True, choices=[('prod', '生产'), ('test', '测试'), ('dev', '开发')], default='', max_length=20, verbose_name='环境'),
        ),
    ]
