# Generated by Django 6.0 on 2026-03-30 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0019_hosttask_hosttaskexecution'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='????')),
                ('task_type', models.CharField(choices=[('check_connection', 'SSH ?????'), ('refresh_metrics', '??????'), ('run_command', '??????'), ('service_status', '??????')], max_length=32, verbose_name='????')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='????')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='????')),
                ('execution_strategy', models.CharField(choices=[('continue', '????'), ('stop_on_error', '????')], default='continue', max_length=20, verbose_name='????')),
                ('timeout_seconds', models.PositiveIntegerField(default=15, verbose_name='????(?)')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='??????')),
                ('created_by', models.CharField(blank=True, default='system', max_length=64, verbose_name='???')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='????')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='????')),
            ],
            options={
                'verbose_name': '??????',
                'verbose_name_plural': '??????',
                'ordering': ['-is_builtin', 'name', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='hosttask',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': '????', 'verbose_name_plural': '????'},
        ),
        migrations.AlterModelOptions(
            name='hosttaskexecution',
            options={'ordering': ['id'], 'verbose_name': '????????', 'verbose_name_plural': '????????'},
        ),
        migrations.AddField(
            model_name='hosttask',
            name='cancel_requested',
            field=models.BooleanField(default=False, verbose_name='???????'),
        ),
        migrations.AddField(
            model_name='hosttask',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='??????'),
        ),
        migrations.AddField(
            model_name='hosttask',
            name='cancel_requested_by',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='?????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='created_by',
            field=models.CharField(default='system', max_length=64, verbose_name='???'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='execution_strategy',
            field=models.CharField(choices=[('continue', '????'), ('stop_on_error', '????')], default='continue', max_length=20, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='failed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='name',
            field=models.CharField(max_length=128, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='selection_filters',
            field=models.JSONField(blank=True, default=dict, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='status',
            field=models.CharField(choices=[('pending', '???'), ('running', '???'), ('success', '????'), ('partial', '????'), ('failed', '????'), ('canceled', '???')], default='pending', max_length=16, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='success_count',
            field=models.PositiveIntegerField(default=0, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='target_count',
            field=models.PositiveIntegerField(default=0, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='target_snapshot',
            field=models.JSONField(blank=True, default=list, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='task_type',
            field=models.CharField(choices=[('check_connection', 'SSH ?????'), ('refresh_metrics', '??????'), ('run_command', '??????'), ('service_status', '??????')], max_length=32, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=15, verbose_name='????(?)'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='command',
            field=models.TextField(blank=True, default='', verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='duration_ms',
            field=models.PositiveIntegerField(default=0, verbose_name='??(??)'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_executions', to='ops.host', verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='host_ip',
            field=models.GenericIPAddressField(verbose_name='?? IP ??'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='host_name',
            field=models.CharField(default='', max_length=128, verbose_name='?????'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='output',
            field=models.TextField(blank=True, default='', verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='status',
            field=models.CharField(choices=[('success', '??'), ('failed', '??'), ('skipped', '??')], default='success', max_length=16, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ops.hosttask', verbose_name='????'),
        ),
    ]
