# Generated by Django 6.0 on 2026-03-31 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0020_hosttasktemplate_alter_hosttask_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hosttask',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': '主机任务', 'verbose_name_plural': '主机任务'},
        ),
        migrations.AlterModelOptions(
            name='hosttaskexecution',
            options={'ordering': ['id'], 'verbose_name': '任务执行明细', 'verbose_name_plural': '任务执行明细'},
        ),
        migrations.AlterModelOptions(
            name='hosttasktemplate',
            options={'ordering': ['-is_builtin', 'name', '-id'], 'verbose_name': '任务模板', 'verbose_name_plural': '任务模板'},
        ),
        migrations.AddField(
            model_name='hosttask',
            name='execution_mode',
            field=models.CharField(choices=[('ssh', 'SSH'), ('ansible', 'Ansible')], default='ssh', max_length=16, verbose_name='执行方式'),
        ),
        migrations.AddField(
            model_name='hosttasktemplate',
            name='execution_mode',
            field=models.CharField(choices=[('ssh', 'SSH'), ('ansible', 'Ansible')], default='ssh', max_length=16, verbose_name='执行方式'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='cancel_requested',
            field=models.BooleanField(default=False, verbose_name='已申请终止'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='终止申请时间'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='cancel_requested_by',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='终止申请人'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='created_by',
            field=models.CharField(default='system', max_length=64, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='任务说明'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='execution_strategy',
            field=models.CharField(choices=[('continue', '失败继续'), ('stop_on_error', '失败即停')], default='continue', max_length=20, verbose_name='执行策略'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='failed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='失败数量'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='name',
            field=models.CharField(max_length=128, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='任务参数'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='selection_filters',
            field=models.JSONField(blank=True, default=dict, verbose_name='筛选条件'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0, verbose_name='跳过数量'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='status',
            field=models.CharField(choices=[('pending', '排队中'), ('running', '执行中'), ('success', '全部成功'), ('partial', '部分成功'), ('failed', '执行失败'), ('canceled', '已终止')], default='pending', max_length=16, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='success_count',
            field=models.PositiveIntegerField(default=0, verbose_name='成功数量'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='执行摘要'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='target_count',
            field=models.PositiveIntegerField(default=0, verbose_name='目标数量'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='target_snapshot',
            field=models.JSONField(blank=True, default=list, verbose_name='目标快照'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='task_type',
            field=models.CharField(choices=[('check_connection', 'SSH 连通性校验'), ('refresh_metrics', '主机信息刷新'), ('run_command', '批量命令执行'), ('service_status', '服务状态巡检')], max_length=32, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=15, verbose_name='超时(秒)'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='command',
            field=models.TextField(blank=True, default='', verbose_name='执行命令'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='duration_ms',
            field=models.PositiveIntegerField(default=0, verbose_name='耗时(毫秒)'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_executions', to='ops.host', verbose_name='主机'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='host_ip',
            field=models.GenericIPAddressField(verbose_name='主机 IP'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='host_name',
            field=models.CharField(default='', max_length=128, verbose_name='主机名称'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='output',
            field=models.TextField(blank=True, default='', verbose_name='输出内容'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='status',
            field=models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('skipped', '跳过')], default='success', max_length=16, verbose_name='执行状态'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ops.hosttask', verbose_name='任务'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='created_by',
            field=models.CharField(blank=True, default='system', max_length=64, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='模板说明'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='execution_strategy',
            field=models.CharField(choices=[('continue', '失败继续'), ('stop_on_error', '失败即停')], default='continue', max_length=20, verbose_name='执行策略'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='is_builtin',
            field=models.BooleanField(default=False, verbose_name='是否内置'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='name',
            field=models.CharField(max_length=128, verbose_name='模板名称'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='模板参数'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='task_type',
            field=models.CharField(choices=[('check_connection', 'SSH 连通性校验'), ('refresh_metrics', '主机信息刷新'), ('run_command', '批量命令执行'), ('service_status', '服务状态巡检')], max_length=32, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=15, verbose_name='超时(秒)'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
