# Generated by Django 6.0 on 2026-03-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0021_alter_hosttask_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosttask',
            name='task_type',
            field=models.CharField(choices=[('check_connection', 'SSH 连通性校验'), ('refresh_metrics', '主机信息刷新'), ('run_command', '批量命令执行'), ('run_playbook', 'Ansible Playbook 执行'), ('service_status', '服务状态巡检')], max_length=32, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='task_type',
            field=models.CharField(choices=[('check_connection', 'SSH 连通性校验'), ('refresh_metrics', '主机信息刷新'), ('run_command', '批量命令执行'), ('run_playbook', 'Ansible Playbook 执行'), ('service_status', '服务状态巡检')], max_length=32, verbose_name='任务类型'),
        ),
    ]
