# Generated by Django 6.0 on 2026-04-01 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0022_alter_hosttask_task_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostTaskSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='????')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='????')),
                ('enabled', models.BooleanField(default=True, verbose_name='????')),
                ('task_type', models.CharField(choices=[('check_connection', 'SSH ?????'), ('refresh_metrics', '??????'), ('run_command', '??????'), ('run_playbook', 'Ansible Playbook ??'), ('service_status', '??????')], max_length=32, verbose_name='????')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='????')),
                ('selection_filters', models.JSONField(blank=True, default=dict, verbose_name='????')),
                ('target_host_ids', models.JSONField(blank=True, default=list, verbose_name='??????')),
                ('target_snapshot', models.JSONField(blank=True, default=list, verbose_name='????')),
                ('target_count', models.PositiveIntegerField(default=0, verbose_name='????')),
                ('execution_mode', models.CharField(choices=[('ssh', 'SSH'), ('ansible', 'Ansible')], default='ssh', max_length=16, verbose_name='????')),
                ('execution_strategy', models.CharField(choices=[('continue', '????'), ('stop_on_error', '????')], default='continue', max_length=20, verbose_name='????')),
                ('timeout_seconds', models.PositiveIntegerField(default=15, verbose_name='??(?)')),
                ('schedule_type', models.CharField(choices=[('once', '????'), ('interval', '????'), ('cron', 'Cron ???')], default='cron', max_length=16, verbose_name='????')),
                ('cron_expression', models.CharField(blank=True, default='', max_length=64, verbose_name='Cron ???')),
                ('interval_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='????')),
                ('run_at', models.DateTimeField(blank=True, null=True, verbose_name='??????')),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=64, verbose_name='??')),
                ('overlap_policy', models.CharField(choices=[('skip', '??????'), ('allow', '??????')], default='skip', max_length=16, verbose_name='????')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='??????')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='??????')),
                ('last_status', models.CharField(blank=True, choices=[('pending', '???'), ('running', '???'), ('success', '????'), ('partial', '????'), ('failed', '????'), ('canceled', '???')], default='', max_length=16, verbose_name='????')),
                ('consecutive_failures', models.PositiveIntegerField(default=0, verbose_name='??????')),
                ('total_run_count', models.PositiveIntegerField(default=0, verbose_name='??????')),
                ('last_error', models.CharField(blank=True, default='', max_length=255, verbose_name='????')),
                ('created_by', models.CharField(default='system', max_length=64, verbose_name='???')),
                ('updated_by', models.CharField(blank=True, default='', max_length=64, verbose_name='???')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='????')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='????')),
            ],
            options={
                'verbose_name': '????',
                'verbose_name_plural': '????',
                'ordering': ['-enabled', 'next_run_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='hosttask',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': '????', 'verbose_name_plural': '????'},
        ),
        migrations.AlterModelOptions(
            name='hosttaskexecution',
            options={'ordering': ['id'], 'verbose_name': '??????', 'verbose_name_plural': '??????'},
        ),
        migrations.AlterModelOptions(
            name='hosttasktemplate',
            options={'ordering': ['-is_builtin', 'name', '-id'], 'verbose_name': '????', 'verbose_name_plural': '????'},
        ),
        migrations.AddField(
            model_name='hosttask',
            name='trigger_source',
            field=models.CharField(choices=[('manual', '????'), ('schedule', '????')], default='manual', max_length=16, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='cancel_requested',
            field=models.BooleanField(default=False, verbose_name='??????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='??????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='cancel_requested_by',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='?????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='created_by',
            field=models.CharField(default='system', max_length=64, verbose_name='???'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='execution_mode',
            field=models.CharField(choices=[('ssh', 'SSH'), ('ansible', 'Ansible')], default='ssh', max_length=16, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='execution_strategy',
            field=models.CharField(choices=[('continue', '????'), ('stop_on_error', '????')], default='continue', max_length=20, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='failed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='name',
            field=models.CharField(max_length=128, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='selection_filters',
            field=models.JSONField(blank=True, default=dict, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='status',
            field=models.CharField(choices=[('pending', '???'), ('running', '???'), ('success', '????'), ('partial', '????'), ('failed', '????'), ('canceled', '???')], default='pending', max_length=16, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='success_count',
            field=models.PositiveIntegerField(default=0, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='target_count',
            field=models.PositiveIntegerField(default=0, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='target_snapshot',
            field=models.JSONField(blank=True, default=list, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='task_type',
            field=models.CharField(choices=[('check_connection', 'SSH ?????'), ('refresh_metrics', '??????'), ('run_command', '??????'), ('run_playbook', 'Ansible Playbook ??'), ('service_status', '??????')], max_length=32, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=15, verbose_name='??(?)'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='command',
            field=models.TextField(blank=True, default='', verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='duration_ms',
            field=models.PositiveIntegerField(default=0, verbose_name='??(??)'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_executions', to='ops.host', verbose_name='??'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='host_ip',
            field=models.GenericIPAddressField(verbose_name='?? IP'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='host_name',
            field=models.CharField(default='', max_length=128, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='output',
            field=models.TextField(blank=True, default='', verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='status',
            field=models.CharField(choices=[('success', '??'), ('failed', '??'), ('skipped', '??')], default='success', max_length=16, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ops.hosttask', verbose_name='??'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='created_by',
            field=models.CharField(blank=True, default='system', max_length=64, verbose_name='???'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='execution_mode',
            field=models.CharField(choices=[('ssh', 'SSH'), ('ansible', 'Ansible')], default='ssh', max_length=16, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='execution_strategy',
            field=models.CharField(choices=[('continue', '????'), ('stop_on_error', '????')], default='continue', max_length=20, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='is_builtin',
            field=models.BooleanField(default=False, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='name',
            field=models.CharField(max_length=128, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='task_type',
            field=models.CharField(choices=[('check_connection', 'SSH ?????'), ('refresh_metrics', '??????'), ('run_command', '??????'), ('run_playbook', 'Ansible Playbook ??'), ('service_status', '??????')], max_length=32, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=15, verbose_name='??(?)'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='????'),
        ),
        migrations.AddField(
            model_name='hosttask',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='ops.hosttaskschedule', verbose_name='????'),
        ),
        migrations.CreateModel(
            name='HostTaskScheduleExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_source', models.CharField(choices=[('scheduler', '?????'), ('manual', '????')], default='scheduler', max_length=16, verbose_name='????')),
                ('status', models.CharField(choices=[('pending', '???'), ('running', '???'), ('success', '????'), ('partial', '????'), ('failed', '????'), ('canceled', '???')], default='pending', max_length=16, verbose_name='????')),
                ('summary', models.CharField(blank=True, default='', max_length=255, verbose_name='????')),
                ('target_count', models.PositiveIntegerField(default=0, verbose_name='????')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='????')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='????')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='????')),
                ('error_message', models.CharField(blank=True, default='', max_length=255, verbose_name='????')),
                ('requested_by', models.CharField(default='system', max_length=64, verbose_name='???')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='????')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='????')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='????')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='????')),
                ('host_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_execution', to='ops.hosttask', verbose_name='????')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ops.hosttaskschedule', verbose_name='??')),
            ],
            options={
                'verbose_name': '????????',
                'verbose_name_plural': '????????',
                'ordering': ['-requested_at', '-id'],
            },
        ),
    ]
