# Generated by Django 6.0 on 2026-04-09 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0023_hosttaskschedule_alter_hosttask_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='工单标题')),
                ('ticket_type', models.CharField(choices=[('change', '变更执行'), ('inspection', '巡检任务'), ('access', '权限开通'), ('incident', '故障处理')], default='change', max_length=32, verbose_name='事务类型')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=16, verbose_name='优先级')),
                ('business_line', models.CharField(blank=True, default='', max_length=50, verbose_name='业务线')),
                ('environment', models.CharField(blank=True, choices=[('prod', '生产'), ('test', '测试'), ('dev', '开发')], default='', max_length=32, verbose_name='环境')),
                ('owner', models.CharField(blank=True, default='', max_length=64, verbose_name='处理人')),
                ('applicant', models.CharField(default='system', max_length=64, verbose_name='申请人')),
                ('window', models.CharField(blank=True, default='', max_length=128, verbose_name='执行窗口')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('processing', '处理中'), ('done', '已完成'), ('rejected', '已驳回')], default='pending', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approval_flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_tickets', to='ops.deploymentapprovalflow', verbose_name='审批流')),
            ],
            options={
                'verbose_name': '事务工单',
                'verbose_name_plural': '事务工单',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='transactionticket',
            index=models.Index(fields=['status', 'priority', '-updated_at'], name='ops_ticket_status_priority_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionticket',
            index=models.Index(fields=['business_line', 'environment'], name='ops_ticket_biz_env_idx'),
        ),
    ]
