# Generated by Codex on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0024_transactionticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='TracingDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Tracing data source name')),
                ('provider', models.CharField(choices=[('skywalking', 'SkyWalking'), ('tempo', 'Tempo / OpenTelemetry'), ('jaeger', 'Jaeger / OpenTelemetry'), ('zipkin', 'Zipkin / OpenTelemetry')], max_length=16, verbose_name='Tracing provider')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Connection config')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default data source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Tracing data source',
                'verbose_name_plural': 'Tracing data sources',
                'ordering': ['provider', 'name'],
            },
        ),
    ]
