# Generated by Codex on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0025_tracingdatasource'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrafanaSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=64, unique=True, verbose_name='配置名称')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('url', models.CharField(blank=True, default='', max_length=255, verbose_name='Grafana URL')),
                ('default_path', models.CharField(blank=True, default='', max_length=255, verbose_name='默认看板路径')),
                ('dashboards', models.JSONField(blank=True, default=list, verbose_name='看板配置')),
                ('updated_by', models.CharField(blank=True, default='', max_length=64, verbose_name='更新人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Grafana 配置',
                'verbose_name_plural': 'Grafana 配置',
            },
        ),
    ]
