# Generated by Django 6.0 on 2026-06-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0056_hosttaskexecution_running_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemPostureEnvironment',
        ),
        migrations.RemoveIndex(
            model_name='systempostureslahistory',
            name='ops_posture_sla_day_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='systempostureslahistory',
            name='ops_posture_sla_system_day_idx',
        ),
        migrations.RemoveConstraint(
            model_name='systempostureslahistory',
            name='ops_posture_sla_day_system_uniq',
        ),
        migrations.DeleteModel(
            name='SystemPostureSLAHistory',
        ),
        migrations.DeleteModel(
            name='SystemPostureSystem',
        ),
    ]
