# Generated by Codex on 2026-06-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventwall', '0006_eventenvironment'),
        ('ops', '0057_delete_system_posture_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresourcegroup',
            name='event_environment',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='task_resource_groups',
                to='eventwall.eventenvironment',
                verbose_name='事件中心环境',
            ),
        ),
    ]
