# Generated by Codex on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0058_taskresourcegroup_event_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='k8scluster',
            name='user_type',
            field=models.CharField(
                choices=[('readonly', '只读用户'), ('admin', '管理用户')],
                default='readonly',
                max_length=16,
                verbose_name='访问身份',
            ),
        ),
    ]
