# Generated by Django 5.2.16 on 2026-07-10 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0070_observability_engine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hosttask',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': '主机任务', 'verbose_name_plural': '主机任务'},
        ),
        migrations.AlterModelOptions(
            name='hosttaskexecution',
            options={'ordering': ['id'], 'verbose_name': '主机执行记录', 'verbose_name_plural': '主机执行记录'},
        ),
        migrations.AlterModelOptions(
            name='hosttaskschedule',
            options={'ordering': ['-enabled', 'next_run_at', '-id'], 'verbose_name': '定时编排', 'verbose_name_plural': '定时编排'},
        ),
        migrations.AlterModelOptions(
            name='hosttaskscheduleexecution',
            options={'ordering': ['-requested_at', '-id'], 'verbose_name': '编排执行记录', 'verbose_name_plural': '编排执行记录'},
        ),
        migrations.AlterModelOptions(
            name='hosttasktemplate',
            options={'ordering': ['-is_builtin', 'name', '-id'], 'verbose_name': '任务模板', 'verbose_name_plural': '任务模板'},
        ),
        migrations.RenameIndex(
            model_name='alertclaim',
            new_name='ops_alertcl_alert_i_14ce2e_idx',
            old_name='ops_alrtclm_alrt_clm_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionticket',
            new_name='ops_transac_status_0f34ce_idx',
            old_name='ops_ticket_status_priority_updated_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionticket',
            new_name='ops_transac_busines_5522d6_idx',
            old_name='ops_ticket_biz_env_idx',
        ),
        migrations.AlterField(
            model_name='alertinteractiontoken',
            name='action',
            field=models.CharField(choices=[('rule_evaluation', '规则触发'), ('notify', '发送通知'), ('acknowledge', '确认'), ('claim', '认领'), ('unclaim', '取消认领'), ('mute', '屏蔽'), ('escalate', '升级'), ('resolve', '恢复'), ('close', '关闭'), ('reopen', '重新打开'), ('comment', '备注')], max_length=32, verbose_name='动作'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='cancel_requested',
            field=models.BooleanField(default=False, verbose_name='已请求取消'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取消时间'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='cancel_requested_by',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='取消发起人'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='created_by',
            field=models.CharField(default='system', max_length=64, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='任务说明'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='execution_strategy',
            field=models.CharField(choices=[('continue', '失败继续'), ('stop_on_error', '遇错停止')], default='continue', max_length=20, verbose_name='执行策略'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='failed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='失败数量'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='name',
            field=models.CharField(max_length=128, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='任务载荷'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='ops.hosttaskschedule', verbose_name='来源编排'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='selection_filters',
            field=models.JSONField(blank=True, default=dict, verbose_name='筛选条件'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0, verbose_name='跳过数量'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='status',
            field=models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '执行成功'), ('partial', '部分成功'), ('failed', '执行失败'), ('canceled', '已取消')], default='pending', max_length=16, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='success_count',
            field=models.PositiveIntegerField(default=0, verbose_name='成功数量'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='执行摘要'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='target_count',
            field=models.PositiveIntegerField(default=0, verbose_name='目标数量'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='target_snapshot',
            field=models.JSONField(blank=True, default=list, verbose_name='目标快照'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=15, verbose_name='超时(秒)'),
        ),
        migrations.AlterField(
            model_name='hosttask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='command',
            field=models.TextField(blank=True, default='', verbose_name='执行命令'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='duration_ms',
            field=models.PositiveIntegerField(default=0, verbose_name='耗时(毫秒)'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_executions', to='ops.host', verbose_name='主机'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='host_name',
            field=models.CharField(default='', max_length=128, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='output',
            field=models.TextField(blank=True, default='', verbose_name='执行输出'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='hosttaskexecution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ops.hosttask', verbose_name='任务'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0, verbose_name='连续失败次数'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='created_by',
            field=models.CharField(default='system', max_length=64, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='cron_expression',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Cron 表达式'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='编排说明'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='execution_mode',
            field=models.CharField(choices=[('ssh', 'SSH'), ('ansible', 'Ansible'), ('k8s_api', 'K8s API')], default='ssh', max_length=16, verbose_name='执行方式'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='execution_strategy',
            field=models.CharField(choices=[('continue', '失败继续'), ('stop_on_error', '遇错停止')], default='continue', max_length=20, verbose_name='执行策略'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='interval_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='间隔秒数'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='last_error',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='最近错误'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='last_status',
            field=models.CharField(blank=True, choices=[('pending', '待执行'), ('running', '执行中'), ('success', '执行成功'), ('partial', '部分成功'), ('failed', '执行失败'), ('canceled', '已取消')], default='', max_length=16, verbose_name='上次状态'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='name',
            field=models.CharField(max_length=128, verbose_name='编排名称'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='next_run_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='overlap_policy',
            field=models.CharField(choices=[('skip', '跳过重叠执行'), ('allow', '允许重叠执行')], default='skip', max_length=16, verbose_name='重叠策略'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='任务载荷'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='run_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='执行时间'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='schedule_type',
            field=models.CharField(choices=[('once', '单次执行'), ('interval', '间隔执行'), ('cron', 'Cron 表达式')], default='cron', max_length=16, verbose_name='调度类型'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='selection_filters',
            field=models.JSONField(blank=True, default=dict, verbose_name='筛选条件'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='target_count',
            field=models.PositiveIntegerField(default=0, verbose_name='目标数量'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='target_host_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='指定主机列表'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='target_snapshot',
            field=models.JSONField(blank=True, default=list, verbose_name='目标快照'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='task_type',
            field=models.CharField(choices=[('check_connection', 'SSH 连通性检查'), ('refresh_metrics', '主机指标刷新'), ('run_command', '批量命令执行'), ('run_playbook', 'Ansible Playbook 执行'), ('service_status', '服务状态巡检'), ('k8s_restart_pod', 'K8s Pod 重启'), ('k8s_pod_exec', 'K8s Pod 命令执行'), ('k8s_scale_workload', 'K8s 工作负载伸缩')], max_length=32, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=15, verbose_name='超时(秒)'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='timezone',
            field=models.CharField(default='Asia/Shanghai', max_length=64, verbose_name='时区'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='total_run_count',
            field=models.PositiveIntegerField(default=0, verbose_name='累计执行次数'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='hosttaskschedule',
            name='updated_by',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='hosttaskscheduleexecution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hosttaskscheduleexecution',
            name='error_message',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='hosttaskscheduleexecution',
            name='failed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='失败数量'),
        ),
        migrations.AlterField(
            model_name='hosttaskscheduleexecution',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='hosttaskscheduleexecution',
            name='host_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_execution', to='ops.hosttask', verbose_name='关联任务'),
        ),
        migrations.AlterField(
            model_name='hosttaskscheduleexecution',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发起时间'),
        ),
        migrations.AlterField(
            model_name='hosttaskscheduleexecution',
            name='requested_by',
            field=models.CharField(default='system', max_length=64, verbose_name='发起人'),
        ),
        migrations.AlterField(
            model_name='hosttaskscheduleexecution',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ops.hosttaskschedule', verbose_name='编排'),
        ),
        migrations.AlterField(
            model_name='hosttaskscheduleexecution',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0, verbose_name='跳过数量'),
        ),
        migrations.AlterField(
            model_name='hosttaskscheduleexecution',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='hosttaskscheduleexecution',
            name='status',
            field=models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '执行成功'), ('partial', '部分成功'), ('failed', '执行失败'), ('canceled', '已取消')], default='pending', max_length=16, verbose_name='执行状态'),
        ),
        migrations.AlterField(
            model_name='hosttaskscheduleexecution',
            name='success_count',
            field=models.PositiveIntegerField(default=0, verbose_name='成功数量'),
        ),
        migrations.AlterField(
            model_name='hosttaskscheduleexecution',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='执行摘要'),
        ),
        migrations.AlterField(
            model_name='hosttaskscheduleexecution',
            name='target_count',
            field=models.PositiveIntegerField(default=0, verbose_name='目标数量'),
        ),
        migrations.AlterField(
            model_name='hosttaskscheduleexecution',
            name='trigger_source',
            field=models.CharField(choices=[('scheduler', '自动调度'), ('manual', '手动执行')], default='scheduler', max_length=16, verbose_name='触发来源'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='created_by',
            field=models.CharField(blank=True, default='system', max_length=64, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='模板说明'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='execution_strategy',
            field=models.CharField(choices=[('continue', '失败继续'), ('stop_on_error', '遇错停止')], default='continue', max_length=20, verbose_name='执行策略'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='is_builtin',
            field=models.BooleanField(default=False, verbose_name='系统内置'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='name',
            field=models.CharField(max_length=128, verbose_name='模板名称'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='模板载荷'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=15, verbose_name='超时(秒)'),
        ),
        migrations.AlterField(
            model_name='hosttasktemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='taskresource',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='运维负责人'),
        ),
    ]
