# Generated by Django 5.2.16 on 2026-07-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0073_seed_alert_template_bundles'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='resource_category',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16, verbose_name='资源分类'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='category',
            field=models.CharField(choices=[('server', '服务器'), ('k8s', 'Kubernetes'), ('storage', '存储'), ('database', '数据库')], db_index=True, default='server', max_length=16, verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='alertruletemplate',
            name='category',
            field=models.CharField(choices=[('server', '服务器'), ('k8s', 'Kubernetes'), ('storage', '存储'), ('database', '数据库')], db_index=True, default='server', max_length=16, verbose_name='分类'),
        ),
    ]
