# Generated by Django 6.0.7 on 2026-07-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0074_alert_resource_category_alertrule_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='root_cause',
            field=models.TextField(blank=True, default='', verbose_name='根因'),
        ),
        migrations.AddField(
            model_name='alert',
            name='suggestion',
            field=models.TextField(blank=True, default='', verbose_name='建议'),
        ),
    ]
