# Generated by Django 5.2.16 on 2026-07-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0079_alert_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiddlewareAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='资产名称')),
                ('asset_type', models.CharField(choices=[('redis', 'Redis'), ('kafka', 'Kafka'), ('rocketmq', 'RocketMQ'), ('elasticsearch', 'Elasticsearch')], max_length=32, verbose_name='资产类型')),
                ('environment', models.CharField(blank=True, default='prod', max_length=32, verbose_name='环境')),
                ('endpoint', models.CharField(max_length=255, verbose_name='访问地址')),
                ('version', models.CharField(blank=True, default='', max_length=64, verbose_name='版本')),
                ('status', models.CharField(choices=[('unknown', '未检测'), ('healthy', '正常'), ('warning', '异常'), ('offline', '离线')], default='unknown', max_length=16, verbose_name='状态')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('created_by', models.CharField(blank=True, default='system', max_length=64, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, default='', max_length=64, verbose_name='更新人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '中间件资产',
                'verbose_name_plural': '中间件资产',
                'ordering': ['asset_type', 'environment', 'name', 'id'],
                'indexes': [models.Index(fields=['asset_type', 'environment', 'status'], name='ops_middlew_asset_t_ab9215_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset_type', 'environment', 'name'), name='uniq_ops_middleware_asset_scope')],
            },
        ),
    ]
