# Generated by Django 5.2.16 on 2026-07-16 06:28

from django.db import migrations, models


def migrate_elasticsearch_assets_to_database(apps, schema_editor):
    MiddlewareAsset = apps.get_model('ops', 'MiddlewareAsset')
    MiddlewareAsset.objects.filter(asset_type='elasticsearch').update(asset_type='database')


def reverse_database_assets_to_elasticsearch(apps, schema_editor):
    # The former Elasticsearch classification intentionally has no reversible
    # mapping once users can register arbitrary database engines.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0080_middlewareasset'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deployment',
            name='uniq_ops_curr_biz_app_docker_host',
        ),
        migrations.AddField(
            model_name='middlewareasset',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='访问密码'),
        ),
        migrations.AddField(
            model_name='middlewareasset',
            name='username',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='访问用户名'),
        ),
        migrations.RunPython(
            migrate_elasticsearch_assets_to_database,
            reverse_database_assets_to_elasticsearch,
        ),
        migrations.AlterField(
            model_name='deployment',
            name='deploy_mode',
            field=models.CharField(choices=[('k8s', 'K8s 集群')], default='k8s', max_length=32, verbose_name='发布模式'),
        ),
        migrations.AlterField(
            model_name='middlewareasset',
            name='asset_type',
            field=models.CharField(choices=[('redis', 'Redis'), ('kafka', 'Kafka'), ('rocketmq', 'RocketMQ'), ('database', '数据库')], max_length=32, verbose_name='资产类型'),
        ),
    ]
