# Generated by Django 5.2.16 on 2026-07-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0083_middleware_asset_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='middlewareasset',
            name='business_groups',
            field=models.ManyToManyField(blank=True, related_name='shared_middleware_assets', to='ops.taskresourcegroup', verbose_name='一级资产业务分组'),
        ),
        migrations.AddField(
            model_name='taskresource',
            name='business_groups',
            field=models.ManyToManyField(blank=True, related_name='task_resources', to='ops.taskresourcegroup', verbose_name='一级资产业务分组'),
        ),
    ]
