# Generated by Django 5.2.16 on 2026-07-17 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0027_alter_aiopsknowledgeenvironment_k8s_cluster_and_more'),
        ('ops', '0085_backfill_asset_business_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='计划名称')),
                ('frequency', models.CharField(choices=[('daily', '每天'), ('weekly', '每周')], default='weekly', max_length=16, verbose_name='发送周期')),
                ('weekday', models.PositiveSmallIntegerField(default=1, help_text='1=周一，7=周日', verbose_name='星期')),
                ('send_time', models.TimeField(default='09:00', verbose_name='发送时间')),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=64, verbose_name='时区')),
                ('profile', models.CharField(choices=[('cluster', '集群综合巡检'), ('control_plane', '控制平面巡检'), ('node', '节点巡检'), ('workload', '工作负载巡检'), ('service', '服务巡检')], default='cluster', max_length=32, verbose_name='巡检范围')),
                ('depth', models.CharField(default='full', max_length=16, verbose_name='巡检深度')),
                ('window_minutes', models.PositiveIntegerField(default=60, verbose_name='证据时间窗分钟')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='下次执行时间')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='最近执行时间')),
                ('last_status', models.CharField(choices=[('never', '未执行'), ('success', '成功'), ('partial', '部分成功'), ('failed', '失败')], default='never', max_length=16, verbose_name='最近状态')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='最近错误')),
                ('last_report', models.JSONField(blank=True, default=dict, verbose_name='最近报告')),
                ('created_by', models.CharField(blank=True, default='', max_length=128, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('channels', models.ManyToManyField(related_name='inspection_report_schedules', to='ops.alertnotificationchannel', verbose_name='通知渠道')),
                ('knowledge_environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_report_schedules', to='aiops.aiopsknowledgeenvironment', verbose_name='业务上下文')),
                ('recipient_groups', models.ManyToManyField(blank=True, related_name='inspection_report_schedules', to='ops.alertrecipientgroup', verbose_name='接收组')),
                ('recipients', models.ManyToManyField(blank=True, related_name='inspection_report_schedules', to='ops.alertrecipient', verbose_name='接收人')),
            ],
            options={
                'verbose_name': '巡检报告计划',
                'verbose_name_plural': '巡检报告计划',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InspectionReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('scheduler', '自动调度'), ('manual', '手动执行')], default='scheduler', max_length=16, verbose_name='触发方式')),
                ('status', models.CharField(choices=[('running', '执行中'), ('success', '成功'), ('partial', '部分成功'), ('failed', '失败')], default='running', max_length=16, verbose_name='执行状态')),
                ('report', models.JSONField(blank=True, default=dict, verbose_name='巡检报告')),
                ('delivery_results', models.JSONField(blank=True, default=list, verbose_name='发送结果')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ops.inspectionreportschedule', verbose_name='巡检报告计划')),
            ],
            options={
                'verbose_name': '巡检报告执行记录',
                'verbose_name_plural': '巡检报告执行记录',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='inspectionreportschedule',
            index=models.Index(fields=['is_enabled', 'next_run_at'], name='ops_irs_enabled_next_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionreportexecution',
            index=models.Index(fields=['schedule', 'started_at'], name='ops_ire_schedule_time_idx'),
        ),
    ]
