# Generated by Django 5.2.16 on 2026-07-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0095_canonicalize_alert_environment_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='source_type',
            field=models.CharField(choices=[('platform', '平台告警规则'), ('zabbix', 'Zabbix'), ('alertmanager', 'Alertmanager')], default='platform', max_length=32, verbose_name='来源类型'),
        ),
    ]
