# Generated by Django 5.2.16 on 2026-07-27 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0027_alter_aiopsknowledgeenvironment_k8s_cluster_and_more'),
        ('ops', '0096_alter_alert_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='binding_status',
            field=models.CharField(choices=[('not_applicable', '不适用'), ('bound', '已绑定'), ('unbound', '待绑定')], db_index=True, default='not_applicable', max_length=16, verbose_name='业务上下文绑定状态'),
        ),
        migrations.CreateModel(
            name='ExternalAlertSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='接入源名称')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='接入源编码')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='接入标识')),
                ('provider', models.CharField(choices=[('alertmanager', 'Alertmanager'), ('zabbix', 'Zabbix')], max_length=32, verbose_name='来源类型')),
                ('mapping_rules', models.JSONField(blank=True, default=list, verbose_name='业务上下文映射规则')),
                ('token_digest', models.CharField(blank=True, default='', max_length=64, verbose_name='Token 摘要')),
                ('token_hint', models.CharField(blank=True, default='', max_length=8, verbose_name='Token 尾号')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='允许接入')),
                ('notify_enabled', models.BooleanField(default=False, verbose_name='发送通知')),
                ('analyze_enabled', models.BooleanField(default=True, verbose_name='执行智能研判')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=120, verbose_name='每分钟请求上限')),
                ('last_received_at', models.DateTimeField(blank=True, null=True, verbose_name='最近请求时间')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='最近成功时间')),
                ('last_error_at', models.DateTimeField(blank=True, null=True, verbose_name='最近失败时间')),
                ('last_error', models.CharField(blank=True, default='', max_length=500, verbose_name='最近失败原因')),
                ('total_requests', models.PositiveBigIntegerField(default=0, verbose_name='请求总数')),
                ('accepted_requests', models.PositiveBigIntegerField(default=0, verbose_name='成功请求数')),
                ('rejected_requests', models.PositiveBigIntegerField(default=0, verbose_name='拒绝请求数')),
                ('received_alerts', models.PositiveBigIntegerField(default=0, verbose_name='接收告警数')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('default_knowledge_environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_alert_sources', to='aiops.aiopsknowledgeenvironment', verbose_name='默认业务上下文')),
            ],
            options={
                'verbose_name': '外部告警接入源',
                'verbose_name_plural': '外部告警接入源',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExternalAlertIngressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='请求 ID')),
                ('status', models.CharField(choices=[('accepted', '已接收'), ('rejected', '已拒绝'), ('error', '处理失败')], max_length=16, verbose_name='状态')),
                ('http_status', models.PositiveSmallIntegerField(default=200, verbose_name='HTTP 状态码')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='来源地址')),
                ('alert_count', models.PositiveIntegerField(default=0, verbose_name='告警数量')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='处理耗时毫秒')),
                ('message', models.CharField(blank=True, default='', max_length=500, verbose_name='处理结果')),
                ('payload_summary', models.JSONField(blank=True, default=dict, verbose_name='载荷摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingress_logs', to='ops.externalalertsource', verbose_name='接入源')),
            ],
            options={
                'verbose_name': '外部告警接入日志',
                'verbose_name_plural': '外部告警接入日志',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='ingress_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='ops.externalalertsource', verbose_name='外部告警接入源'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['ingress_source', 'binding_status'], name='ops_alert_ingress_adaa50_idx'),
        ),
        migrations.AddIndex(
            model_name='externalalertingresslog',
            index=models.Index(fields=['source', 'created_at'], name='ops_externa_source__dad76d_idx'),
        ),
    ]
