# Generated by Django 5.2.16 on 2026-07-27 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0097_alert_binding_status_externalalertsource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertnotificationpolicy',
            name='external_alert_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_policies', to='ops.externalalertsource', verbose_name='外部告警接入源'),
        ),
        migrations.AddIndex(
            model_name='alertnotificationpolicy',
            index=models.Index(fields=['external_alert_source', 'is_enabled', 'priority'], name='ops_anp_ext_enabled_prio_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertnotificationpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('metric_datasource__isnull', True), ('external_alert_source__isnull', True), _connector='OR'), name='ops_policy_single_source_scope'),
        ),
    ]
