# Generated by Django 5.2.16 on 2026-07-29 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0101_alter_logdatasource_provider'),
        ('resource_center', '0002_seed_resource_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='matched_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='resource_center.resource', verbose_name='关联资源中心资源'),
        ),
        migrations.AddField(
            model_name='alert',
            name='resource_match_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='资源匹配依据'),
        ),
        migrations.AddField(
            model_name='alert',
            name='resource_match_status',
            field=models.CharField(choices=[('unmatched', '未匹配'), ('matched', '已匹配'), ('conflict', '匹配冲突')], db_index=True, default='unmatched', max_length=16, verbose_name='资源匹配状态'),
        ),
        migrations.AddField(
            model_name='alertnotificationpolicy',
            name='use_resource_contacts',
            field=models.BooleanField(default=False, verbose_name='追加资源负责人'),
        ),
    ]
