# Generated by Django 5.2.16 on 2026-07-29 12:24

import django.db.models.deletion
import ops.models
import uuid
from django.conf import settings
from django.db import migrations, models


def clear_legacy_alert_domain(apps, schema_editor):
    """The unified source model intentionally starts with a clean alert domain."""
    for model_name in (
        'AlertNotificationLog',
        'AlertAnalysis',
        'AlertAction',
        'AlertClaim',
        'AlertInteractionToken',
        'AlertRuleState',
        'ExternalAlertIngressLog',
        'Alert',
        'AlertNotificationPolicy',
        'AlertRule',
        'AlertSilence',
        'ExternalAlertSource',
    ):
        model = apps.get_model('ops', model_name)
        model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0027_alter_aiopsknowledgeenvironment_k8s_cluster_and_more'),
        ('ops', '0102_alert_matched_resource_alert_resource_match_reason_and_more'),
        ('resource_center', '0003_resource_business_contexts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertNotificationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('critical', '严重'), ('warning', '警告'), ('info', '信息')], max_length=16, verbose_name='告警级别')),
                ('trigger', models.CharField(choices=[('immediate', '立即发送'), ('unacknowledged', '未认领升级')], default='immediate', max_length=24, verbose_name='触发阶段')),
                ('after_minutes', models.PositiveIntegerField(default=0, verbose_name='等待分钟')),
                ('escalate_to_level', models.CharField(blank=True, choices=[('critical', '严重'), ('warning', '警告'), ('info', '信息')], default='', max_length=16, verbose_name='升级后级别')),
                ('target_type', models.CharField(choices=[('fixed', '固定目的地'), ('source_owners', '告警源负责人'), ('recipient_group', '指定接收组'), ('resource_contacts', '资源负责人')], default='fixed', max_length=32, verbose_name='接收对象')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='顺序')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '告警通知路由',
                'verbose_name_plural': '告警通知路由',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AlertSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='告警源名称')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='告警源编码')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Webhook 接入标识')),
                ('provider', models.CharField(choices=[('prometheus', 'Prometheus'), ('alertmanager', 'Alertmanager'), ('zabbix', 'Zabbix')], max_length=32, verbose_name='告警源类型')),
                ('field_mapping', models.JSONField(blank=True, default=dict, verbose_name='字段映射')),
                ('fingerprint_fields', models.JSONField(blank=True, default=list, verbose_name='指纹字段')),
                ('token_digest', models.CharField(blank=True, default='', max_length=64, verbose_name='Token 摘要')),
                ('token_hint', models.CharField(blank=True, default='', max_length=8, verbose_name='Token 尾号')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用告警源')),
                ('notify_enabled', models.BooleanField(default=True, verbose_name='发送通知')),
                ('analyze_enabled', models.BooleanField(default=True, verbose_name='执行智能研判')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=120, verbose_name='每分钟请求上限')),
                ('last_received_at', models.DateTimeField(blank=True, null=True, verbose_name='最近请求时间')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='最近成功时间')),
                ('last_error_at', models.DateTimeField(blank=True, null=True, verbose_name='最近失败时间')),
                ('last_error', models.CharField(blank=True, default='', max_length=500, verbose_name='最近失败原因')),
                ('total_requests', models.PositiveBigIntegerField(default=0, verbose_name='请求总数')),
                ('accepted_requests', models.PositiveBigIntegerField(default=0, verbose_name='成功请求数')),
                ('rejected_requests', models.PositiveBigIntegerField(default=0, verbose_name='拒绝请求数')),
                ('received_alerts', models.PositiveBigIntegerField(default=0, verbose_name='接收告警数')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '告警源',
                'verbose_name_plural': '告警源',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AlertSourceOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', '主负责人'), ('collaborator', '协同负责人')], default='collaborator', max_length=16, verbose_name='责任角色')),
                ('levels', models.JSONField(blank=True, default=ops.models.default_alert_owner_levels, verbose_name='负责级别')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '告警源负责人',
                'verbose_name_plural': '告警源负责人',
                'ordering': ['alert_source_id', 'role', 'id'],
            },
        ),
        migrations.RunPython(clear_legacy_alert_domain, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='alertnotificationpolicy',
            name='ops_policy_single_source_scope',
        ),
        migrations.RemoveConstraint(
            model_name='alertrule',
            name='uniq_ops_alert_rule_template_ds',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='ops_alert_ingress_adaa50_idx',
        ),
        migrations.RemoveIndex(
            model_name='alertnotificationpolicy',
            name='ops_anp_ds_enabled_prio_idx',
        ),
        migrations.RemoveIndex(
            model_name='alertnotificationpolicy',
            name='ops_anp_ext_enabled_prio_idx',
        ),
        migrations.RemoveIndex(
            model_name='alertrule',
            name='ops_ar_ds_tpl_enabled_idx',
        ),
        migrations.RemoveField(
            model_name='externalalertsource',
            name='default_knowledge_environment',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='ingress_source',
        ),
        migrations.RemoveField(
            model_name='alertnotificationpolicy',
            name='external_alert_source',
        ),
        migrations.RemoveField(
            model_name='alertnotificationpolicy',
            name='channels',
        ),
        migrations.RemoveField(
            model_name='alertnotificationpolicy',
            name='escalation_steps',
        ),
        migrations.RemoveField(
            model_name='alertnotificationpolicy',
            name='level_channel_ids',
        ),
        migrations.RemoveField(
            model_name='alertnotificationpolicy',
            name='metric_datasource',
        ),
        migrations.RemoveField(
            model_name='alertnotificationpolicy',
            name='recipient_groups',
        ),
        migrations.RemoveField(
            model_name='alertnotificationpolicy',
            name='use_resource_contacts',
        ),
        migrations.RemoveField(
            model_name='alertrule',
            name='metric_datasource',
        ),
        migrations.AddField(
            model_name='alertrule',
            name='template_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_rule_templates', to=settings.AUTH_USER_MODEL, verbose_name='模板创建人'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='template_status',
            field=models.CharField(choices=[('draft', '草稿'), ('review', '待审核'), ('published', '已发布'), ('archived', '已归档')], db_index=True, default='draft', max_length=16, verbose_name='模板状态'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='template_version',
            field=models.PositiveIntegerField(default=1, verbose_name='模板版本'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='source_type',
            field=models.CharField(choices=[('platform', '平台告警规则'), ('prometheus', 'Prometheus'), ('zabbix', 'Zabbix'), ('alertmanager', 'Alertmanager')], default='platform', max_length=32, verbose_name='来源类型'),
        ),
        migrations.AddField(
            model_name='alertnotificationroute',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_routes', to='ops.alertnotificationchannel', verbose_name='通知目的地'),
        ),
        migrations.AddField(
            model_name='alertnotificationroute',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='ops.alertnotificationpolicy', verbose_name='通知策略'),
        ),
        migrations.AddField(
            model_name='alertnotificationroute',
            name='recipient_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_routes', to='ops.alertrecipientgroup', verbose_name='接收组'),
        ),
        migrations.AddField(
            model_name='alertsource',
            name='metric_datasource',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alert_source', to='ops.metricdatasource', verbose_name='Prometheus 指标数据源'),
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='ops.alertsource', verbose_name='告警源'),
        ),
        migrations.AddField(
            model_name='alertnotificationpolicy',
            name='alert_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_policies', to='ops.alertsource', verbose_name='告警源'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='alert_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='ops.alertsource', verbose_name='告警源'),
        ),
        migrations.AlterField(
            model_name='externalalertingresslog',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingress_logs', to='ops.alertsource', verbose_name='告警源'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_source', 'status'], name='ops_alert_source_status_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnotificationpolicy',
            index=models.Index(fields=['alert_source', 'is_enabled', 'priority'], name='ops_anp_src_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['alert_source', 'is_template', 'is_enabled'], name='ops_ar_src_tpl_enabled_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertrule',
            constraint=models.UniqueConstraint(condition=models.Q(('alert_source__isnull', False), ('is_template', False), ('template__isnull', False)), fields=('template', 'alert_source'), name='uniq_ops_alert_rule_template_source'),
        ),
        migrations.AddField(
            model_name='alertsourceowner',
            name='alert_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_bindings', to='ops.alertsource', verbose_name='告警源'),
        ),
        migrations.AddField(
            model_name='alertsourceowner',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_source_bindings', to='ops.alertrecipient', verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='alertsource',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owned_alert_sources', through='ops.AlertSourceOwner', to='ops.alertrecipient', verbose_name='负责人'),
        ),
        migrations.AddConstraint(
            model_name='alertnotificationroute',
            constraint=models.UniqueConstraint(fields=('policy', 'level', 'trigger', 'channel', 'target_type', 'recipient_group'), name='uniq_ops_alert_notification_route'),
        ),
        migrations.DeleteModel(
            name='ExternalAlertSource',
        ),
        migrations.AddConstraint(
            model_name='alertsourceowner',
            constraint=models.UniqueConstraint(fields=('alert_source', 'recipient'), name='uniq_ops_alert_source_owner'),
        ),
        migrations.AddConstraint(
            model_name='alertsourceowner',
            constraint=models.UniqueConstraint(condition=models.Q(('is_enabled', True), ('role', 'primary')), fields=('alert_source',), name='uniq_ops_alert_source_primary_owner'),
        ),
        migrations.AddConstraint(
            model_name='alertsource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('metric_datasource__isnull', False), ('provider', 'prometheus')), models.Q(('provider', 'prometheus'), _negated=True), _connector='OR'), name='ops_alert_source_prometheus_ds'),
        ),
    ]
