# Generated by Django 5.2.16 on 2026-08-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0104_alertnotificationpolicy_alert_source_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='k8scluster',
            name='tls_skip_verify',
            field=models.BooleanField(default=False, verbose_name='跳过 TLS 证书校验'),
        ),
    ]
