# Generated by Django 5.2.16 on 2026-08-05 09:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0105_k8scluster_tls_skip_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(db_index=True, default='system', max_length=32, verbose_name='来源类别')),
                ('kind', models.CharField(db_index=True, max_length=64, verbose_name='事件类型')),
                ('severity', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('danger', '危险')], default='info', max_length=16, verbose_name='级别')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='标题')),
                ('message', models.TextField(blank=True, default='', verbose_name='描述')),
                ('target_type', models.CharField(blank=True, default='', max_length=64, verbose_name='目标类别')),
                ('target_resource', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='目标标识')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='附加数据')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='发生时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='ops.alert', verbose_name='关联告警')),
            ],
            options={
                'verbose_name': '事件',
                'verbose_name_plural': '事件',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['source_type', 'kind'], name='ops_event_source__d362d1_idx'), models.Index(fields=['-occurred_at'], name='ops_event_occurre_89bcaa_idx')],
            },
        ),
    ]
