# Generated by Django 5.2.16 on 2026-08-06 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0106_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='converge_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='收敛聚合键'),
        ),
        migrations.AddField(
            model_name='alert',
            name='group_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_children', to='ops.alert', verbose_name='聚合父告警'),
        ),
        migrations.AddField(
            model_name='alert',
            name='is_group_root',
            field=models.BooleanField(default=False, verbose_name='是否聚合根'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='converge_enabled',
            field=models.BooleanField(default=False, verbose_name='启用收敛'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='group_fields',
            field=models.JSONField(blank=True, default=list, verbose_name='收敛分组键'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='suppress_ancestor_hops',
            field=models.PositiveIntegerField(default=3, verbose_name='抑制祖先层数'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='suppress_by_topology',
            field=models.BooleanField(default=False, verbose_name='拓扑抑制'),
        ),
        migrations.AddField(
            model_name='alertsource',
            name='converge_enabled',
            field=models.BooleanField(default=False, verbose_name='启用收敛'),
        ),
        migrations.AddField(
            model_name='alertsource',
            name='converge_group_fields',
            field=models.JSONField(blank=True, default=list, verbose_name='收敛分组键'),
        ),
        migrations.AddField(
            model_name='alertsource',
            name='converge_window_minutes',
            field=models.PositiveIntegerField(default=5, verbose_name='收敛窗口(分钟)'),
        ),
        migrations.AddField(
            model_name='alertsource',
            name='suppress_ancestor_hops',
            field=models.PositiveIntegerField(default=3, verbose_name='抑制祖先层数'),
        ),
        migrations.AddField(
            model_name='alertsource',
            name='suppress_by_topology',
            field=models.BooleanField(default=False, verbose_name='拓扑抑制'),
        ),
    ]
