# Generated by Django 5.2.16 on 2026-08-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0107_alert_converge_key_alert_group_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='suppressed_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='抑制原因'),
        ),
    ]
