# Generated by Django 5.2.16 on 2026-08-06 07:25

import django.db.models.deletion
import ops.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0108_alert_suppressed_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnCallSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='班次名称')),
                ('weekday_bits', models.PositiveIntegerField(default=127, verbose_name='星期位图')),
                ('start_time', models.TimeField(default=ops.models.default_oncall_start_time, verbose_name='开始时间')),
                ('end_time', models.TimeField(default=ops.models.default_oncall_end_time, verbose_name='结束时间')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('recipient_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oncall_schedules', to='ops.alertrecipientgroup', verbose_name='值班接收组')),
            ],
            options={
                'verbose_name': '值班班次',
                'verbose_name_plural': '值班班次',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='alertnotificationpolicy',
            name='oncall_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='ops.oncallschedule', verbose_name='值班班次'),
        ),
        migrations.CreateModel(
            name='AlertTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ops.alert', verbose_name='告警')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_ticket_links', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_links', to='ops.transactionticket', verbose_name='工单')),
            ],
            options={
                'verbose_name': '告警工单关联',
                'verbose_name_plural': '告警工单关联',
                'constraints': [models.UniqueConstraint(fields=('alert', 'ticket'), name='uniq_ops_alert_ticket')],
            },
        ),
    ]
