# Generated by Django 5.2.16 on 2026-08-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0109_oncallschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='detector',
            field=models.JSONField(blank=True, default=dict, verbose_name='检测算法'),
        ),
    ]
